'use strict';
// Storm Directive - game data: elements, weapons, spells, merges, passives, enemies, bosses, directives.

const ELEMENTS = {
  phys:   { name: 'Kinetic', color: '#e8eef8' },
  fire:   { name: 'Fire',    color: '#ff7a2f' },
  ice:    { name: 'Frost',   color: '#6fd8ff' },
  shock:  { name: 'Shock',   color: '#ffe94a' },
  poison: { name: 'Toxic',   color: '#8dff4a' },
  arcane: { name: 'Arcane',  color: '#c77dff' },
};

// Targeting directives. Each weapon/spell runs one of these.
const DIRECTIVES = [
  { id: 'nearest',   name: 'NEAREST',        short: 'NEAR' },
  { id: 'strongest', name: 'STRONGEST',      short: 'STRG' },
  { id: 'weakest',   name: 'WEAKEST',        short: 'WEAK' },
  { id: 'lowhp',     name: 'LOWEST HEALTH',  short: 'LOW HP' },
  { id: 'highhp',    name: 'HIGHEST HEALTH', short: 'HI HP' },
  { id: 'armour',    name: 'HIGHEST ARMOUR', short: 'ARMR' },
  { id: 'fastest',   name: 'FASTEST',        short: 'FAST' },
  { id: 'furthest',  name: 'FURTHEST',       short: 'FAR' },
  { id: 'cluster',   name: 'DENSEST CLUSTER', short: 'CLSTR' },
  { id: 'elite',     name: 'ELITES & BOSSES', short: 'ELITE' },
  { id: 'shooters',  name: 'SHOOTERS FIRST', short: 'SHOOT' },
  { id: 'random',    name: 'RANDOM',         short: 'RAND' },
  { id: 'revenge',   name: 'REVENGE',        short: 'GRUDGE' },
];

// Movement (autorun) directives.
const MOVE_DIRECTIVES = [
  { id: 'kite',    name: 'KITE',    desc: 'Keep distance from threats, dodge bullets' },
  { id: 'collect', name: 'COLLECT', desc: 'Hoover up XP and power-ups' },
  { id: 'orbit',   name: 'ORBIT',   desc: 'Circle around the horde' },
  { id: 'hunt',    name: 'HUNT',    desc: 'Close in on the primary target' },
  { id: 'hold',    name: 'HOLD',    desc: 'Stand ground, only dodge bullets' },
  { id: 'defend',  name: 'DEFEND',  desc: 'Guard the Chrono Anchor and intercept siege lines' },
];

// Level bonus keys: count, pierce, chain, bounce (additive); dmg, area, dur (additive %); cd (negative = faster).
const WEAPONS = {
  blaster: { name: 'Blaster', icon: 'BL', elem: 'phys', kind: 'gun', color: '#e8f0ff', dir: 'nearest',
    desc: 'Reliable sidearm. Accurate single shots.',
    base: { dmg: 10, cd: 0.3, mag: 12, reload: 1.1, count: 1, spread: 0.04, speed: 640, pierce: 0, range: 430, size: 4 },
    lv: { 3: { pierce: 1 }, 5: { count: 1 }, 7: { dmg: 0.3 } } },
  smg: { name: 'Storm SMG', icon: 'SM', elem: 'phys', kind: 'gun', color: '#cfd8ff', dir: 'nearest',
    desc: 'Sprays a hail of light rounds. Big magazine, long reload.',
    base: { dmg: 4.5, cd: 0.075, mag: 36, reload: 1.7, count: 1, spread: 0.2, speed: 580, pierce: 0, range: 370, size: 3 },
    lv: { 3: { cd: -0.15 }, 5: { pierce: 1 }, 7: { count: 1 } } },
  shotgun: { name: 'Scattergun', icon: 'SG', elem: 'phys', kind: 'gun', color: '#ffd6a5', dir: 'nearest',
    desc: 'Close-range pellet burst with knockback.',
    base: { dmg: 8, cd: 0.75, mag: 4, reload: 1.6, count: 6, spread: 0.55, speed: 540, pierce: 0, range: 270, size: 3.5, knock: 70 },
    lv: { 3: { count: 2 }, 5: { pierce: 1 }, 7: { count: 3 } } },
  railgun: { name: 'Railgun', icon: 'RG', elem: 'phys', kind: 'gun', color: '#9ef0ff', dir: 'armour', style: 'rail',
    desc: 'Hypersonic slug. Pierces everything and shreds armour.',
    base: { dmg: 42, cd: 1.3, mag: 3, reload: 2.2, count: 1, spread: 0.05, speed: 1700, pierce: 99, range: 720, size: 3, shred: 3 },
    lv: { 3: { shred: 2 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  rocket: { name: 'Rocket Pod', icon: 'RK', elem: 'fire', kind: 'gun', color: '#ffb347', dir: 'cluster', style: 'rocket',
    desc: 'Explosive rockets that ignite the blast zone.',
    base: { dmg: 24, cd: 0.55, mag: 2, reload: 2.4, count: 1, spread: 0.1, speed: 400, pierce: 0, range: 500, size: 5, explode: 62 },
    lv: { 3: { area: 0.25 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  flamer: { name: 'Flamer', icon: 'FL', elem: 'fire', kind: 'gun', color: '#ff7a2f', dir: 'nearest', style: 'flame',
    desc: 'Short-range cone of fire. Every lick burns.',
    base: { dmg: 3.2, cd: 0.05, mag: 50, reload: 2.1, count: 2, spread: 0.45, speed: 310, pierce: 99, range: 200, size: 7 },
    lv: { 3: { area: 0.3 }, 5: { dmg: 0.3 }, 7: { count: 1 } } },
  frost: { name: 'Frost Lance', icon: 'FR', elem: 'ice', kind: 'gun', color: '#6fd8ff', dir: 'fastest', style: 'shard',
    desc: 'Piercing ice shards that chill and freeze.',
    base: { dmg: 15, cd: 0.6, mag: 5, reload: 1.5, count: 1, spread: 0.08, speed: 540, pierce: 3, range: 460, size: 5 },
    lv: { 3: { count: 1 }, 5: { pierce: 3 }, 7: { count: 2 } } },
  tesla: { name: 'Tesla Coil', icon: 'TC', elem: 'shock', kind: 'chain', color: '#ffe94a', dir: 'cluster',
    desc: 'Instant lightning that arcs between enemies.',
    base: { dmg: 13, cd: 0.7, mag: 6, reload: 1.8, count: 1, chain: 3, range: 330, jump: 140 },
    lv: { 3: { chain: 2 }, 5: { count: 1 }, 7: { chain: 3 } } },
  venom: { name: 'Venom Spitter', icon: 'VS', elem: 'poison', kind: 'lob', color: '#8dff4a', dir: 'cluster',
    desc: 'Lobs acid globs that leave toxic puddles.',
    base: { dmg: 9, cd: 0.9, mag: 4, reload: 1.8, count: 1, spread: 40, range: 390, area: 55, dur: 3, flight: 0.6 },
    lv: { 3: { dur: 0.5 }, 5: { count: 1 }, 7: { area: 0.4 } } },
  glaive: { name: 'Glaive', icon: 'GL', elem: 'phys', kind: 'gun', color: '#f1f1f1', dir: 'furthest', style: 'glaive',
    desc: 'Spinning blade that flies out and returns.',
    base: { dmg: 15, cd: 1.0, mag: 2, reload: 1.3, count: 1, spread: 0.3, speed: 430, pierce: 99, range: 330, size: 10, boomerang: 1 },
    lv: { 3: { count: 1 }, 5: { dmg: 0.3 }, 7: { count: 1 } } },
  orbit: { name: 'Orbital Blades', icon: 'OB', elem: 'arcane', kind: 'orbit', color: '#c77dff', dir: 'nearest',
    desc: 'Arcane blades orbit you. Active, then recharge.',
    base: { dmg: 16, count: 3, dur: 4.5, reload: 2.2, radius: 72, spin: 3.6, size: 10, range: 100 },
    lv: { 3: { count: 1 }, 5: { area: 0.3 }, 7: { count: 2 } } },
  prism: { name: 'Prism Beam', icon: 'PB', elem: 'arcane', kind: 'beam', color: '#e0aaff', dir: 'strongest',
    desc: 'Channelled beam that burns through a line of foes.',
    base: { dmg: 32, cd: 1.7, mag: 3, reload: 2.2, count: 1, dur: 1.2, range: 390, size: 6 },
    lv: { 3: { dur: 0.35 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  mines: { name: 'Mine Layer', icon: 'ML', elem: 'fire', kind: 'mine', color: '#ff9f1c', dir: 'nearest',
    desc: 'Drops proximity mines in your wake.',
    base: { dmg: 32, cd: 0.7, mag: 5, reload: 2.4, count: 1, explode: 72, life: 14, range: 600 },
    lv: { 3: { count: 1 }, 5: { area: 0.3 }, 7: { dmg: 0.5 } } },
  seeker: { name: 'Seeker Swarm', icon: 'SS', elem: 'arcane', kind: 'gun', color: '#d0a3ff', dir: 'weakest', style: 'missile',
    desc: 'Homing micro-missiles that never miss.',
    base: { dmg: 9, cd: 0.45, mag: 6, reload: 2.0, count: 2, spread: 1.2, speed: 320, pierce: 0, range: 500, size: 4, homing: 5 },
    lv: { 3: { count: 1 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  gatling: { name: 'Gatling', icon: 'GT', elem: 'phys', kind: 'gun', color: '#ffe8a3', dir: 'nearest', spinup: 1,
    desc: 'Spins up to a terrifying fire rate. Huge belt.',
    base: { dmg: 5.5, cd: 0.14, mag: 120, reload: 3.2, count: 1, spread: 0.13, speed: 720, pierce: 0, range: 450, size: 3 },
    lv: { 3: { pierce: 1 }, 5: { count: 1 }, 7: { dmg: 0.3 } } },
  drone: { name: 'Attack Drone', icon: 'DR', elem: 'shock', kind: 'gun', color: '#fff275', dir: 'lowhp', drones: 1,
    desc: 'Drones hover beside you and fire shock bolts.',
    base: { dmg: 8, cd: 0.45, mag: 10, reload: 1.5, count: 1, spread: 0.05, speed: 620, pierce: 0, range: 420, size: 3.5 },
    lv: { 3: { count: 1 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  ricochet: { name: 'Ricochet Disc', icon: 'RD', elem: 'phys', kind: 'gun', color: '#a0c4ff', dir: 'nearest', style: 'disc',
    desc: 'Discs bounce from enemy to enemy.',
    base: { dmg: 13, cd: 0.8, mag: 3, reload: 1.5, count: 1, spread: 0.1, speed: 500, pierce: 0, range: 420, size: 6, bounce: 3 },
    lv: { 3: { bounce: 2 }, 5: { count: 1 }, 7: { bounce: 3 } } },
  mortar: { name: 'Mortar', icon: 'MR', elem: 'fire', kind: 'lob', color: '#ff6b35', dir: 'cluster',
    desc: 'Slow, heavy shells with a huge blast.',
    base: { dmg: 42, cd: 1.6, mag: 2, reload: 2.5, count: 1, spread: 30, range: 540, area: 82, flight: 1.0, explode: 1 },
    lv: { 3: { area: 0.25 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  arbalest: { name: 'Arbalest', icon: 'AB', elem: 'phys', kind: 'gun', color: '#d4a373', dir: 'strongest', style: 'bolt',
    desc: 'Heavy bolts. Massive knockback, light armour shred.',
    base: { dmg: 24, cd: 0.9, mag: 4, reload: 1.6, count: 1, spread: 0.05, speed: 820, pierce: 2, range: 540, size: 4, knock: 220, shred: 1 },
    lv: { 3: { pierce: 2 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  void: { name: 'Void Orb', icon: 'VO', elem: 'arcane', kind: 'gun', color: '#7b2cbf', dir: 'cluster', style: 'void',
    desc: 'Slow orb that drags enemies into its maw.',
    base: { dmg: 7, cd: 1.8, mag: 2, reload: 2.5, count: 1, spread: 0.2, speed: 115, pierce: 99, range: 400, size: 15, aura: 70, pull: 90 },
    lv: { 3: { area: 0.3 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  needler: { name: 'Needler', icon: 'ND', elem: 'poison', kind: 'gun', color: '#b8f35a', dir: 'highhp', style: 'needle',
    desc: 'Rapid toxic needles. Poison stacks up.',
    base: { dmg: 3.5, cd: 0.1, mag: 30, reload: 1.6, count: 1, spread: 0.1, speed: 680, pierce: 0, range: 410, size: 2.5 },
    lv: { 3: { count: 1 }, 5: { pierce: 1 }, 7: { cd: -0.2 } } },
  hailstorm: { name: 'Hailstorm', icon: 'HS', elem: 'ice', kind: 'lob', color: '#a2d2ff', dir: 'cluster',
    desc: 'Rains ice chunks around the target.',
    base: { dmg: 11, cd: 1.4, mag: 2, reload: 2.0, count: 5, spread: 90, range: 460, area: 36, flight: 0.7, explode: 1 },
    lv: { 3: { count: 2 }, 5: { area: 0.3 }, 7: { count: 3 } } },

  paradox: { name: 'Paradox Rifle', icon: 'PX', elem: 'arcane', kind: 'gun', color: '#7df9ff', dir: 'strongest', style: 'bolt',
    desc: 'Every hit repeats itself 1 second later, from the future.',
    base: { dmg: 16, cd: 0.55, mag: 6, reload: 1.6, count: 1, spread: 0.04, speed: 760, pierce: 1, range: 480, size: 4, echoHit: 1 },
    lv: { 3: { pierce: 1 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },

  // ---- Merged weapons (not in the random pool; created by fusing two maxed-enough weapons) ----
  steam: { name: 'Steam Cannon', icon: 'ST', elem: 'fire', elem2: 'ice', kind: 'gun', color: '#ffc6ff', dir: 'nearest', style: 'flame', merged: 1,
    desc: 'Scalding fire-and-frost cone. Triggers reactions constantly.',
    base: { dmg: 8, cd: 0.055, mag: 70, reload: 1.9, count: 3, spread: 0.5, speed: 380, pierce: 99, range: 250, size: 9 },
    lv: { 5: { area: 0.3 }, 7: { count: 1 } } },
  thunderbuck: { name: 'Thunder Buckshot', icon: 'TB', elem: 'shock', kind: 'gun', color: '#fff3b0', dir: 'nearest', merged: 1,
    desc: 'Each pellet detonates into chain lightning.',
    base: { dmg: 11, cd: 0.7, mag: 5, reload: 1.4, count: 8, spread: 0.6, speed: 580, pierce: 0, range: 310, size: 4, chainHit: 2, knock: 60 },
    lv: { 5: { count: 2 }, 7: { dmg: 0.3 } } },
  annihilator: { name: 'Annihilator', icon: 'AN', elem: 'arcane', kind: 'beam', color: '#f72585', dir: 'strongest', merged: 1,
    desc: 'Colossal armour-shredding beam across the screen.',
    base: { dmg: 130, cd: 2.4, mag: 2, reload: 2.5, count: 1, dur: 1.5, range: 820, size: 14, shred: 5 },
    lv: { 5: { dur: 0.4 }, 7: { count: 1 } } },
  hydra: { name: 'Hydra Barrage', icon: 'HB', elem: 'fire', kind: 'gun', color: '#ff9e00', dir: 'elite', style: 'rocket', merged: 1,
    desc: 'Volleys of homing explosive rockets.',
    base: { dmg: 22, cd: 0.5, mag: 4, reload: 2.2, count: 4, spread: 1.6, speed: 350, pierce: 0, range: 540, size: 5, homing: 6, explode: 58 },
    lv: { 5: { count: 2 }, 7: { area: 0.3 } } },
  cyclone: { name: 'Cyclone Glaives', icon: 'CG', elem: 'phys', kind: 'orbit', color: '#ffffff', dir: 'nearest', merged: 1,
    desc: 'Six glaives pulse outward and back in a storm.',
    base: { dmg: 30, count: 6, dur: 6, reload: 1.4, radius: 70, spin: 4.2, size: 12, range: 170, pulse: 1 },
    lv: { 5: { count: 2 }, 7: { dmg: 0.4 } } },
  pinball: { name: 'Pinball Magnum', icon: 'PM', elem: 'phys', kind: 'gun', color: '#caffbf', dir: 'nearest', style: 'disc', merged: 1,
    desc: 'Magnum rounds that ricochet 6 times. Crits often.',
    base: { dmg: 22, cd: 0.35, mag: 8, reload: 1.2, count: 1, spread: 0.05, speed: 720, pierce: 0, range: 470, size: 5, bounce: 6, critBonus: 0.2 },
    lv: { 5: { bounce: 3 }, 7: { count: 1 } } },
  plague: { name: 'Plague Mortar', icon: 'PL', elem: 'poison', kind: 'lob', color: '#70e000', dir: 'cluster', merged: 1,
    desc: 'Toxic shells: huge blast plus a lingering plague pool.',
    base: { dmg: 46, cd: 1.4, mag: 3, reload: 2.2, count: 1, spread: 40, range: 540, area: 96, dur: 5, flight: 0.9, explode: 1 },
    lv: { 5: { count: 1 }, 7: { area: 0.3 } } },
  singularity: { name: 'Singularity Mines', icon: 'SI', elem: 'arcane', kind: 'mine', color: '#9d4edd', dir: 'nearest', merged: 1,
    desc: 'Mines open a black hole, then detonate.',
    base: { dmg: 55, cd: 0.8, mag: 4, reload: 2.2, count: 1, explode: 95, life: 16, range: 600, singularity: 1 },
    lv: { 5: { count: 1 }, 7: { dmg: 0.5 } } },
  hive: { name: 'Drone Hive', icon: 'DH', elem: 'shock', kind: 'gun', color: '#ffee32', dir: 'lowhp', drones: 1, merged: 1,
    desc: 'Four drones with SMG fire rates.',
    base: { dmg: 6.5, cd: 0.12, mag: 40, reload: 1.8, count: 4, spread: 0.1, speed: 640, pierce: 0, range: 440, size: 3 },
    lv: { 5: { count: 2 }, 7: { dmg: 0.4 } } },
  siege: { name: 'Siege Repeater', icon: 'SR', elem: 'phys', kind: 'gun', color: '#e9c46a', dir: 'armour', style: 'bolt', spinup: 1, merged: 1,
    desc: 'Automatic heavy bolts. Pierce, shred, knockback.',
    base: { dmg: 17, cd: 0.15, mag: 60, reload: 2.4, count: 1, spread: 0.08, speed: 860, pierce: 4, range: 560, size: 4, knock: 140, shred: 2 },
    lv: { 5: { pierce: 3 }, 7: { count: 1 } } },
  zero: { name: 'Absolute Zero', icon: 'AZ', elem: 'ice', kind: 'lob', color: '#caf0f8', dir: 'cluster', merged: 1,
    desc: 'Ice meteors that flash-freeze everything hit.',
    base: { dmg: 18, cd: 1.3, mag: 3, reload: 1.8, count: 8, spread: 110, range: 500, area: 48, flight: 0.7, explode: 1, freezeHit: 1 },
    lv: { 5: { count: 3 }, 7: { dmg: 0.4 } } },
  neuro: { name: 'Neurotoxin Arc', icon: 'NA', elem: 'poison', elem2: 'shock', kind: 'chain', color: '#d9ed92', dir: 'cluster', merged: 1,
    desc: 'Toxic lightning. Every arc spreads plague.',
    base: { dmg: 9, cd: 0.25, mag: 12, reload: 1.6, count: 1, chain: 6, range: 360, jump: 150 },
    lv: { 5: { chain: 3 }, 7: { count: 1 } } },

  // ---- Show-season weapons
  siphon: { name: 'Bullet Siphon', icon: 'BU', elem: 'arcane', kind: 'siphon', color: '#ff3df2', dir: 'nearest',
    desc: 'Eats enemy bullets that come near you and spits them back. No reloads. No ammo either, until the screen is full of bullets.',
    base: { dmg: 18, cd: 0.08, mag: 40, area: 90, speed: 640, range: 460, size: 4.5, pierce: 0, spread: 0.08, count: 1 },
    lv: { 3: { count: 1 }, 5: { pierce: 1 }, 7: { dmg: 0.4 } } },
  committee: { name: 'Committee Cannon', icon: 'CC', elem: 'phys', kind: 'gun', committee: 1, color: '#ffd6a5', dir: 'strongest',
    desc: 'Three barrels, three directives, zero consensus. Set each barrel in the pause menu.',
    base: { dmg: 9, cd: 0.45, mag: 9, reload: 1.6, count: 1, spread: 0.05, speed: 640, pierce: 0, range: 450, size: 4 },
    lv: { 3: { pierce: 1 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  grudge: { name: 'Grudge Rifle', icon: 'GR', elem: 'phys', kind: 'gun', grudge: 1, color: '#ff4d6d', dir: 'revenge', style: 'bolt',
    desc: 'Remembers whatever last hurt you. Hunts it across the whole map. Triple damage to it. Very healthy.',
    base: { dmg: 20, cd: 0.6, mag: 5, reload: 1.5, count: 1, spread: 0.02, speed: 900, pierce: 0, range: 480, size: 4, homing: 3 },
    lv: { 3: { pierce: 1 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  wake: { name: 'Wake Blade', icon: 'WB', elem: 'phys', kind: 'wake', color: '#e0fbfc', dir: 'nearest', noTarget: 1,
    desc: 'Your flight path becomes a blade. Keep moving, or it is just very expensive litter.',
    base: { dmg: 22, dur: 2.2, area: 22, range: 0 },
    lv: { 3: { area: 0.3 }, 5: { dur: 0.5 }, 7: { dmg: 0.5 } } },
  scrapcannon: { name: 'Scrap Cannon', icon: 'SK', elem: 'phys', kind: 'gun', scrapAmmo: 1, color: '#ffb400', dir: 'strongest', style: 'scrap',
    desc: 'Fires your savings. 1 scrap per shot, enormous bang. Financial advisers weep.',
    base: { dmg: 55, cd: 0.8, mag: 99, reload: 0.5, count: 1, spread: 0.1, speed: 520, pierce: 0, range: 480, size: 7, explode: 55, knock: 120 },
    lv: { 3: { area: 0.25 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  mimic: { name: 'Mimic Core', icon: 'MI', elem: 'arcane', kind: 'mimic', color: '#f15bb5', dir: 'nearest',
    desc: 'Copies the attack pattern of the last shooter you killed. It is not plagiarism if you win.',
    base: { dmg: 10, cd: 0.9, mag: 6, reload: 1.8, count: 1, speed: 330, range: 430, size: 5, pierce: 1 },
    lv: { 3: { dmg: 0.3 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  parasite: { name: 'Parasite Seeder', icon: 'PS', elem: 'poison', kind: 'gun', parasite: 1, color: '#b5e48c', dir: 'highhp', style: 'needle',
    desc: 'Infects enemies. When they die, the corpse becomes your turret for 8 seconds. Ethically grey, tactically green.',
    base: { dmg: 11, cd: 0.4, mag: 8, reload: 1.6, count: 1, spread: 0.08, speed: 560, pierce: 0, range: 430, size: 3.5, dur: 8 },
    lv: { 3: { count: 1 }, 5: { dur: 0.5 }, 7: { dmg: 0.4 } } },
  thermal: { name: 'Thermal Lance', icon: 'TH', elem: 'fire', kind: 'beam', heat: 1, color: '#ff5400', dir: 'nearest',
    desc: 'No magazine, just heat. Overheat and it vents a fireball around you. Warranty void.',
    base: { dmg: 38, cd: 0, mag: 1, reload: 1.3, count: 1, dur: 3.2, range: 300, size: 5, area: 150 },
    lv: { 3: { dur: 0.3 }, 5: { area: 0.3 }, 7: { dmg: 0.4 } } },
  tether: { name: 'Tether Coil', icon: 'TE', elem: 'shock', kind: 'tether', color: '#9ef0ff', dir: 'highhp',
    desc: 'Ties two monsters together with a lightning leash and makes them hug. Violently.',
    base: { dmg: 16, cd: 1.1, mag: 3, reload: 1.8, count: 1, dur: 3, range: 380, pull: 170, jump: 240 },
    lv: { 3: { count: 1 }, 5: { dur: 0.4 }, 7: { dmg: 0.5 } } },
  gacha: { name: 'Gacha Blaster', icon: 'GB', elem: 'phys', kind: 'gun', gacha: 1, color: '#ffd23f', dir: 'nearest',
    desc: 'Every magazine is a loot box. Every loot box is a lie. Except the Legendary ones. Those explode.',
    base: { dmg: 12, cd: 0.22, mag: 12, reload: 1.3, count: 1, spread: 0.06, speed: 650, pierce: 0, range: 440, size: 4 },
    lv: { 3: { pierce: 1 }, 5: { count: 1 }, 7: { dmg: 0.3 } } },
  prequel: { name: 'Prequel Launcher', icon: 'PQ', elem: 'fire', kind: 'prequel', color: '#ff9e00', dir: 'cluster',
    desc: 'The explosion happens first. The shell arrives afterwards, flying backwards into the barrel, still angry.',
    base: { dmg: 34, cd: 1.1, mag: 3, reload: 2.0, count: 1, area: 70, speed: 520, range: 480, spread: 40 },
    lv: { 3: { area: 0.25 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },

  // ---- Show-season fusions
  hailreturn: { name: 'Hailreturn', icon: 'HR', elem: 'ice', kind: 'siphon', color: '#caf0f8', dir: 'nearest', style: 'shard', merged: 1,
    desc: 'Their bullets. Your ice. Everyone else\'s problem. Returned shots freeze on hit.',
    base: { dmg: 20, cd: 0.06, mag: 70, area: 105, speed: 700, range: 500, size: 5, pierce: 2, spread: 0.1, count: 1, freezeHit: 1 },
    lv: { 5: { count: 1 }, 7: { dmg: 0.4 } } },
  plaguetrail: { name: 'Plague Trail', icon: 'PT', elem: 'poison', kind: 'wake', color: '#70e000', dir: 'nearest', noTarget: 1, merged: 1,
    desc: 'You leave a lane of plague behind you. Lead the siege through it and wave.',
    base: { dmg: 30, dur: 4, area: 34, range: 0 },
    lv: { 5: { area: 0.3 }, 7: { dmg: 0.5 } } },
  salvage: { name: 'Salvage Barrage', icon: 'SB', elem: 'fire', kind: 'lob', scrapAmmo: 1, salvage: 1, color: '#ffb400', dir: 'cluster', merged: 1,
    desc: 'Shells cost scrap. Shells make scrap. It is basically a pyramid scheme with explosions.',
    base: { dmg: 50, cd: 0.9, mag: 99, reload: 0.5, count: 3, spread: 60, range: 540, area: 80, flight: 0.9, explode: 1 },
    lv: { 5: { count: 1 }, 7: { area: 0.3 } } },
};

const MERGES = [
  { a: 'flamer',  b: 'frost',     out: 'steam' },
  { a: 'shotgun', b: 'tesla',     out: 'thunderbuck' },
  { a: 'railgun', b: 'prism',     out: 'annihilator' },
  { a: 'rocket',  b: 'seeker',    out: 'hydra' },
  { a: 'glaive',  b: 'orbit',     out: 'cyclone' },
  { a: 'blaster', b: 'ricochet',  out: 'pinball' },
  { a: 'venom',   b: 'mortar',    out: 'plague' },
  { a: 'mines',   b: 'void',      out: 'singularity' },
  { a: 'drone',   b: 'smg',       out: 'hive' },
  { a: 'arbalest', b: 'gatling',  out: 'siege' },
  { a: 'frost',   b: 'hailstorm', out: 'zero' },
  { a: 'needler', b: 'tesla',     out: 'neuro' },
  { a: 'siphon',  b: 'frost',     out: 'hailreturn' },
  { a: 'wake',    b: 'venom',     out: 'plaguetrail' },
  { a: 'scrapcannon', b: 'mortar', out: 'salvage' },
];
const MERGE_MIN_LEVEL = 4;

// Spells: autocast on cooldown, occupy spell slots.
const SPELLS = {
  meteor: { name: 'Meteor', icon: 'ME', elem: 'fire', kind: 'strike', color: '#ff5400', dir: 'cluster',
    desc: 'Calls a meteor on the target. Leaves burning ground.',
    base: { dmg: 65, cd: 5, count: 1, area: 88, delay: 0.7, range: 520, dur: 2 },
    lv: { 3: { count: 1 }, 5: { area: 0.3 }, 7: { count: 1 } } },
  frostnova: { name: 'Frost Nova', icon: 'FN', elem: 'ice', kind: 'nova', color: '#90e0ef', dir: 'nearest',
    desc: 'Freezing blast around you. Erases enemy bullets.',
    base: { dmg: 22, cd: 7, area: 165, range: 170 },
    lv: { 3: { area: 0.2 }, 5: { dmg: 0.5 }, 7: { cd: -0.25 } } },
  thunder: { name: 'Thunderstorm', icon: 'TS', elem: 'shock', kind: 'thunder', color: '#fdf0d5', dir: 'strongest',
    desc: 'Lightning strikes several targets at once.',
    base: { dmg: 36, cd: 6, count: 5, area: 48, range: 520 },
    lv: { 3: { count: 2 }, 5: { dmg: 0.4 }, 7: { count: 3 } } },
  blackhole: { name: 'Black Hole', icon: 'BH', elem: 'arcane', kind: 'zone', color: '#7209b7', dir: 'cluster',
    desc: 'Tears open a singularity that drags and crushes.',
    base: { dmg: 16, cd: 10, area: 125, dur: 3, pull: 210, range: 460 },
    lv: { 3: { dur: 0.3 }, 5: { area: 0.3 }, 7: { dmg: 0.6 } } },
  heal: { name: 'Rejuvenate', icon: 'RJ', elem: 'poison', kind: 'heal', color: '#80ffdb', dir: 'nearest', noTarget: 1,
    desc: 'Restores a portion of your health.',
    base: { dmg: 0.15, cd: 14, range: 0 },
    lv: { 3: { cd: -0.15 }, 5: { dmg: 0.5 }, 7: { cd: -0.2 } } },
  warp: { name: 'Time Warp', icon: 'TW', elem: 'arcane', kind: 'warp', color: '#b8c0ff', dir: 'nearest', noTarget: 1,
    desc: 'Slows every enemy and bullet to a crawl.',
    base: { dmg: 0, cd: 16, dur: 3, range: 0 },
    lv: { 3: { dur: 0.3 }, 5: { cd: -0.2 }, 7: { dur: 0.4 } } },
  barrier: { name: 'Aegis Barrier', icon: 'AE', elem: 'arcane', kind: 'barrier', color: '#48cae4', dir: 'nearest', noTarget: 1,
    desc: 'Shield that reflects enemy bullets and blocks contact.',
    base: { dmg: 12, cd: 12, dur: 3, area: 80, range: 0 },
    lv: { 3: { dur: 0.35 }, 5: { area: 0.3 }, 7: { cd: -0.25 } } },
  bladestorm: { name: 'Blade Storm', icon: 'BS', elem: 'phys', kind: 'ring', color: '#e9ecef', dir: 'nearest', noTarget: 1,
    desc: 'Explodes a ring of blades outward.',
    base: { dmg: 19, cd: 6, count: 16, speed: 460, pierce: 3, range: 360, size: 6 },
    lv: { 3: { count: 8 }, 5: { pierce: 3 }, 7: { dmg: 0.5 } } },
  cloud: { name: 'Plague Cloud', icon: 'PC', elem: 'poison', kind: 'zone', color: '#9ef01a', dir: 'cluster',
    desc: 'A drifting cloud of stacking poison.',
    base: { dmg: 11, cd: 9, area: 115, dur: 5, pull: 0, range: 460 },
    lv: { 3: { dur: 0.4 }, 5: { area: 0.3 }, 7: { dmg: 0.6 } } },
  sentry: { name: 'Sentry Turret', icon: 'SN', elem: 'shock', kind: 'sentry', color: '#ffd60a', dir: 'nearest', noTarget: 1,
    desc: 'Deploys an auto-turret that uses this directive.',
    base: { dmg: 9, cd: 13, count: 1, dur: 10, rate: 0.25, range: 400 },
    lv: { 3: { dur: 0.3 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
};

const RARITIES = [
  { id: 'common',    name: 'Bronze',    color: '#cd8a4a', mult: 1,   lvls: 1, w: 60 },
  { id: 'rare',      name: 'Silver',    color: '#c9d6e3', mult: 1.5, lvls: 1, w: 27 },
  { id: 'epic',      name: 'Gold',      color: '#ffd23f', mult: 2,   lvls: 2, w: 10 },
  { id: 'legendary', name: 'Legendary', color: '#ff3df2', mult: 3,   lvls: 3, w: 3 },
];

// Passive power-ups. v = value per stack at common rarity; rarity multiplies it.
const PASSIVES = {
  might:     { name: 'Might',            icon: 'MT', max: 8, v: 0.12, fmt: v => `+${pc(v)} damage`, apply: (P, v) => { P.might += v; } },
  haste:     { name: 'Trigger Discipline', icon: 'TD', max: 8, v: 0.10, fmt: v => `+${pc(v)} fire rate`, apply: (P, v) => { P.haste += v; } },
  reload:    { name: 'Quick Hands',      icon: 'QH', max: 6, v: 0.15, fmt: v => `+${pc(v)} reload speed`, apply: (P, v) => { P.reloadSpd += v; } },
  mag:       { name: 'Extended Mags',    icon: 'EM', max: 6, v: 0.20, fmt: v => `+${pc(v)} magazine size`, apply: (P, v) => { P.magMult += v; } },
  multishot: { name: 'Multishot',        icon: 'MS', max: 3, v: 1, minRarity: 2, fmt: v => `+${Math.round(v)} projectile for all weapons`, apply: (P, v) => { P.multishot += Math.round(v); } },
  velocity:  { name: 'Velocity',         icon: 'VE', max: 5, v: 0.12, fmt: v => `+${pc(v)} projectile speed and range`, apply: (P, v) => { P.projSpeed += v; P.range += v * 0.6; } },
  area:      { name: 'Blast Radius',     icon: 'BR', max: 6, v: 0.12, fmt: v => `+${pc(v)} area of effect`, apply: (P, v) => { P.area += v; } },
  duration:  { name: 'Longevity',        icon: 'LG', max: 5, v: 0.15, fmt: v => `+${pc(v)} effect duration`, apply: (P, v) => { P.dur += v; } },
  pierce:    { name: 'Penetrator',       icon: 'PN', max: 4, v: 1, fmt: v => `+${Math.round(v)} pierce`, apply: (P, v) => { P.pierce += Math.round(v); } },
  crit:      { name: 'Deadeye',          icon: 'DE', max: 6, v: 0.05, fmt: v => `+${pc(v)} crit chance`, apply: (P, v) => { P.crit += v; } },
  critdmg:   { name: 'Executioner',      icon: 'EX', max: 6, v: 0.25, fmt: v => `+${pc(v)} crit damage`, apply: (P, v) => { P.critDmg += v; } },
  vital:     { name: 'Vital Core',       icon: 'VC', max: 8, v: 15, fmt: v => `+${Math.round(v)} max HP (and heal it)`, apply: (P, v, G) => { P.maxHp += Math.round(v); G.player.hp += Math.round(v); } },
  regen:     { name: 'Nanites',          icon: 'NA', max: 5, v: 0.3, fmt: v => `+${v.toFixed(1)} HP/sec regen`, apply: (P, v) => { P.regen += v; } },
  speed:     { name: 'Sprint Servos',    icon: 'SP', max: 5, v: 0.08, fmt: v => `+${pc(v)} move speed`, apply: (P, v) => { P.speed += v; } },
  magnet:    { name: 'Tractor Field',    icon: 'TF', max: 5, v: 0.3, fmt: v => `+${pc(v)} pickup range`, apply: (P, v) => { P.magnet += v; } },
  armour:    { name: 'Plating',          icon: 'PT', max: 6, v: 1, fmt: v => `+${Math.round(v)} armour (flat damage reduction)`, apply: (P, v) => { P.armour += Math.round(v); } },
  luck:      { name: 'Fortune',          icon: 'FO', max: 5, v: 0.15, fmt: v => `+${pc(v)} luck (rarer loot, more drops)`, apply: (P, v) => { P.luck += v; } },
  vamp:      { name: 'Vampiric Rounds',  icon: 'VR', max: 5, v: 0.08, fmt: v => `Heal ${v.toFixed(2)} HP per kill`, apply: (P, v) => { P.lifesteal += v; } },
  pyro:      { name: 'Pyromancy',        icon: 'PY', max: 5, v: 0.25, fmt: v => `+${pc(v)} fire damage and burn`, apply: (P, v) => { P.elem.fire += v; } },
  cryo:      { name: 'Cryomancy',        icon: 'CY', max: 5, v: 0.25, fmt: v => `+${pc(v)} frost damage and chill`, apply: (P, v) => { P.elem.ice += v; } },
  storm:     { name: 'Stormcaller',      icon: 'SC', max: 5, v: 0.25, fmt: v => `+${pc(v)} shock damage, +1 chain`, apply: (P, v) => { P.elem.shock += v; P.chain += 1; } },
  toxin:     { name: 'Toxicology',       icon: 'TX', max: 5, v: 0.25, fmt: v => `+${pc(v)} poison damage, +3 max stacks`, apply: (P, v) => { P.elem.poison += v; P.poisonCap += 3; } },
  arcanum:   { name: 'Arcanum',          icon: 'AR', max: 5, v: 0.25, fmt: v => `+${pc(v)} arcane damage`, apply: (P, v) => { P.elem.arcane += v; } },
  kinetic:   { name: 'Ballistics',       icon: 'BA', max: 5, v: 0.25, fmt: v => `+${pc(v)} kinetic damage`, apply: (P, v) => { P.elem.phys += v; } },
  catalyst:  { name: 'Catalyst',         icon: 'CT', max: 5, v: 0.35, fmt: v => `+${pc(v)} elemental reaction damage`, apply: (P, v) => { P.react += v; } },
  echo:      { name: 'Spell Echo',       icon: 'SE', max: 5, v: 0.10, fmt: v => `-${pc(v)} spell cooldowns`, apply: (P, v) => { P.cdr = Math.max(0.4, P.cdr - v); } },
  scholar:   { name: 'Scholar',          icon: 'SH', max: 5, v: 0.12, fmt: v => `+${pc(v)} experience gained`, apply: (P, v) => { P.xp += v; } },
  temporal:  { name: 'Temporal Loop',    icon: 'TL', max: 3, v: 1, minRarity: 1, fmt: () => `+1 max Rewind charge, +25% Chrono energy`, apply: (P, v, G) => { G.chrono.max += 1; P.chronoGain += 0.25; } },
  engineer:  { name: 'Engineer',         icon: 'EN', max: 5, v: 0.2, fmt: v => `+${pc(v)} tower damage, towers cost ${pc(v / 2)} less`, apply: (P, v) => { P.tower += v; P.towerCost = Math.max(0.4, P.towerCost - v / 2); } },
  salvage:   { name: 'Salvager',         icon: 'SV', max: 5, v: 0.25, fmt: v => `+${pc(v)} scrap from kills`, apply: (P, v) => { P.scrap += v; } },
  bulwark:   { name: 'Anchor Plating',   icon: 'AP', max: 5, v: 150, fmt: v => `+${Math.round(v)} Anchor max HP (and repair it)`, apply: (P, v, G) => { G.core.maxHp += Math.round(v); G.core.hp += Math.round(v); } },
  lastround: { name: 'Last Word',        icon: 'LW', max: 3, v: 1, fmt: v => `Last bullet of every magazine deals x${3 + Math.round(v)} damage and explodes`, apply: (P, v) => { P.lastRound += Math.round(v); } },
  tactical:  { name: 'Tactical Reload',  icon: 'TR', max: 4, v: 1, fmt: v => `Starting a reload sends out a shockwave that deletes nearby bullets (+${40 * Math.round(v)} radius)`, apply: (P, v) => { P.tactical += Math.round(v); } },
  focus:     { name: 'Focus Lock',       icon: 'FL', max: 3, v: 0.3, fmt: v => `+3% damage per second on the same target, up to +${pc(v)} more`, apply: (P, v) => { P.focus += v; } },
  overkill:  { name: 'Overkill Transfer', icon: 'OK', max: 3, v: 0.5, fmt: v => `${pc(v)} of excess kill damage jumps to the next enemy`, apply: (P, v) => { P.overkill += v; } },
  crossfire: { name: 'Crossfire Protocol', icon: 'CF', max: 3, v: 0.25, fmt: v => `Weapons sharing a target: +${pc(v)} damage. All three on different targets: +${pc(v)} fire rate`, apply: (P, v) => { P.crossfire += v; } },
  momentum:  { name: 'Momentum',         icon: 'MO', max: 4, v: 0.15, fmt: v => `Up to +${pc(v * 1.5)} damage the faster you are moving`, apply: (P, v) => { P.momentum += v; } },
  anchorlink:{ name: 'Anchor Link',      icon: 'AL', max: 3, v: 0.3, fmt: v => `Near the Anchor: +${pc(v)} fire rate. Away from it: +${pc(v)} crit chance`, apply: (P, v) => { P.anchorLink += v; } },
  future:    { name: 'Future Rounds',    icon: 'FU', max: 4, v: 0.1, fmt: v => `${pc(v)} of shots appear already next to their target`, apply: (P, v) => { P.future += v; } },
  echoinherit: { name: 'Echo Inheritance', icon: 'EI', max: 1, v: 1, minRarity: 1, fmt: () => `Paradox Echoes also cast your spells and last twice as long`, apply: (P) => { P.echoInherit = 1; } },
  evasion:   { name: 'Evasion',          icon: 'EV', max: 5, v: 0.04, fmt: v => `+${pc(v)} chance to dodge hits`, apply: (P, v) => { P.dodge = Math.min(0.5, P.dodge + v); } },
};
function pc(v) { return Math.round(v * 100) + '%'; }

// Element reactions (triggered when an element hits an enemy already carrying another status).
const REACTIONS = {
  thermal:   { name: 'THERMAL SHOCK', color: '#ff9e9e', desc: 'Fire on a chilled/frozen enemy: big burst damage' },
  steam:     { name: 'STEAM BURST',   color: '#e0fbfc', desc: 'Frost on a burning enemy: scalding area blast' },
  combust:   { name: 'COMBUSTION',    color: '#ffba08', desc: 'Fire on a poisoned enemy: poison stacks explode' },
  toxicarc:  { name: 'TOXIC ARC',     color: '#d4ff5c', desc: 'Shock on a poisoned enemy: poison spreads to neighbours' },
  supercon:  { name: 'SUPERCONDUCT',  color: '#bde0fe', desc: 'Shock on a chilled enemy: armour shredded' },
  resonance: { name: 'RESONANCE',     color: '#e0aaff', desc: 'Arcane on any status: bonus damage, mark spreads' },
  overload:  { name: 'OVERLOAD',      color: '#fff3b0', desc: 'Fire on a shocked enemy: lightning explosion' },
};

// Elemental synergy set bonuses: owning N weapons/spells of one element.
const SYNERGIES = {
  phys:   { name: 'Gunslinger',  desc: '+15% fire rate for kinetic weapons' },
  fire:   { name: 'Pyromaniac',  desc: 'Burns last longer and deal +50% damage' },
  ice:    { name: 'Permafrost',  desc: 'Freeze threshold halved, frozen take +25%' },
  shock:  { name: 'Conductor',   desc: 'Shocked enemies arc twice as often' },
  poison: { name: 'Plaguebringer', desc: 'Poison ticks twice as fast' },
  arcane: { name: 'Arcanist',    desc: 'Marks amplify damage by +50% instead of +30%' },
};

// Enemies. from = seconds before they can spawn, w = spawn weight.
const ENEMIES = {
  crawler:  { name: 'Crawler', hp: 14, speed: 64, armour: 0, r: 12, dmg: 8, xp: 1, color: '#ff4d6d', shape: 'circle', ai: 'chase', from: 0, w: 10 },
  skitter:  { name: 'Skitter', hp: 6, speed: 125, armour: 0, r: 8, dmg: 5, xp: 1, color: '#ffa94d', shape: 'tri', ai: 'chase', from: 15, w: 7 },
  spitter:  { name: 'Spitter', hp: 20, speed: 58, armour: 0, r: 13, dmg: 6, xp: 3, color: '#e056fd', shape: 'diamond', ai: 'ranged', from: 35, w: 4,
    shoot: { pattern: 'aimed', cd: 2.6, speed: 170, dmg: 6 } },
  brute:    { name: 'Brute', hp: 60, speed: 44, armour: 3, r: 20, dmg: 16, xp: 4, color: '#c77d4a', shape: 'square', ai: 'chase', from: 55, w: 4 },
  bomber:   { name: 'Bomber', hp: 16, speed: 98, armour: 0, r: 12, dmg: 18, xp: 2, color: '#ff2e2e', shape: 'spike', ai: 'bomber', from: 100, w: 3 },
  splitter: { name: 'Splitter', hp: 42, speed: 52, armour: 0, r: 17, dmg: 10, xp: 3, color: '#43e97b', shape: 'hex', ai: 'chase', from: 85, w: 3, split: 'splitling' },
  splitling:{ name: 'Splitling', hp: 12, speed: 92, armour: 0, r: 9, dmg: 5, xp: 1, color: '#7af5a8', shape: 'hex', ai: 'chase', from: 99999, w: 0 },
  wisp:     { name: 'Wisp', hp: 4, speed: 145, armour: 0, r: 6, dmg: 4, xp: 0.5, color: '#fee440', shape: 'circle', ai: 'chase', from: 95, w: 2, group: 9 },
  blinker:  { name: 'Blinker', hp: 22, speed: 72, armour: 0, r: 12, dmg: 9, xp: 3, color: '#00f5d4', shape: 'diamond', ai: 'blink', from: 105, w: 2 },
  medic:    { name: 'Mender', hp: 30, speed: 56, armour: 1, r: 13, dmg: 6, xp: 4, color: '#7bed9f', shape: 'cross', ai: 'medic', from: 120, w: 2 },
  charger:  { name: 'Ram', hp: 50, speed: 56, armour: 2, r: 16, dmg: 18, xp: 4, color: '#f15bb5', shape: 'tri', ai: 'charge', from: 130, w: 3 },
  bulwark:  { name: 'Bulwark', hp: 95, speed: 40, armour: 8, r: 20, dmg: 14, xp: 6, color: '#8da9c4', shape: 'square', ai: 'aura', from: 150, w: 2 },
  warlock:  { name: 'Warlock', hp: 45, speed: 46, armour: 1, r: 15, dmg: 8, xp: 6, color: '#9b5de5', shape: 'star', ai: 'ranged', from: 170, w: 2,
    shoot: { pattern: 'ring', count: 8, cd: 3.2, speed: 140, dmg: 9 } },
  phantom:  { name: 'Phantom', hp: 35, speed: 82, armour: 0, r: 13, dmg: 10, xp: 5, color: '#caf0f8', shape: 'circle', ai: 'phase', from: 195, w: 2 },
  summoner: { name: 'Broodmother', hp: 75, speed: 40, armour: 2, r: 18, dmg: 10, xp: 8, color: '#ff8fab', shape: 'oct', ai: 'summon', from: 210, w: 1.2 },
  spire:    { name: 'Spire', hp: 85, speed: 16, armour: 4, r: 18, dmg: 10, xp: 8, color: '#ff006e', shape: 'hex', ai: 'turret', from: 240, w: 1.5,
    shoot: { pattern: 'spiral', cd: 0.16, speed: 125, dmg: 7 } },
  lancer:   { name: 'Lancer', hp: 26, speed: 52, armour: 0, r: 13, dmg: 6, xp: 5, color: '#ff99c8', shape: 'tri', ai: 'ranged', from: 260, w: 1.5,
    shoot: { pattern: 'snipe', cd: 3.6, speed: 430, dmg: 16 } },
  juggernaut: { name: 'Juggernaut', hp: 420, speed: 34, armour: 12, r: 28, dmg: 30, xp: 20, color: '#8d99ae', shape: 'oct', ai: 'chase', from: 300, w: 0.6 },
};

const BOSSES = [
  { id: 'queen',    name: 'THE HIVE QUEEN', hp: 2600, speed: 46, armour: 2, r: 44, dmg: 25, xp: 60, color: '#ff4d6d', shape: 'star', patterns: ['spiral', 'summon', 'ring', 'aimedFan'] },
  { id: 'colossus', name: 'IRON COLOSSUS',  hp: 4200, speed: 36, armour: 10, r: 52, dmg: 35, xp: 90, color: '#adb5bd', shape: 'oct', patterns: ['ring', 'charge', 'aimedFan', 'doubleSpiral'] },
  { id: 'voideye',  name: 'THE VOID EYE',   hp: 3400, speed: 52, armour: 4, r: 46, dmg: 30, xp: 80, color: '#7b2cbf', shape: 'eye', patterns: ['doubleSpiral', 'blink', 'ring', 'flower'] },
];
const BOSS_INTERVAL = 180; // seconds

// Field power-ups.
const POWERUPS = {
  magnet: { name: 'MAGNET',  letter: 'M', color: '#4cc9f0', desc: 'All XP flies to you' },
  nuke:   { name: 'NUKE',    letter: 'N', color: '#ff595e', desc: 'Obliterates nearby enemies' },
  rage:   { name: 'OVERDRIVE', letter: 'O', color: '#ff924c', desc: 'Double fire rate, no reloads' },
  heal:   { name: 'MEDKIT',  letter: '+', color: '#8ac926', desc: 'Restore 35% HP' },
  shield: { name: 'SHIELD',  letter: 'S', color: '#48cae4', desc: 'Invulnerable for 5s' },
  freeze: { name: 'STASIS',  letter: 'F', color: '#a2d2ff', desc: 'Freeze all enemies' },
  chest:  { name: 'LOOT BOX', letter: '?', color: '#ffca3a', desc: 'Free upgrade' },
};

// ---------------------------------------------------------------- Tower defence
// The Chrono Anchor sits at the world origin. Build pads ring it; siege waves march on it from rifts.
const CORE = { hp: 900, r: 34, sanctuary: 230, arena: 1400, regen: 1.5 };
const TOWERS = {
  cannon: { name: 'Autocannon',   icon: 'AC', color: '#e8eef8', elem: 'phys',   cost: 40, dir: 'nearest',
    desc: 'Rapid kinetic rounds.', dmg: 7, rate: 0.32, range: 330 },
  tesla:  { name: 'Tesla Pylon',  icon: 'TP', color: '#ffe94a', elem: 'shock',  cost: 60, dir: 'cluster',
    desc: 'Chain lightning across 4 targets.', dmg: 9, rate: 0.9, range: 270, chain: 3 },
  cryo:   { name: 'Cryo Spire',   icon: 'CS', color: '#6fd8ff', elem: 'ice',    cost: 50, dir: null,
    desc: 'Freezing pulse around the tower.', dmg: 4, rate: 1.1, range: 160 },
  mortar: { name: 'Mortar Nest',  icon: 'MN', color: '#ff6b35', elem: 'fire',   cost: 80, dir: 'cluster',
    desc: 'Long-range explosive shells.', dmg: 26, rate: 2.2, range: 520, area: 85 },
  stasis: { name: 'Stasis Clock', icon: 'SC', color: '#b8c0ff', elem: 'arcane', cost: 70, dir: null,
    desc: 'Time runs at 35% in its field: enemies and bullets crawl.', dmg: 0, rate: 0, range: 190 },
  beacon: { name: 'Repair Beacon', icon: 'RB', color: '#80ffdb', elem: 'poison', cost: 65, dir: null,
    desc: 'Repairs the Anchor and heals you nearby.', dmg: 6, rate: 0, range: 170 },
};
const TOWER_MAX_LVL = 3;
const SIEGE_FIRST = 55, SIEGE_INTERVAL = 80, SIEGE_WARN = 4;
const SIEGE_POOL = ['crawler', 'skitter', 'brute', 'splitter', 'bulwark', 'charger', 'wisp', 'juggernaut'];

// ---------------------------------------------------------------- Chrono (time travel)
const CHRONO = { window: 4, snapEvery: 0.25, animDur: 1.1, energyPerCharge: 260, startCharges: 1, maxCharges: 2 };

// ---------------------------------------------------------------- Weapon mods (slot into one weapon, 2 per weapon)
const MOD_SLOTS = 2;
const MODS = {
  split:     { name: 'Split on Kill',   icon: 'SK', desc: 'Kills burst into 3 shrapnel shards (40% damage).' },
  ricochet:  { name: 'Ricochet Rounds', icon: 'RR', desc: '+2 bounces between enemies.', kinds: ['gun', 'siphon', 'mimic'] },
  elemental: { name: 'Element Swap',    icon: 'EL', desc: 'Converts this weapon to a new element.' },
  homing:    { name: 'Homing Guidance', icon: 'HG', desc: 'Projectiles steer towards targets.', kinds: ['gun', 'siphon', 'mimic'] },
};

// ---------------------------------------------------------------- Cursed loot cards
const CURSES = [
  { id: 'glass', name: 'Glass Cannon Deluxe', boon: 'x1.8 damage for everything', bane: 'Max HP halved',
    apply: (P, G) => { P.might *= 1.8; P.maxHp = Math.max(30, Math.round(P.maxHp / 2)); G.player.hp = Math.min(G.player.hp, P.maxHp); } },
  { id: 'speed', name: "Speedrunner's Regret", boon: '+50% fire rate', bane: 'Enemy bullets 20% faster', apply: P => { P.haste += 0.5; P.bulletSpeed *= 1.2; } },
  { id: 'hoard', name: "Hoarder's Bargain", boon: 'Double scrap from everything', bane: 'Towers cost 50% more', apply: P => { P.scrap *= 2; P.towerCost *= 1.5; } },
  { id: 'crowd', name: 'Crowd Pleaser', boon: '+50% XP and viewers', bane: '30% more enemies', apply: P => { P.xp += 0.5; P.viewers *= 1.5; P.spawnMult *= 1.3; } },
  { id: 'paradox', name: 'Paradox Addict', boon: '+2 max Rewind charges, all refilled now', bane: 'All healing halved', apply: (P, G) => { G.chrono.max += 2; G.chrono.charges = G.chrono.max; P.healMult *= 0.5; } },
  { id: 'naked', name: 'Clothing Optional', boon: '+25% move speed, +20% dodge', bane: 'Armour is zero. Forever.', apply: P => { P.speed += 0.25; P.dodge = Math.min(0.6, P.dodge + 0.2); P.noArmour = true; } },
];

// ---------------------------------------------------------------- The Show: announcer, achievements, viewers, sponsors
// Original comedy writing for Storm Directive's sardonic game-show host, "the System".
const GACHA_TIERS = [
  { name: 'BRONZE MAG', mult: 0.7, color: '#cd8a4a', w: 55 },
  { name: 'SILVER MAG', mult: 1.1, color: '#c9d6e3', w: 28 },
  { name: 'GOLD MAG', mult: 1.8, color: '#ffd23f', w: 13 },
  { name: 'LEGENDARY MAG', mult: 3, color: '#ff3df2', w: 4 },
];
const BOSS_TITLES = { queen: 'Tenured Mother of Thousands', colossus: 'Regional Manager of Crushing', voideye: 'Unblinking Critic of Your Life Choices' };
const SPONSORS = [
  "Grundle's Discount Ordnance", "Madame Vex's Totally Legal Potions", 'The Committee for Unnecessary Explosions',
  "Big Barry's Scrap and Salvage", 'Glorp Cola: It Glows For A Reason', 'The Ancient Order of Slightly Sticky Relics',
  "Dr Fizzwick's Regrettable Medicines", 'Hovercrab Insurance: We Probably Cover That',
];
const SYSTEM_LINES = {
  start: [
    'Welcome, Contestant. Please keep your limbs inside the ship at all times. Or don\'t. The ratings are better if you don\'t.',
    'Good news: you have been selected for a fabulous new game show. Bad news: it is this one.',
    'Reminder: the ship flies itself. Your job is to make bad decisions in the menus.',
  ],
  level: [
    'Level up! Your body is changing. That is normal. The glowing is also normal.',
    'Another level. At this rate you might survive until the adverts.',
    'Level up. Please enjoy this complimentary box of violence.',
    'Congratulations on your promotion from "snack" to "slightly harder snack".',
  ],
  boss: [
    'It has read your file and is unimpressed.',
    'It has been told you insulted its mother. You did not. We did. On your behalf.',
    'Please try to die slowly. The viewers paid for the full episode.',
  ],
  siege: [
    'Rifts are opening. The monsters would like a word with your crystal.',
    'Siege incoming. Please do not let them lick the expensive rock.',
  ],
  lowhp: [
    'Your health is low. Have you tried not getting hit?',
    'Vital signs: concerning. Viewer engagement: excellent.',
    'The medic has been notified. The medic has declined.',
  ],
  rewind: [
    'Time has been rewound. The paperwork on this is going to be horrendous.',
    'Rewind successful. Your future self is now an unpaid intern.',
    'Causality has filed a formal complaint. Noted. Ignored.',
  ],
  fusion: ['Fusion complete. It violates at least four treaties.', 'Two weapons became one. The other one is in a better place now.'],
  cursed: ['You took the cursed card. We are not angry. We are just disappointed. And delighted.', 'Bold. Stupid, but bold.'],
  tower: ['Tower built. Anchor property values have increased by 3%.', 'Construction complete. No permits were filed. None will be.'],
  anchorLow: ['The Anchor is cracking. That is the one thing you were asked to protect.', 'Anchor integrity critical. Please stop looking at the loot and look at the rock.'],
  surge: ['Storm Surge! Everything hits harder now. Please remain calm and panic.'],
  idle: [
    'The audience is getting bored. Kill something interesting.',
    'Fun fact: most contestants die within the next minute. Just saying.',
    'A reminder that screaming does not affect gameplay, but we do record it.',
    'Our legal team would like to remind you that none of this is legally binding. Except the dying.',
    'Viewer poll: 61% think you will die to a Skitter. Prove them right.',
    'You are doing great! This message is automated and applies to all contestants equally.',
  ],
  death: [
    'Contestant eliminated. The audience has already forgotten your name.',
    'You have died. Your loot will be redistributed to someone more competent.',
    'And that is the show! Well, your show. The show continues without you.',
    'Cause of death: optimism.',
  ],
  gacha: ['Legendary magazine! The house always wins. Except, apparently, now.'],
  mimic: ['Pattern copied. The original owner is dead and cannot sue. Probably.'],
  grudge: ['Grudge settled. Therapy was cheaper, but this was faster.'],
};
const NO_REWARD = [
  'Reward: a sense of accomplishment. It is non-refundable.',
  'Reward: nothing. We are not made of money.',
  'Reward: our respect. It has no resale value.',
  'Reward: exposure. You know how it is.',
];
const CARD_QUIPS = [
  'The System recommends this one. The System is often wrong.',
  'Viewers voted this "most likely to end in tears".',
  'A previous contestant picked this. We don\'t talk about them.',
  'Sponsored content. Probably.',
  'This one comes with a free trial of hope.',
  'Our focus group loved it. The focus group has since dissolved.',
];
const ACHIEVEMENTS = {
  firstblood: { name: "Baby's First Homicide", desc: 'Killed a monster. It had a family. Probably.', reward: 'none' },
  kills100:   { name: 'Pest Control', desc: '100 kills. The exterminators\' union has filed a complaint.', reward: 'reroll' },
  kills1000:  { name: 'Statistically Significant', desc: '1,000 kills. You are now a demographic.', reward: 'box' },
  kills5000:  { name: 'Extinction Event', desc: '5,000 kills. Several species have asked you to stop.', reward: 'bossbox' },
  firstloot:  { name: 'Unboxing Influencer', desc: 'Opened your first loot box. Please like and subscribe.', reward: 'none' },
  fusion:     { name: 'Frankenweapon', desc: 'Fused two weapons. It is alive. It is also on fire.', reward: 'reroll' },
  rewind:     { name: 'Undo Button Enthusiast', desc: 'Rewound time. Causality has been notified.', reward: 'none' },
  autorewind: { name: 'Not Today, Death', desc: 'Died, then un-died. Our lawyers are looking into it.', reward: 'heal' },
  boss:       { name: 'Middle Management Removed', desc: 'Killed a boss. Someone will be promoted to replace it.', reward: 'none' },
  tower:      { name: 'Property Developer', desc: 'Built a tower. Planning permission was not sought.', reward: 'scrap' },
  sell:       { name: 'Flipper', desc: 'Sold a tower. The housing market is in shambles.', reward: 'none' },
  anchorhit:  { name: 'That Was Load-Bearing', desc: 'Let something hit the Anchor. It was the one job.', reward: 'none' },
  reactions:  { name: 'Mad Scientist', desc: 'Triggered 50 elemental reactions. Safety goggles were optional.', reward: 'reroll' },
  friendly:   { name: 'Let Them Fight', desc: 'A Bomber killed another monster. Teamwork!', reward: 'none' },
  cursed:     { name: 'Bad Decision Maker', desc: 'Took a cursed card. We knew you would.', reward: 'none' },
  modded:     { name: 'Aftermarket Parts', desc: 'Installed a weapon mod. The warranty is now fully void.', reward: 'none' },
  grudge:     { name: 'Petty', desc: 'Killed the thing that hurt you with the Grudge Rifle. Worth it.', reward: 'none' },
  broke:      { name: 'Financially Ruined', desc: 'Ran the Scrap Cannon dry. Please consult a debt counsellor.', reward: 'scrap' },
  gachagold:  { name: 'Gambling Problem', desc: 'Rolled a Legendary magazine. Do not tell your mother.', reward: 'none' },
  parasite:   { name: 'Landlord of Flesh', desc: 'A corpse became your turret. Rent is due Tuesday.', reward: 'none' },
  mimic:      { name: 'Identity Theft', desc: 'Stole a monster\'s attack pattern. It will be pressing charges.', reward: 'none' },
  overkill:   { name: 'Excessive Force', desc: 'Dealt 1,000 overkill damage in one hit. The review board is concerned.', reward: 'none' },
  lastword:   { name: 'The Last Word', desc: 'Killed something with the final round of a magazine. Dramatic.', reward: 'none' },
  spoilers:   { name: 'Spoilers', desc: 'Killed something before the shell had even been fired.', reward: 'none' },
  tethered:   { name: 'Forced Proximity', desc: 'Slammed two tethered monsters together. They did not consent.', reward: 'none' },
  siphoned:   { name: 'Return to Sender', desc: 'Absorbed 200 enemy bullets. The postal service is in awe.', reward: 'reroll' },
  echokill:   { name: 'Time Paradox Murder', desc: 'Your future self got a kill. Who gets the XP? You do. Don\'t ask.', reward: 'none' },
  survive5:   { name: 'Still Here?', desc: 'Survived 5 minutes. The producers are surprised.', reward: 'box' },
  survive10:  { name: 'Contractually Obligated', desc: 'Survived 10 minutes. We have to keep filming now.', reward: 'box' },
  surge:      { name: 'Ratings Spike', desc: 'Reached the Storm Surge. The audience is thrilled you will die soon.', reward: 'none' },
  viewers1m:  { name: 'Celebrity', desc: 'One million viewers. Your agent has several questions.', reward: 'box' },
  lowhp:      { name: 'Flesh Wound', desc: 'Survived a hit with under 5% HP. The medic has fainted.', reward: 'heal' },
  sponsor:    { name: 'Sold Out', desc: 'Accepted a sponsor gift. Integrity was never on the table.', reward: 'none' },
};
const VIEWER_MILESTONES = [10e3, 50e3, 100e3, 250e3, 500e3, 1e6, 2.5e6, 5e6, 1e7, 2.5e7, 5e7];
