'use strict';
// Spawn Prawn - game data: elements, weapons, spells, merges, passives, enemies, bosses, directives.

const ELEMENTS = {
  phys:   { name: 'Kinetic', color: '#e8eef8' },
  fire:   { name: 'Fire',    color: '#ff7a2f' },
  ice:    { name: 'Frost',   color: '#6fd8ff' },
  shock:  { name: 'Shock',   color: '#ffe94a' },
  poison: { name: 'Toxic',   color: '#8dff4a' },
  arcane: { name: 'Arcane',  color: '#c77dff' },
};

// Targeting directives. Each weapon/spell runs one of these.
const DIRECTIVES = [
  { id: 'nearest',   name: 'NEAREST',        short: 'NEAR',   desc: 'Whatever is closest. Safe, boring, effective.' },
  { id: 'strongest', name: 'STRONGEST',      short: 'STRG',   desc: 'Biggest max health first. Tank busting.' },
  { id: 'weakest',   name: 'WEAKEST',        short: 'WEAK',   desc: 'Smallest max health first. Clears fodder.' },
  { id: 'lowhp',     name: 'LOWEST HEALTH',  short: 'LOW HP', desc: 'Finish off the wounded. Great for kills.' },
  { id: 'highhp',    name: 'HIGHEST HEALTH', short: 'HI HP',  desc: 'Whoever has the most health left right now.' },
  { id: 'armour',    name: 'HIGHEST ARMOUR', short: 'ARMR',   desc: 'Most armour first. Pair with shred.' },
  { id: 'fastest',   name: 'FASTEST',        short: 'FAST',   desc: 'Chargers and skitters before they reach you.' },
  { id: 'furthest',  name: 'FURTHEST',       short: 'FAR',    desc: 'Snipe the back line.' },
  { id: 'cluster',   name: 'DENSEST CLUSTER', short: 'CLSTR', desc: 'The middle of the crowd. Best for splash.' },
  { id: 'elite',     name: 'ELITES & BOSSES', short: 'ELITE', desc: 'Bosses, then elites, then nearest.' },
  { id: 'shooters',  name: 'SHOOTERS FIRST', short: 'SHOOT',  desc: 'Ranged enemies, healers and summoners first.' },
  { id: 'random',    name: 'RANDOM',         short: 'RAND',   desc: 'Chaos. The audience loves it.' },
  { id: 'revenge',   name: 'REVENGE',        short: 'GRUDGE', desc: 'Whatever hurt you last. Otherwise nearest.' },
];

// Movement (autorun) directives.
const MOVE_DIRECTIVES = [
  { id: 'kite',    name: 'KITE',    desc: 'Keep distance from threats, dodge bullets' },
  { id: 'collect', name: 'COLLECT', desc: 'Hoover up XP and power-ups' },
  { id: 'orbit',   name: 'ORBIT',   desc: 'Circle around the horde' },
  { id: 'hunt',    name: 'HUNT',    desc: 'Close in on the primary target' },
  { id: 'hold',    name: 'HOLD',    desc: 'Stand ground, only dodge bullets' },
  { id: 'defend',  name: 'NEST',    desc: 'Hover in the egg\'s warm glow, which slowly heals you' },
];

// Level bonus keys: count, pierce, chain, bounce (additive); dmg, area, dur (additive %); cd (negative = faster).
const WEAPONS = {
  blaster: { name: 'Spitball', icon: 'BL', elem: 'phys', kind: 'gun', color: '#e8f0ff', dir: 'nearest',
    desc: 'Reliable, accurate single shots. Mildly unhygienic.',
    base: { dmg: 10, cd: 0.3, mag: 12, reload: 1.1, count: 1, spread: 0.04, speed: 640, pierce: 0, range: 430, size: 4 },
    lv: { 3: { pierce: 1 }, 5: { count: 1 }, 7: { dmg: 0.3 } } },
  smg: { name: 'Sneeze Gun', icon: 'SM', elem: 'phys', kind: 'gun', color: '#cfd8ff', dir: 'nearest',
    desc: 'Sprays a hail of light droplets. Big magazine, long recovery. Bless you.',
    base: { dmg: 4.5, cd: 0.075, mag: 36, reload: 1.7, count: 1, spread: 0.2, speed: 580, pierce: 0, range: 370, size: 3 },
    lv: { 3: { cd: -0.15 }, 5: { pierce: 1 }, 7: { count: 1 } } },
  shotgun: { name: 'Hiccup Scattergun', icon: 'SG', elem: 'phys', kind: 'gun', color: '#ffd6a5', dir: 'nearest',
    desc: 'Close-range burst with knockback. Comes out whether you want it to or not.',
    base: { dmg: 8, cd: 0.75, mag: 4, reload: 1.6, count: 6, spread: 0.55, speed: 540, pierce: 0, range: 270, size: 3.5, knock: 70 },
    lv: { 3: { count: 2 }, 5: { pierce: 1 }, 7: { count: 3 } } },
  railgun: { name: 'Kidney Stone Railgun', icon: 'RG', elem: 'phys', kind: 'gun', color: '#9ef0ff', dir: 'armour', style: 'rail',
    desc: 'A hypersonic calcified slug. Pierces everything, shreds armour, hurts everyone involved.',
    base: { dmg: 42, cd: 1.3, mag: 3, reload: 2.2, count: 1, spread: 0.05, speed: 1700, pierce: 99, range: 720, size: 3, shred: 3 },
    lv: { 3: { shred: 2 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  rocket: { name: 'Bottle Rockets', icon: 'RK', elem: 'fire', kind: 'gun', color: '#ffb347', dir: 'cluster', style: 'rocket',
    desc: 'Explosive baby bottles that set the blast zone alight. Test the temperature first.',
    base: { dmg: 24, cd: 0.55, mag: 2, reload: 2.4, count: 1, spread: 0.1, speed: 400, pierce: 0, range: 500, size: 5, explode: 62 },
    lv: { 3: { area: 0.25 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  flamer: { name: 'Heartburn', icon: 'FL', elem: 'fire', kind: 'gun', color: '#ff7a2f', dir: 'nearest', style: 'flame',
    desc: 'Short-range cone of fire. Every lick burns. Antacids not included.',
    base: { dmg: 3.2, cd: 0.05, mag: 50, reload: 2.1, count: 2, spread: 0.45, speed: 310, pierce: 99, range: 200, size: 7 },
    lv: { 3: { area: 0.3 }, 5: { dmg: 0.3 }, 7: { count: 1 } } },
  frost: { name: 'Cold Feet', icon: 'FR', elem: 'ice', kind: 'gun', color: '#6fd8ff', dir: 'fastest', style: 'shard',
    desc: 'Piercing ice shards that chill and freeze. Commitment issues, weaponised.',
    base: { dmg: 15, cd: 0.6, mag: 5, reload: 1.5, count: 1, spread: 0.08, speed: 540, pierce: 3, range: 460, size: 5 },
    lv: { 3: { count: 1 }, 5: { pierce: 3 }, 7: { count: 2 } } },
  tesla: { name: 'Static Cling', icon: 'TC', elem: 'shock', kind: 'chain', color: '#ffe94a', dir: 'cluster',
    desc: 'Instant lightning that arcs between enemies, like a nylon onesie in winter.',
    base: { dmg: 13, cd: 0.7, mag: 6, reload: 1.8, count: 1, chain: 3, range: 330, jump: 140 },
    lv: { 3: { chain: 2 }, 5: { count: 1 }, 7: { chain: 3 } } },
  venom: { name: 'Morning Sickness', icon: 'VS', elem: 'poison', kind: 'lob', color: '#8dff4a', dir: 'cluster',
    desc: 'Lobs acid globs that leave toxic puddles. Worse before noon.',
    base: { dmg: 9, cd: 0.9, mag: 4, reload: 1.8, count: 1, spread: 40, range: 390, area: 55, dur: 3, flight: 0.6 },
    lv: { 3: { dur: 0.5 }, 5: { count: 1 }, 7: { area: 0.4 } } },
  glaive: { name: 'Yo-Yo Diet', icon: 'GL', elem: 'phys', kind: 'gun', color: '#f1f1f1', dir: 'furthest', style: 'glaive',
    desc: 'A spinning blade that flies out and always comes back. Like the weight.',
    base: { dmg: 15, cd: 1.0, mag: 2, reload: 1.3, count: 1, spread: 0.3, speed: 430, pierce: 99, range: 330, size: 10, boomerang: 1 },
    lv: { 3: { count: 1 }, 5: { dmg: 0.3 }, 7: { count: 1 } } },
  orbit: { name: 'Doting Relatives', icon: 'OB', elem: 'arcane', kind: 'orbit', color: '#c77dff', dir: 'nearest',
    desc: 'Blades circle you, fussing. They need a sit-down every so often.',
    base: { dmg: 16, count: 3, dur: 4.5, reload: 2.2, radius: 72, spin: 3.6, size: 10, range: 100 },
    lv: { 3: { count: 1 }, 5: { area: 0.3 }, 7: { count: 2 } } },
  prism: { name: 'Ultrasound Beam', icon: 'PB', elem: 'arcane', kind: 'beam', color: '#e0aaff', dir: 'strongest',
    desc: 'A channelled beam that burns through a line of foes. Would you like a printout?',
    base: { dmg: 32, cd: 1.7, mag: 3, reload: 2.2, count: 1, dur: 1.2, range: 390, size: 6 },
    lv: { 3: { dur: 0.35 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  mines: { name: 'Nappy Mines', icon: 'ML', elem: 'fire', kind: 'mine', color: '#ff9f1c', dir: 'nearest',
    desc: 'Drops proximity mines in your wake. Nobody wants to change them.',
    base: { dmg: 32, cd: 0.7, mag: 5, reload: 2.4, count: 1, explode: 72, life: 14, range: 600 },
    lv: { 3: { count: 1 }, 5: { area: 0.3 }, 7: { dmg: 0.5 } } },
  seeker: { name: 'Seeker Siblings', icon: 'SS', elem: 'arcane', kind: 'gun', color: '#d0a3ff', dir: 'weakest', style: 'sperm',
    desc: 'Tiny homing siblings who swim for you and never miss. Family is complicated.',
    base: { dmg: 9, cd: 0.45, mag: 6, reload: 2.0, count: 2, spread: 1.2, speed: 320, pierce: 0, range: 500, size: 4, homing: 5 },
    lv: { 3: { count: 1 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  gatling: { name: 'Contraction Gatling', icon: 'GT', elem: 'phys', kind: 'gun', color: '#ffe8a3', dir: 'nearest', spinup: 1,
    desc: 'Spins up faster and faster and faster. Breathe through it.',
    base: { dmg: 5.5, cd: 0.14, mag: 120, reload: 3.2, count: 1, spread: 0.13, speed: 720, pierce: 0, range: 450, size: 3 },
    lv: { 3: { pierce: 1 }, 5: { count: 1 }, 7: { dmg: 0.3 } } },
  drone: { name: 'Helicopter Parent', icon: 'DR', elem: 'shock', kind: 'gun', color: '#fff275', dir: 'lowhp', drones: 1,
    desc: 'Hovers beside you and fires shock bolts at anyone who looks at you funny.',
    base: { dmg: 8, cd: 0.45, mag: 10, reload: 1.5, count: 1, spread: 0.05, speed: 620, pierce: 0, range: 420, size: 3.5 },
    lv: { 3: { count: 1 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  ricochet: { name: 'Pass the Parcel', icon: 'RD', elem: 'phys', kind: 'gun', color: '#a0c4ff', dir: 'nearest', style: 'disc',
    desc: 'Discs bounce from enemy to enemy. Nobody wants to be holding one when the music stops.',
    base: { dmg: 13, cd: 0.8, mag: 3, reload: 1.5, count: 1, spread: 0.1, speed: 500, pierce: 0, range: 420, size: 6, bounce: 3 },
    lv: { 3: { bounce: 2 }, 5: { count: 1 }, 7: { bounce: 3 } } },
  mortar: { name: 'Bedpan Mortar', icon: 'MR', elem: 'fire', kind: 'lob', color: '#ff6b35', dir: 'cluster',
    desc: 'Slow, heavy shells with a huge blast. Contents best not discussed.',
    base: { dmg: 42, cd: 1.6, mag: 2, reload: 2.5, count: 1, spread: 30, range: 540, area: 82, flight: 1.0, explode: 1 },
    lv: { 3: { area: 0.25 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  arbalest: { name: 'Tongue Depressor Crossbow', icon: 'AB', elem: 'phys', kind: 'gun', color: '#d4a373', dir: 'strongest', style: 'bolt',
    desc: 'Heavy bolts: massive knockback, light armour shred. Say "ahh".',
    base: { dmg: 24, cd: 0.9, mag: 4, reload: 1.6, count: 1, spread: 0.05, speed: 820, pierce: 2, range: 540, size: 4, knock: 220, shred: 1 },
    lv: { 3: { pierce: 2 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  void: { name: 'Toddler Gravity', icon: 'VO', elem: 'arcane', kind: 'gun', color: '#7b2cbf', dir: 'cluster', style: 'void',
    desc: 'A slow orb that drags everything into its mouth. Everything.',
    base: { dmg: 7, cd: 1.8, mag: 2, reload: 2.5, count: 1, spread: 0.2, speed: 115, pierce: 99, range: 400, size: 15, aura: 70, pull: 90 },
    lv: { 3: { area: 0.3 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  needler: { name: 'Booster Jab', icon: 'ND', elem: 'poison', kind: 'gun', color: '#b8f35a', dir: 'highhp', style: 'needle',
    desc: 'Rapid toxic needles. Poison stacks up. Side effects may include winning.',
    base: { dmg: 3.5, cd: 0.1, mag: 30, reload: 1.6, count: 1, spread: 0.1, speed: 680, pierce: 0, range: 410, size: 2.5 },
    lv: { 3: { count: 1 }, 5: { pierce: 1 }, 7: { cd: -0.2 } } },
  hailstorm: { name: 'Frozen Peas', icon: 'HS', elem: 'ice', kind: 'lob', color: '#a2d2ff', dir: 'cluster',
    desc: 'Rains frozen peas around the target. Also good for swelling.',
    base: { dmg: 11, cd: 1.4, mag: 2, reload: 2.0, count: 5, spread: 90, range: 460, area: 36, flight: 0.7, explode: 1 },
    lv: { 3: { count: 2 }, 5: { area: 0.3 }, 7: { count: 3 } } },

  paradox: { name: 'Deja Vu Rifle', icon: 'PX', elem: 'arcane', kind: 'gun', color: '#8dffc0', dir: 'strongest', style: 'bolt',
    desc: 'Every hit repeats itself 1 second later, from the future. Every hit repeats itself 1 second later...',
    base: { dmg: 16, cd: 0.55, mag: 6, reload: 1.6, count: 1, spread: 0.04, speed: 760, pierce: 1, range: 480, size: 4, echoHit: 1 },
    lv: { 3: { pierce: 1 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },

  // ---- Merged weapons (not in the random pool; created by fusing two maxed-enough weapons) ----
  steam: { name: 'Hot Flush Cold Sweat', icon: 'ST', elem: 'fire', elem2: 'ice', kind: 'gun', color: '#ffc6ff', dir: 'nearest', style: 'flame', merged: 1,
    desc: 'A scalding fire-and-frost cone. Triggers reactions constantly. Menopause, but tactical.',
    base: { dmg: 8, cd: 0.055, mag: 70, reload: 1.9, count: 3, spread: 0.5, speed: 380, pierce: 99, range: 250, size: 9 },
    lv: { 5: { area: 0.3 }, 7: { count: 1 } } },
  thunderbuck: { name: 'Static Hiccups', icon: 'TB', elem: 'shock', kind: 'gun', color: '#fff3b0', dir: 'nearest', merged: 1,
    desc: 'Each pellet detonates into chain lightning. Try holding your breath.',
    base: { dmg: 11, cd: 0.7, mag: 5, reload: 1.4, count: 8, spread: 0.6, speed: 580, pierce: 0, range: 310, size: 4, chainHit: 2, knock: 60 },
    lv: { 5: { count: 2 }, 7: { dmg: 0.3 } } },
  annihilator: { name: 'Full-Body Scan', icon: 'AN', elem: 'arcane', kind: 'beam', color: '#f72585', dir: 'strongest', merged: 1,
    desc: 'A colossal armour-shredding beam across the whole screen. Please remain very still.',
    base: { dmg: 130, cd: 2.4, mag: 2, reload: 2.5, count: 1, dur: 1.5, range: 820, size: 14, shred: 5 },
    lv: { 5: { dur: 0.4 }, 7: { count: 1 } } },
  hydra: { name: 'Sibling Rivalry', icon: 'HB', elem: 'fire', kind: 'gun', color: '#ff9e00', dir: 'elite', style: 'rocket', merged: 1,
    desc: 'Volleys of homing explosive rockets that fight over who gets there first.',
    base: { dmg: 22, cd: 0.5, mag: 4, reload: 2.2, count: 4, spread: 1.6, speed: 350, pierce: 0, range: 540, size: 5, homing: 6, explode: 58 },
    lv: { 5: { count: 2 }, 7: { area: 0.3 } } },
  cyclone: { name: 'Tantrum Cyclone', icon: 'CG', elem: 'phys', kind: 'orbit', color: '#ffffff', dir: 'nearest', merged: 1,
    desc: 'Six blades pulse outward and back in a screaming storm. It is about the blue cup.',
    base: { dmg: 30, count: 6, dur: 6, reload: 1.4, radius: 70, spin: 4.2, size: 12, range: 170, pulse: 1 },
    lv: { 5: { count: 2 }, 7: { dmg: 0.4 } } },
  pinball: { name: 'Bouncy Castle Magnum', icon: 'PM', elem: 'phys', kind: 'gun', color: '#caffbf', dir: 'nearest', style: 'disc', merged: 1,
    desc: 'Magnum rounds that ricochet 6 times and crit often. Shoes off.',
    base: { dmg: 22, cd: 0.35, mag: 8, reload: 1.2, count: 1, spread: 0.05, speed: 720, pierce: 0, range: 470, size: 5, bounce: 6, critBonus: 0.2 },
    lv: { 5: { bounce: 3 }, 7: { count: 1 } } },
  plague: { name: 'Nappy Bomb', icon: 'PL', elem: 'poison', kind: 'lob', color: '#70e000', dir: 'cluster', merged: 1,
    desc: 'Toxic shells: a huge blast plus a lingering pool. Nobody is volunteering.',
    base: { dmg: 46, cd: 1.4, mag: 3, reload: 2.2, count: 1, spread: 40, range: 540, area: 96, dur: 5, flight: 0.9, explode: 1 },
    lv: { 5: { count: 1 }, 7: { area: 0.3 } } },
  singularity: { name: 'Sleep Regression Mines', icon: 'SI', elem: 'arcane', kind: 'mine', color: '#9d4edd', dir: 'nearest', merged: 1,
    desc: 'Mines open a black hole that swallows everything, then detonate. Like 4am.',
    base: { dmg: 55, cd: 0.8, mag: 4, reload: 2.2, count: 1, explode: 95, life: 16, range: 600, singularity: 1 },
    lv: { 5: { count: 1 }, 7: { dmg: 0.5 } } },
  hive: { name: 'Grandparent Hive', icon: 'DH', elem: 'shock', kind: 'gun', color: '#ffee32', dir: 'lowhp', drones: 1, merged: 1,
    desc: 'Four drones with SMG fire rates. They insist on helping.',
    base: { dmg: 6.5, cd: 0.12, mag: 40, reload: 1.8, count: 4, spread: 0.1, speed: 640, pierce: 0, range: 440, size: 3 },
    lv: { 5: { count: 2 }, 7: { dmg: 0.4 } } },
  siege: { name: 'Forceps Repeater', icon: 'SR', elem: 'phys', kind: 'gun', color: '#e9c46a', dir: 'armour', style: 'bolt', spinup: 1, merged: 1,
    desc: 'Automatic heavy bolts. Pierce, shred, knockback. Gentle it is not.',
    base: { dmg: 17, cd: 0.15, mag: 60, reload: 2.4, count: 1, spread: 0.08, speed: 860, pierce: 4, range: 560, size: 4, knock: 140, shred: 2 },
    lv: { 5: { pierce: 3 }, 7: { count: 1 } } },
  zero: { name: 'Egg Freezing Service', icon: 'AZ', elem: 'ice', kind: 'lob', color: '#caf0f8', dir: 'cluster', merged: 1,
    desc: 'Ice meteors that flash-freeze everything they hit. Very forward-planning.',
    base: { dmg: 18, cd: 1.3, mag: 3, reload: 1.8, count: 8, spread: 110, range: 500, area: 48, flight: 0.7, explode: 1, freezeHit: 1 },
    lv: { 5: { count: 3 }, 7: { dmg: 0.4 } } },
  neuro: { name: 'Nervous Breakdown', icon: 'NA', elem: 'poison', elem2: 'shock', kind: 'chain', color: '#d9ed92', dir: 'cluster', merged: 1,
    desc: 'Toxic lightning. Every arc spreads plague. It has been a long week.',
    base: { dmg: 9, cd: 0.25, mag: 12, reload: 1.6, count: 1, chain: 6, range: 360, jump: 150 },
    lv: { 5: { chain: 3 }, 7: { count: 1 } } },

  // ---- Show-season weapons
  siphon: { name: 'Placental Siphon', icon: 'BU', elem: 'arcane', kind: 'siphon', color: '#ff3df2', dir: 'nearest',
    desc: 'Eats enemy bullets that come near you and spits them back. No reloads. No ammo either, until the screen is full of bullets.',
    base: { dmg: 18, cd: 0.08, mag: 40, area: 90, speed: 640, range: 460, size: 4.5, pierce: 0, spread: 0.08, count: 1 },
    lv: { 3: { count: 1 }, 5: { pierce: 1 }, 7: { dmg: 0.4 } } },
  committee: { name: 'Birth Plan Committee', icon: 'CC', elem: 'phys', kind: 'gun', committee: 1, color: '#ffd6a5', dir: 'strongest',
    desc: 'Three barrels, three directives, zero consensus. Nobody follows the birth plan. Set each barrel in the Armoury.',
    base: { dmg: 9, cd: 0.45, mag: 9, reload: 1.6, count: 1, spread: 0.05, speed: 640, pierce: 0, range: 450, size: 4 },
    lv: { 3: { pierce: 1 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  grudge: { name: 'Family Grudge', icon: 'GR', elem: 'phys', kind: 'gun', grudge: 1, color: '#ff4d6d', dir: 'revenge', style: 'bolt',
    desc: 'Remembers whatever last hurt you. Hunts it across the whole map. Triple damage to it. Very healthy.',
    base: { dmg: 20, cd: 0.6, mag: 5, reload: 1.5, count: 1, spread: 0.02, speed: 900, pierce: 0, range: 480, size: 4, homing: 3 },
    lv: { 3: { pierce: 1 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  wake: { name: 'Slipstream Scalpel', icon: 'WB', elem: 'phys', kind: 'wake', color: '#e0fbfc', dir: 'nearest', noTarget: 1,
    desc: 'Your flight path becomes a blade. Keep moving, or it is just very expensive litter.',
    base: { dmg: 22, dur: 2.2, area: 22, range: 0 },
    lv: { 3: { area: 0.3 }, 5: { dur: 0.5 }, 7: { dmg: 0.5 } } },
  scrapcannon: { name: 'Child Benefit Cannon', icon: 'SK', elem: 'phys', kind: 'gun', scrapAmmo: 1, color: '#ffb400', dir: 'strongest', style: 'scrap',
    desc: 'Fires your savings. 1 scrap per shot, enormous bang. Financial advisers weep.',
    base: { dmg: 55, cd: 0.8, mag: 99, reload: 0.5, count: 1, spread: 0.1, speed: 520, pierce: 0, range: 480, size: 7, explode: 55, knock: 120 },
    lv: { 3: { area: 0.25 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  mimic: { name: 'Copycat Twin', icon: 'MI', elem: 'arcane', kind: 'mimic', color: '#f15bb5', dir: 'nearest',
    desc: 'Copies the attack pattern of the last shooter you killed. It is not plagiarism if you win.',
    base: { dmg: 10, cd: 0.9, mag: 6, reload: 1.8, count: 1, speed: 330, range: 430, size: 5, pierce: 1 },
    lv: { 3: { dmg: 0.3 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  parasite: { name: 'Tapeworm Seeder', icon: 'PS', elem: 'poison', kind: 'gun', parasite: 1, color: '#b5e48c', dir: 'highhp', style: 'needle',
    desc: 'Infects enemies. When they die, the corpse becomes your turret for 8 seconds. Ethically grey, tactically green.',
    base: { dmg: 11, cd: 0.4, mag: 8, reload: 1.6, count: 1, spread: 0.08, speed: 560, pierce: 0, range: 430, size: 3.5, dur: 8 },
    lv: { 3: { count: 1 }, 5: { dur: 0.5 }, 7: { dmg: 0.4 } } },
  thermal: { name: 'Thermometer Lance', icon: 'TH', elem: 'fire', kind: 'beam', heat: 1, color: '#ff5400', dir: 'nearest',
    desc: 'No magazine, just temperature. Overheat and it vents a fireball around you. Not for oral use.',
    base: { dmg: 38, cd: 0, mag: 1, reload: 1.3, count: 1, dur: 3.2, range: 300, size: 5, area: 150 },
    lv: { 3: { dur: 0.3 }, 5: { area: 0.3 }, 7: { dmg: 0.4 } } },
  tether: { name: 'Umbilical Tether', icon: 'TE', elem: 'shock', kind: 'tether', color: '#9ef0ff', dir: 'highhp',
    desc: 'Ties two monsters together with a lightning cord and makes them hug. Violently.',
    base: { dmg: 16, cd: 1.1, mag: 3, reload: 1.8, count: 1, dur: 3, range: 380, pull: 170, jump: 240 },
    lv: { 3: { count: 1 }, 5: { dur: 0.4 }, 7: { dmg: 0.5 } } },
  gacha: { name: 'Gender Reveal Blaster', icon: 'GB', elem: 'phys', kind: 'gun', gacha: 1, color: '#ffd23f', dir: 'nearest',
    desc: 'Every magazine is a surprise. Every surprise is a letdown. Except the Legendary ones. Those explode and set fire to a forest.',
    base: { dmg: 12, cd: 0.22, mag: 12, reload: 1.3, count: 1, spread: 0.06, speed: 650, pierce: 0, range: 440, size: 4 },
    lv: { 3: { pierce: 1 }, 5: { count: 1 }, 7: { dmg: 0.3 } } },
  prequel: { name: 'Hindsight Launcher', icon: 'PQ', elem: 'fire', kind: 'prequel', color: '#ff9e00', dir: 'cluster',
    desc: 'The explosion happens first. The shell arrives afterwards, flying backwards into the barrel, still angry.',
    base: { dmg: 34, cd: 1.1, mag: 3, reload: 2.0, count: 1, area: 70, speed: 520, range: 480, spread: 40 },
    lv: { 3: { area: 0.25 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },

  // ---- Show-season fusions
  hailreturn: { name: 'Return to Sender', icon: 'HR', elem: 'ice', kind: 'siphon', color: '#caf0f8', dir: 'nearest', style: 'shard', merged: 1,
    desc: 'Their bullets. Your ice. Everyone else\'s problem. Returned shots freeze on hit.',
    base: { dmg: 20, cd: 0.06, mag: 70, area: 105, speed: 700, range: 500, size: 5, pierce: 2, spread: 0.1, count: 1, freezeHit: 1 },
    lv: { 5: { count: 1 }, 7: { dmg: 0.4 } } },
  plaguetrail: { name: 'Nappy Trail', icon: 'PT', elem: 'poison', kind: 'wake', color: '#70e000', dir: 'nearest', noTarget: 1, merged: 1,
    desc: 'You leave a lane of plague behind you. Lead the siege through it and wave.',
    base: { dmg: 30, dur: 4, area: 34, range: 0 },
    lv: { 5: { area: 0.3 }, 7: { dmg: 0.5 } } },
  salvage: { name: 'Pyramid Scheme', icon: 'SB', elem: 'fire', kind: 'lob', scrapAmmo: 1, salvage: 1, color: '#ffb400', dir: 'cluster', merged: 1,
    desc: 'Shells cost scrap. Shells make scrap. It is basically a pyramid scheme with explosions.',
    base: { dmg: 50, cd: 0.9, mag: 99, reload: 0.5, count: 3, spread: 60, range: 540, area: 80, flight: 0.9, explode: 1 },
    lv: { 5: { count: 1 }, 7: { area: 0.3 } } },
};

// ---------------------------------------------------------------- The Reproductive Arsenal
// Forty biology-themed weapons and eight fusions. Some carry a built-in effect (the same effects as the
// branch perks: pChill, pIgnite, pVenom, pArc, pExec, pGiant, splitHit, critBonus).
Object.assign(WEAPONS, {
  // Kinetic
  chromowhip: { name: 'Chromosome Whip', icon: 'CW', elem: 'phys', kind: 'gun', dir: 'furthest', style: 'glaive',
    desc: 'A coiled chromosome on a crack. Flies out, snaps back, hits everything twice.',
    base: { dmg: 17, cd: 0.9, mag: 2, reload: 1.2, count: 1, spread: 0.25, speed: 460, pierce: 99, range: 300, size: 9, boomerang: 1 },
    lv: { 3: { count: 1 }, 5: { dmg: 0.3 }, 7: { count: 1 } } },
  nailgun: { name: 'Keratin Nailgun', icon: 'KN', elem: 'phys', kind: 'gun', dir: 'nearest', style: 'needle',
    desc: 'Fires fingernail clippings at alarming speed. Please do not ask where it gets them.',
    base: { dmg: 5, cd: 0.09, mag: 32, reload: 1.5, count: 1, spread: 0.08, speed: 720, pierce: 1, range: 400, size: 2.5 },
    lv: { 3: { pierce: 1 }, 5: { cd: -0.15 }, 7: { count: 1 } } },
  ciliaflail: { name: 'Cilia Flail', icon: 'CF', elem: 'phys', kind: 'orbit', dir: 'nearest',
    desc: 'A ring of stiffened cilia sweeps around you. Very tidy. Very rude.',
    base: { dmg: 14, count: 4, dur: 4, reload: 2, radius: 64, spin: 4.2, size: 8, range: 90 },
    lv: { 3: { count: 1 }, 5: { area: 0.3 }, 7: { count: 2 } } },
  collagenbow: { name: 'Collagen Crossbow', icon: 'CC', elem: 'phys', kind: 'gun', dir: 'strongest', style: 'bolt',
    desc: 'Tough protein bolts that pierce and push. Structural integrity as a weapon.',
    base: { dmg: 26, cd: 0.8, mag: 4, reload: 1.6, count: 1, spread: 0.03, speed: 820, pierce: 2, range: 560, size: 3, knock: 60 },
    lv: { 3: { pierce: 1 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  marrowmortar: { name: 'Bone Marrow Mortar', icon: 'BM', elem: 'phys', kind: 'lob', dir: 'cluster',
    desc: 'Lobs dense marrow shells. Lands like a femur.',
    base: { dmg: 46, cd: 1.7, mag: 2, reload: 2.4, count: 1, spread: 30, range: 520, area: 78, flight: 1.0, explode: 1 },
    lv: { 3: { area: 0.25 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  histonehammer: { name: 'Histone Hammer', icon: 'HH', elem: 'phys', kind: 'gun', dir: 'nearest',
    desc: 'A point-blank wall of packed DNA spools. Enormous knockback.',
    base: { dmg: 11, cd: 0.9, mag: 3, reload: 1.5, count: 7, spread: 0.7, speed: 500, pierce: 1, range: 220, size: 4, knock: 130 },
    lv: { 3: { count: 2 }, 5: { dmg: 0.3 }, 7: { count: 3 } } },
  tendonrail: { name: 'Tendon Railshot', icon: 'TR', elem: 'phys', kind: 'gun', dir: 'armour', style: 'rail',
    desc: 'A tendon wound until it snaps. Pierces everything, shreds armour.',
    base: { dmg: 36, cd: 1.1, mag: 3, reload: 2, count: 1, spread: 0.04, speed: 1600, pierce: 99, range: 680, size: 3, shred: 2.5 },
    lv: { 3: { shred: 2 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  zonapunch: { name: 'Zona Punch', icon: 'ZP', elem: 'phys', kind: 'gun', dir: 'nearest', style: 'disc',
    desc: 'A hardened glycoprotein disc that ricochets around like it owns the place.',
    base: { dmg: 16, cd: 0.7, mag: 3, reload: 1.4, count: 1, spread: 0.2, speed: 520, pierce: 0, range: 380, size: 8, bounce: 3 },
    lv: { 3: { bounce: 2 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  // Fire
  enzymetorch: { name: 'Enzyme Torch', icon: 'ET', elem: 'fire', kind: 'gun', dir: 'nearest', style: 'flame',
    desc: 'Digestive enzymes, heated. It does not so much burn as disagree with you.',
    base: { dmg: 3.6, cd: 0.05, mag: 44, reload: 2, count: 2, spread: 0.4, speed: 300, pierce: 99, range: 190, size: 7, pIgnite: 0.2 },
    lv: { 3: { area: 0.3 }, 5: { dmg: 0.3 }, 7: { count: 1 } } },
  metaflare: { name: 'Metabolic Flare', icon: 'MF', elem: 'fire', kind: 'gun', dir: 'cluster', style: 'rocket',
    desc: 'Burns a week of calories in one rocket. Explodes in a satisfying way.',
    base: { dmg: 22, cd: 0.5, mag: 3, reload: 2.2, count: 1, spread: 0.12, speed: 420, pierce: 0, range: 520, size: 5, explode: 58 },
    lv: { 3: { area: 0.25 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  feverpitch: { name: 'Fever Pitch', icon: 'FP', elem: 'fire', kind: 'beam', heat: 1, dir: 'nearest',
    desc: 'A 41-degree beam. Overheat and you vent the whole fever around you.',
    base: { dmg: 34, cd: 0, mag: 1, reload: 1.2, count: 1, dur: 3.4, range: 290, size: 5, area: 140 },
    lv: { 3: { dur: 0.3 }, 5: { area: 0.3 }, 7: { dmg: 0.4 } } },
  mitogrenade: { name: 'Mitochondrial Grenade', icon: 'MG', elem: 'fire', kind: 'lob', dir: 'cluster',
    desc: 'The powerhouse of the cell, thrown. The school textbooks were right all along.',
    base: { dmg: 38, cd: 1.3, mag: 3, reload: 2.1, count: 1, spread: 36, range: 480, area: 70, flight: 0.8, explode: 1 },
    lv: { 3: { area: 0.25 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  pyrogen: { name: 'Pyrogen Mines', icon: 'PM', elem: 'fire', kind: 'mine', dir: 'nearest',
    desc: 'Leaves little fever-inducing mines behind you. The host will feel it too.',
    base: { dmg: 30, cd: 0.6, mag: 6, reload: 2.2, count: 1, explode: 66, life: 14, range: 600, pIgnite: 0.3 },
    lv: { 3: { count: 1 }, 5: { area: 0.3 }, 7: { dmg: 0.5 } } },
  acroburst: { name: 'Acrosome Burst', icon: 'AB', elem: 'fire', kind: 'gun', dir: 'nearest',
    desc: 'The enzyme cap you were meant to use on the egg, fired at everything else instead.',
    base: { dmg: 12, cd: 0.8, mag: 4, reload: 1.4, count: 5, spread: 0.6, speed: 480, pierce: 0, range: 240, size: 4, explode: 26 },
    lv: { 3: { count: 2 }, 5: { area: 0.3 }, 7: { dmg: 0.4 } } },
  // Frost
  cryopipette: { name: 'Cryo Pipette', icon: 'CP', elem: 'ice', kind: 'gun', dir: 'fastest', style: 'shard',
    desc: 'Precise drops of liquid cold. Lab-grade accuracy, very poor bedside manner.',
    base: { dmg: 14, cd: 0.5, mag: 6, reload: 1.4, count: 1, spread: 0.05, speed: 580, pierce: 2, range: 480, size: 4, pChill: 1 },
    lv: { 3: { count: 1 }, 5: { pierce: 2 }, 7: { count: 1 } } },
  ln2spray: { name: 'Liquid Nitrogen Spray', icon: 'LN', elem: 'ice', kind: 'gun', dir: 'nearest', style: 'flame',
    desc: 'A cone of minus 196 degrees. Things that stay in it stay put.',
    base: { dmg: 2.6, cd: 0.05, mag: 46, reload: 2, count: 2, spread: 0.42, speed: 290, pierce: 99, range: 190, size: 7, pChill: 1 },
    lv: { 3: { area: 0.3 }, 5: { dmg: 0.3 }, 7: { count: 1 } } },
  embryomortar: { name: 'Frozen Embryo Mortar', icon: 'FE', elem: 'ice', kind: 'lob', dir: 'cluster',
    desc: 'Cryo-stored and very cross about it. Shatters into a freezing blast.',
    base: { dmg: 34, cd: 1.4, mag: 2, reload: 2.3, count: 1, spread: 34, range: 500, area: 76, flight: 0.9, explode: 1, pChill: 1 },
    lv: { 3: { area: 0.25 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  hailswarm: { name: 'Hailstone Swarm', icon: 'HS', elem: 'ice', kind: 'gun', dir: 'weakest', style: 'missile',
    desc: 'Homing ice pellets. Small, cold and personal.',
    base: { dmg: 8, cd: 0.4, mag: 8, reload: 1.9, count: 2, spread: 1.1, speed: 330, pierce: 0, range: 480, size: 4, homing: 5, pChill: 1 },
    lv: { 3: { count: 1 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  glacialorbit: { name: 'Glacial Orbit', icon: 'GO', elem: 'ice', kind: 'orbit', dir: 'nearest',
    desc: 'Ice crystals orbit you and chill whatever they touch.',
    base: { dmg: 13, count: 3, dur: 4.5, reload: 2.2, radius: 78, spin: 3.2, size: 10, range: 100, pChill: 1 },
    lv: { 3: { count: 1 }, 5: { area: 0.3 }, 7: { count: 2 } } },
  // Shock
  nerveimpulse: { name: 'Nerve Impulse', icon: 'NI', elem: 'shock', kind: 'chain', dir: 'cluster',
    desc: 'An action potential, weaponised. Jumps from cell to cell faster than gossip.',
    base: { dmg: 12, cd: 0.6, mag: 7, reload: 1.7, count: 1, chain: 4, range: 320, jump: 150 },
    lv: { 3: { chain: 2 }, 5: { count: 1 }, 7: { chain: 3 } } },
  axonrail: { name: 'Axon Rail', icon: 'AR', elem: 'shock', kind: 'gun', dir: 'strongest', style: 'rail',
    desc: 'A myelinated slug down a very long nerve. Arcs to whatever it passes.',
    base: { dmg: 30, cd: 1.2, mag: 3, reload: 2, count: 1, spread: 0.05, speed: 1650, pierce: 99, range: 700, size: 3, pArc: 0.35, pArcDmg: 0.5, pArcN: 1 },
    lv: { 3: { count: 1 }, 5: { dmg: 0.3 }, 7: { dmg: 0.5 } } },
  synapsedrone: { name: 'Synapse Drone', icon: 'SD', elem: 'shock', kind: 'gun', dir: 'lowhp', drones: 1,
    desc: 'Tiny neurons in hover mode, firing sparks at whatever looks weakest.',
    base: { dmg: 7, cd: 0.4, mag: 12, reload: 1.5, count: 1, spread: 0.05, speed: 640, pierce: 0, range: 430, size: 3.5 },
    lv: { 3: { count: 1 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  pacemaker: { name: 'Pacemaker', icon: 'PC', elem: 'shock', kind: 'gun', dir: 'strongest', style: 'bolt',
    desc: 'One steady, heavy jolt every beat. Stuns what it hits.',
    base: { dmg: 40, cd: 1, mag: 6, reload: 1.6, count: 1, spread: 0.02, speed: 760, pierce: 1, range: 520, size: 4, freezeHit: 1 },
    lv: { 3: { pierce: 1 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  defib: { name: 'Defibrillator', icon: 'DF', elem: 'shock', kind: 'chain', dir: 'nearest',
    desc: 'CLEAR! Big, short-range shocks that leap through a crowd.',
    base: { dmg: 30, cd: 1.8, mag: 2, reload: 2.2, count: 1, chain: 6, range: 220, jump: 120 },
    lv: { 3: { chain: 2 }, 5: { dmg: 0.3 }, 7: { count: 1 } } },
  ionchannel: { name: 'Ion Channel', icon: 'IC', elem: 'shock', kind: 'beam', dir: 'strongest',
    desc: 'Opens a channel and lets the current flow straight through a line of foes.',
    base: { dmg: 28, cd: 1.6, mag: 3, reload: 2.1, count: 1, dur: 1.2, range: 400, size: 5, pArc: 0.25, pArcDmg: 0.5, pArcN: 1 },
    lv: { 3: { dur: 0.35 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  // Toxic
  antibioticsg: { name: 'Antibiotic Shotgun', icon: 'AS', elem: 'poison', kind: 'gun', dir: 'nearest',
    desc: 'A broad-spectrum course, all at once. Finish the whole magazine.',
    base: { dmg: 7, cd: 0.7, mag: 4, reload: 1.5, count: 6, spread: 0.55, speed: 530, pierce: 0, range: 270, size: 3.5, pVenom: 1 },
    lv: { 3: { count: 2 }, 5: { pierce: 1 }, 7: { count: 3 } } },
  mucusweb: { name: 'Mucus Web', icon: 'MW', elem: 'poison', kind: 'lob', dir: 'cluster',
    desc: 'Lobs sticky globs that leave slowing, toxic puddles. Ew, but effective.',
    base: { dmg: 7, cd: 0.9, mag: 4, reload: 1.8, count: 1, spread: 40, range: 380, area: 62, dur: 3.5, flight: 0.6, pChill: 1 },
    lv: { 3: { dur: 0.5 }, 5: { count: 1 }, 7: { area: 0.4 } } },
  hormonecloud: { name: 'Hormone Cloud', icon: 'HC', elem: 'poison', kind: 'gun', dir: 'cluster', style: 'void',
    desc: 'A slow drifting surge of hormones. Everything nearby gets confused and drawn in.',
    base: { dmg: 6, cd: 1.7, mag: 2, reload: 2.4, count: 1, spread: 0.2, speed: 120, pierce: 99, range: 400, size: 14, aura: 74, pull: 70, pVenom: 1 },
    lv: { 3: { area: 0.3 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  spermicide: { name: 'Spermicide Sprayer', icon: 'SP', elem: 'poison', kind: 'gun', dir: 'nearest', style: 'flame',
    desc: 'You are, technically, immune. Probably. Do not check.',
    base: { dmg: 3.2, cd: 0.05, mag: 48, reload: 2, count: 2, spread: 0.44, speed: 300, pierce: 99, range: 190, size: 7, pVenom: 1, pGiant: 0.5 },
    lv: { 3: { area: 0.3 }, 5: { dmg: 0.3 }, 7: { count: 1 } } },
  enzymedrill: { name: 'Enzyme Drill', icon: 'ED', elem: 'poison', kind: 'beam', dir: 'armour',
    desc: 'A beam of protease that eats through armour, then through whatever was under it.',
    base: { dmg: 26, cd: 1.5, mag: 3, reload: 2, count: 1, dur: 1.3, range: 360, size: 6, shred: 3, pVenom: 1 },
    lv: { 3: { dur: 0.35 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  toxinneedles: { name: 'Toxin Needles', icon: 'TN', elem: 'poison', kind: 'gun', dir: 'weakest', style: 'needle',
    desc: 'Homing hypodermics. They always find a vein.',
    base: { dmg: 4, cd: 0.14, mag: 24, reload: 1.6, count: 1, spread: 0.3, speed: 520, pierce: 0, range: 420, size: 2.5, homing: 4 },
    lv: { 3: { count: 1 }, 5: { pierce: 1 }, 7: { cd: -0.2 } } },
  viralpayload: { name: 'Viral Payload', icon: 'VP', elem: 'poison', kind: 'gun', dir: 'strongest', style: 'missile',
    desc: 'Missiles full of virus. Infected targets burst into turrets when they die.',
    base: { dmg: 11, cd: 0.6, mag: 4, reload: 2, count: 1, spread: 0.6, speed: 340, pierce: 0, range: 500, size: 4, homing: 4 },
    parasite: 1, lv: { 3: { count: 1 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  // Arcane
  genesplicer: { name: 'Gene Splicer', icon: 'GS', elem: 'arcane', kind: 'gun', dir: 'strongest', style: 'bolt',
    desc: 'Snips the target\'s genome at the worst possible place. Crits often.',
    base: { dmg: 22, cd: 0.55, mag: 5, reload: 1.5, count: 1, spread: 0.03, speed: 760, pierce: 1, range: 520, size: 3, critBonus: 0.25 },
    lv: { 3: { pierce: 1 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  mitosiscannon: { name: 'Mitosis Cannon', icon: 'MC', elem: 'arcane', kind: 'gun', dir: 'cluster',
    desc: 'Every shot divides on impact. Then the halves divide. Biology is relentless.',
    base: { dmg: 14, cd: 0.6, mag: 5, reload: 1.6, count: 1, spread: 0.1, speed: 520, pierce: 0, range: 450, size: 6, splitHit: 3 },
    lv: { 3: { count: 1 }, 5: { dmg: 0.3 }, 7: { count: 1 } } },
  telomere: { name: 'Telomere Beam', icon: 'TB', elem: 'arcane', kind: 'beam', dir: 'furthest',
    desc: 'A very long beam that shortens everything it touches. Ageing, weaponised.',
    base: { dmg: 30, cd: 1.8, mag: 3, reload: 2.2, count: 1, dur: 1.2, range: 540, size: 5, pExec: 0.5 },
    lv: { 3: { dur: 0.35 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  epiorb: { name: 'Epigenetic Orb', icon: 'EO', elem: 'arcane', kind: 'gun', dir: 'cluster', style: 'void',
    desc: 'Switches genes off in a wide radius. Monsters drift in, confused about who they are.',
    base: { dmg: 8, cd: 1.9, mag: 2, reload: 2.5, count: 1, spread: 0.2, speed: 110, pierce: 99, range: 400, size: 16, aura: 80, pull: 100 },
    lv: { 3: { area: 0.3 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  placebo: { name: 'Placebo Pistol', icon: 'PP', elem: 'arcane', kind: 'gun', dir: 'nearest',
    desc: 'Contains no active ingredients. Works anyway, especially on big things.',
    base: { dmg: 11, cd: 0.28, mag: 12, reload: 1.1, count: 1, spread: 0.04, speed: 640, pierce: 0, range: 440, size: 4, pGiant: 1 },
    lv: { 3: { pierce: 1 }, 5: { count: 1 }, 7: { dmg: 0.3 } } },
  stemmines: { name: 'Stem Cell Mines', icon: 'SM', elem: 'arcane', kind: 'mine', dir: 'nearest',
    desc: 'Undifferentiated mines. They become whatever kills best, which is usually an explosion.',
    base: { dmg: 34, cd: 0.7, mag: 5, reload: 2.4, count: 1, explode: 74, life: 16, range: 600, splitHit: 3 },
    lv: { 3: { count: 1 }, 5: { area: 0.3 }, 7: { dmg: 0.5 } } },
  retrovirus: { name: 'Retrovirus Swarm', icon: 'RV', elem: 'arcane', kind: 'gun', dir: 'weakest', style: 'missile',
    desc: 'Homing viral particles that write themselves into the target. Leaves a poison.',
    base: { dmg: 8, cd: 0.42, mag: 7, reload: 2, count: 2, spread: 1.2, speed: 320, pierce: 0, range: 500, size: 4, homing: 5, pVenom: 1 },
    lv: { 3: { count: 1 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  ribosome: { name: 'Ribosome Printer', icon: 'RP', elem: 'arcane', kind: 'orbit', dir: 'nearest',
    desc: 'Prints protein blades around you, one amino acid at a time.',
    base: { dmg: 15, count: 3, dur: 4.2, reload: 2, radius: 70, spin: 3.8, size: 9, range: 100 },
    lv: { 3: { count: 1 }, 5: { area: 0.3 }, 7: { count: 2 } } },
  // Fusions
  spindle: { name: 'Spindle Apparatus', icon: 'SA', elem: 'phys', kind: 'orbit', dir: 'nearest', merged: true,
    desc: 'Whips and cilia become a mitotic spindle that shreds anything in the division zone.',
    base: { dmg: 30, count: 6, dur: 5, reload: 1.6, radius: 88, spin: 4.4, size: 11, range: 120, shred: 2 },
    lv: { 3: { count: 1 }, 5: { area: 0.3 }, 7: { dmg: 0.5 } } },
  thermocycler: { name: 'Thermal Cycler', icon: 'TX', elem: 'fire', elem2: 'ice', kind: 'gun', dir: 'nearest', style: 'flame', merged: true,
    desc: 'PCR in cone form: denature, anneal, extend, repeat. Burns and freezes by turns.',
    base: { dmg: 7, cd: 0.05, mag: 60, reload: 1.8, count: 3, spread: 0.45, speed: 320, pierce: 99, range: 230, size: 8, pIgnite: 0.25, pChill: 1 },
    lv: { 3: { area: 0.3 }, 5: { dmg: 0.3 }, 7: { count: 1 } } },
  actionpotential: { name: 'Action Potential', icon: 'AP', elem: 'shock', kind: 'gun', dir: 'strongest', style: 'rail', merged: true,
    desc: 'All-or-nothing: a rail of pure nerve signal that arcs through everything in its path.',
    base: { dmg: 60, cd: 0.9, mag: 4, reload: 1.8, count: 1, spread: 0.04, speed: 1800, pierce: 99, range: 760, size: 4, pArc: 0.6, pArcDmg: 0.6, pArcN: 2 },
    lv: { 3: { count: 1 }, 5: { dmg: 0.4 }, 7: { dmg: 0.5 } } },
  superbug: { name: 'Superbug', icon: 'SB', elem: 'poison', kind: 'gun', dir: 'strongest', style: 'missile', merged: true,
    desc: 'Resistant to everything, including your conscience. Missiles that split and infect.',
    base: { dmg: 18, cd: 0.5, mag: 6, reload: 1.8, count: 2, spread: 0.8, speed: 360, pierce: 0, range: 520, size: 5, homing: 5, pVenom: 1, splitHit: 3 },
    parasite: 1, lv: { 3: { count: 1 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  crispr: { name: 'CRISPR Cannon', icon: 'CR', elem: 'arcane', kind: 'gun', dir: 'strongest', style: 'bolt', merged: true,
    desc: 'Precision edits at scale. Every shot divides, and every piece crits.',
    base: { dmg: 34, cd: 0.45, mag: 6, reload: 1.4, count: 1, spread: 0.03, speed: 800, pierce: 2, range: 560, size: 4, critBonus: 0.35, splitHit: 4 },
    lv: { 3: { pierce: 1 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  cryobank: { name: 'Cryobank', icon: 'CB', elem: 'ice', kind: 'gun', dir: 'weakest', style: 'missile', merged: true,
    desc: 'The whole freezer, launched. Homing, piercing, freezing.',
    base: { dmg: 16, cd: 0.35, mag: 10, reload: 1.6, count: 3, spread: 1.1, speed: 380, pierce: 2, range: 520, size: 5, homing: 6, pChill: 1, freezeHit: 1 },
    lv: { 3: { count: 1 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  crashcart: { name: 'Crash Cart', icon: 'CK', elem: 'shock', kind: 'chain', dir: 'cluster', merged: true,
    desc: 'The full resuscitation trolley. Enormous shocks through the whole crowd.',
    base: { dmg: 44, cd: 1, mag: 4, reload: 1.8, count: 2, chain: 8, range: 360, jump: 160 },
    lv: { 3: { chain: 3 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  osteoclast: { name: 'Osteoclast Barrage', icon: 'OS', elem: 'phys', elem2: 'fire', kind: 'lob', dir: 'cluster', merged: true,
    desc: 'Bone-dissolving cells, burning, delivered by mortar. A lot of mortar.',
    base: { dmg: 52, cd: 0.9, mag: 4, reload: 2.2, count: 2, spread: 60, range: 560, area: 84, flight: 0.9, explode: 1, pIgnite: 0.25 },
    lv: { 3: { area: 0.25 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
});

const MERGES = [
  { a: 'chromowhip',   b: 'ciliaflail',   out: 'spindle' },
  { a: 'enzymetorch',  b: 'ln2spray',     out: 'thermocycler' },
  { a: 'nerveimpulse', b: 'axonrail',     out: 'actionpotential' },
  { a: 'antibioticsg', b: 'viralpayload', out: 'superbug' },
  { a: 'genesplicer',  b: 'mitosiscannon', out: 'crispr' },
  { a: 'cryopipette',  b: 'hailswarm',    out: 'cryobank' },
  { a: 'pacemaker',    b: 'defib',        out: 'crashcart' },
  { a: 'marrowmortar', b: 'metaflare',    out: 'osteoclast' },
  { a: 'flamer',  b: 'frost',     out: 'steam' },
  { a: 'shotgun', b: 'tesla',     out: 'thunderbuck' },
  { a: 'railgun', b: 'prism',     out: 'annihilator' },
  { a: 'rocket',  b: 'seeker',    out: 'hydra' },
  { a: 'glaive',  b: 'orbit',     out: 'cyclone' },
  { a: 'blaster', b: 'ricochet',  out: 'pinball' },
  { a: 'venom',   b: 'mortar',    out: 'plague' },
  { a: 'mines',   b: 'void',      out: 'singularity' },
  { a: 'drone',   b: 'smg',       out: 'hive' },
  { a: 'arbalest', b: 'gatling',  out: 'siege' },
  { a: 'frost',   b: 'hailstorm', out: 'zero' },
  { a: 'needler', b: 'tesla',     out: 'neuro' },
  { a: 'siphon',  b: 'frost',     out: 'hailreturn' },
  { a: 'wake',    b: 'venom',     out: 'plaguetrail' },
  { a: 'scrapcannon', b: 'mortar', out: 'salvage' },
];
const MERGE_MIN_LEVEL = 4;

// Spells: autocast on cooldown, occupy spell slots.
const SPELLS = {
  meteor: { name: 'Stork Drop', icon: 'ME', elem: 'fire', kind: 'strike', color: '#ff5400', dir: 'cluster',
    desc: 'A stork drops something heavy on the target and leaves burning ground. Not a baby.',
    base: { dmg: 65, cd: 5, count: 1, area: 88, delay: 0.7, range: 520, dur: 2 },
    lv: { 3: { count: 1 }, 5: { area: 0.3 }, 7: { count: 1 } } },
  frostnova: { name: 'Cold Shower', icon: 'FN', elem: 'ice', kind: 'nova', color: '#90e0ef', dir: 'nearest',
    desc: 'A freezing blast around you. Erases enemy bullets, and enthusiasm.',
    base: { dmg: 22, cd: 7, area: 165, range: 170 },
    lv: { 3: { area: 0.2 }, 5: { dmg: 0.5 }, 7: { cd: -0.25 } } },
  thunder: { name: 'Brainstorm', icon: 'TS', elem: 'shock', kind: 'thunder', color: '#fdf0d5', dir: 'strongest',
    desc: 'Lightning strikes several targets at once. None of the ideas are good.',
    base: { dmg: 36, cd: 6, count: 5, area: 48, range: 520 },
    lv: { 3: { count: 2 }, 5: { dmg: 0.4 }, 7: { count: 3 } } },
  blackhole: { name: 'Sofa Crevice', icon: 'BH', elem: 'arcane', kind: 'zone', color: '#7209b7', dir: 'cluster',
    desc: 'Tears open a singularity that drags and crushes. Everything you ever lost is in there.',
    base: { dmg: 16, cd: 10, area: 125, dur: 3, pull: 210, range: 460 },
    lv: { 3: { dur: 0.3 }, 5: { area: 0.3 }, 7: { dmg: 0.6 } } },
  heal: { name: 'Kiss It Better', icon: 'RJ', elem: 'poison', kind: 'heal', color: '#80ffdb', dir: 'nearest', noTarget: 1,
    desc: 'Restores a portion of your health. Medically dubious. Works anyway.',
    base: { dmg: 0.15, cd: 14, range: 0 },
    lv: { 3: { cd: -0.15 }, 5: { dmg: 0.5 }, 7: { cd: -0.2 } } },
  warp: { name: 'Nap Time', icon: 'TW', elem: 'arcane', kind: 'warp', color: '#b8c0ff', dir: 'nearest', noTarget: 1,
    desc: 'Slows every enemy and bullet to a crawl. Rare. Precious. Over too soon.',
    base: { dmg: 0, cd: 16, dur: 3, range: 0 },
    lv: { 3: { dur: 0.3 }, 5: { cd: -0.2 }, 7: { dur: 0.4 } } },
  barrier: { name: 'Latex Barrier', icon: 'AE', elem: 'arcane', kind: 'barrier', color: '#48cae4', dir: 'nearest', noTarget: 1,
    desc: 'A shield that reflects enemy bullets and blocks contact. 98% effective.',
    base: { dmg: 12, cd: 12, dur: 3, area: 80, range: 0 },
    lv: { 3: { dur: 0.35 }, 5: { area: 0.3 }, 7: { cd: -0.25 } } },
  bladestorm: { name: 'Running With Scissors', icon: 'BS', elem: 'phys', kind: 'ring', color: '#e9ecef', dir: 'nearest', noTarget: 1,
    desc: 'Explodes a ring of blades outward. You were told.',
    base: { dmg: 19, cd: 6, count: 16, speed: 460, pierce: 3, range: 360, size: 6 },
    lv: { 3: { count: 8 }, 5: { pierce: 3 }, 7: { dmg: 0.5 } } },
  cloud: { name: 'Dutch Oven', icon: 'PC', elem: 'poison', kind: 'zone', color: '#9ef01a', dir: 'cluster',
    desc: 'A drifting cloud of stacking poison. You know what you did.',
    base: { dmg: 11, cd: 9, area: 115, dur: 5, pull: 0, range: 460 },
    lv: { 3: { dur: 0.4 }, 5: { area: 0.3 }, 7: { dmg: 0.6 } } },
  sentry: { name: 'Baby Monitor', icon: 'SN', elem: 'shock', kind: 'sentry', color: '#ffd60a', dir: 'nearest', noTarget: 1,
    desc: 'Deploys a turret that watches and shoots using this directive. Static included.',
    base: { dmg: 9, cd: 13, count: 1, dur: 10, rate: 0.25, range: 400 },
    lv: { 3: { dur: 0.3 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
};

const RARITIES = [
  { id: 'common',    name: 'Bronze',    color: '#cd8a4a', mult: 1,   lvls: 1, w: 60 },
  { id: 'rare',      name: 'Silver',    color: '#c9d6e3', mult: 1.5, lvls: 1, w: 27 },
  { id: 'epic',      name: 'Gold',      color: '#ffd23f', mult: 2,   lvls: 2, w: 10 },
  { id: 'legendary', name: 'Legendary', color: '#ff3df2', mult: 3,   lvls: 3, w: 3 },
];

// Passive power-ups. v = value per stack at common rarity; rarity multiplies it.
const PASSIVES = {
  might:     { name: 'Protein Shake',            icon: 'MT', max: 8, v: 0.12, fmt: v => `+${pc(v)} damage`, apply: (P, v) => { P.might += v; } },
  haste:     { name: 'Twitchy Tail', icon: 'TD', max: 8, v: 0.10, fmt: v => `+${pc(v)} fire rate`, apply: (P, v) => { P.haste += v; } },
  reload:    { name: 'Short Refractory Period',      icon: 'QH', max: 6, v: 0.15, fmt: v => `+${pc(v)} reload speed`, apply: (P, v) => { P.reloadSpd += v; } },
  mag:       { name: 'Bigger Load',    icon: 'EM', max: 6, v: 0.20, fmt: v => `+${pc(v)} magazine size`, apply: (P, v) => { P.magMult += v; } },
  multishot: { name: 'Split Personality',        icon: 'MS', max: 3, v: 1, minRarity: 2, fmt: v => `+${Math.round(v)} projectile for all weapons`, apply: (P, v) => { P.multishot += Math.round(v); } },
  velocity:  { name: 'Early Arrival',         icon: 'VE', max: 5, v: 0.12, fmt: v => `+${pc(v)} projectile speed and range`, apply: (P, v) => { P.projSpeed += v; P.range += v * 0.6; } },
  area:      { name: 'Personal Space',     icon: 'BR', max: 6, v: 0.12, fmt: v => `+${pc(v)} area of effect`, apply: (P, v) => { P.area += v; } },
  duration:  { name: 'Stamina',        icon: 'LG', max: 5, v: 0.15, fmt: v => `+${pc(v)} effect duration`, apply: (P, v) => { P.dur += v; } },
  pierce:    { name: 'Pushy',       icon: 'PN', max: 4, v: 1, fmt: v => `+${Math.round(v)} pierce`, apply: (P, v) => { P.pierce += Math.round(v); } },
  crit:      { name: 'Sharp Elbows',          icon: 'DE', max: 6, v: 0.05, fmt: v => `+${pc(v)} crit chance`, apply: (P, v) => { P.crit += v; } },
  critdmg:   { name: 'Low Blow',      icon: 'EX', max: 6, v: 0.25, fmt: v => `+${pc(v)} crit damage`, apply: (P, v) => { P.critDmg += v; } },
  vital:     { name: 'Thick Skin',       icon: 'VC', max: 8, v: 15, fmt: v => `+${Math.round(v)} max HP (and heal it)`, apply: (P, v, G) => { P.maxHp += Math.round(v); G.player.hp += Math.round(v); } },
  regen:     { name: 'Pregnancy Vitamins',          icon: 'NA', max: 5, v: 0.3, fmt: v => `+${v.toFixed(1)} HP/sec regen`, apply: (P, v) => { P.regen += v; } },
  grip:      { name: 'Sticky Cilia',     icon: 'SC', max: 5, v: 0.22, fmt: v => `+${pc(v)} traction: sharper turns, less drift`, apply: (P, v) => { P.traction += v; } },
  hydro:     { name: 'Hydrodynamic Head', icon: 'HH', max: 3, v: 0.12, fmt: v => `+${pc(v)} traction and +${pc(v / 2)} swim speed`, apply: (P, v) => { P.traction += v; P.speed += v / 2; } },
  speed:     { name: 'Leg Day (Tail Day)',    icon: 'SP', max: 5, v: 0.08, fmt: v => `+${pc(v)} move speed`, apply: (P, v) => { P.speed += v; } },
  magnet:    { name: 'Clingy',    icon: 'TF', max: 5, v: 0.3, fmt: v => `+${pc(v)} pickup range`, apply: (P, v) => { P.magnet += v; } },
  armour:    { name: 'Shell Suit',          icon: 'PT', max: 6, v: 1, fmt: v => `+${Math.round(v)} armour (flat damage reduction)`, apply: (P, v) => { P.armour += Math.round(v); } },
  luck:      { name: 'Lucky Swimmer',          icon: 'FO', max: 5, v: 0.15, fmt: v => `+${pc(v)} luck (rarer loot, more drops)`, apply: (P, v) => { P.luck += v; } },
  vamp:      { name: 'Leech Mode',  icon: 'VR', max: 5, v: 0.08, fmt: v => `Heal ${v.toFixed(2)} HP per kill`, apply: (P, v) => { P.lifesteal += v; } },
  pyro:      { name: 'Hot-Blooded',        icon: 'PY', max: 5, v: 0.25, fmt: v => `+${pc(v)} fire damage and burn`, apply: (P, v) => { P.elem.fire += v; } },
  cryo:      { name: 'Cold-Blooded',        icon: 'CY', max: 5, v: 0.25, fmt: v => `+${pc(v)} frost damage and chill`, apply: (P, v) => { P.elem.ice += v; } },
  storm:     { name: 'Static Hair',      icon: 'SC', max: 5, v: 0.25, fmt: v => `+${pc(v)} shock damage, +1 chain`, apply: (P, v) => { P.elem.shock += v; P.chain += 1; } },
  toxin:     { name: 'Bad Breath',       icon: 'TX', max: 5, v: 0.25, fmt: v => `+${pc(v)} poison damage, +3 max stacks`, apply: (P, v) => { P.elem.poison += v; P.poisonCap += 3; } },
  arcanum:   { name: 'Weird Aura',          icon: 'AR', max: 5, v: 0.25, fmt: v => `+${pc(v)} arcane damage`, apply: (P, v) => { P.elem.arcane += v; } },
  kinetic:   { name: 'Headbutt Training',       icon: 'BA', max: 5, v: 0.25, fmt: v => `+${pc(v)} kinetic damage`, apply: (P, v) => { P.elem.phys += v; } },
  catalyst:  { name: 'Chemistry',         icon: 'CT', max: 5, v: 0.35, fmt: v => `+${pc(v)} elemental reaction damage`, apply: (P, v) => { P.react += v; } },
  echo:      { name: 'Repeat Prescription',       icon: 'SE', max: 5, v: 0.10, fmt: v => `-${pc(v)} spell cooldowns`, apply: (P, v) => { P.cdr = Math.max(0.4, P.cdr - v); } },
  scholar:   { name: 'Antenatal Classes',          icon: 'SH', max: 5, v: 0.12, fmt: v => `+${pc(v)} experience gained`, apply: (P, v) => { P.xp += v; } },
  temporal:  { name: 'Snooze Button',    icon: 'TL', max: 3, v: 1, minRarity: 1, fmt: () => `+1 max Rewind charge, +25% Chrono energy`, apply: (P, v, G) => { G.chrono.max += 1; P.chronoGain += 0.25; } },
  salvage:   { name: 'Hand-Me-Downs',         icon: 'SV', max: 5, needsScrap: 1, v: 0.25, fmt: v => `+${pc(v)} scrap from kills`, apply: (P, v) => { P.scrap += v; } },
  lastround: { name: 'Last Word',        icon: 'LW', max: 3, v: 1, fmt: v => `Last bullet of every magazine deals x${3 + Math.round(v)} damage and explodes`, apply: (P, v) => { P.lastRound += Math.round(v); } },
  tactical:  { name: 'Tactical Nap',  icon: 'TR', max: 4, v: 1, fmt: v => `Starting a reload sends out a shockwave that deletes nearby bullets (+${40 * Math.round(v)} radius)`, apply: (P, v) => { P.tactical += Math.round(v); } },
  focus:     { name: 'Tunnel Vision',       icon: 'FL', max: 3, v: 0.3, fmt: v => `+3% damage per second on the same target, up to +${pc(v)} more`, apply: (P, v) => { P.focus += v; } },
  overkill:  { name: 'Overachiever', icon: 'OK', max: 3, v: 0.5, fmt: v => `${pc(v)} of excess kill damage jumps to the next enemy`, apply: (P, v) => { P.overkill += v; } },
  crossfire: { name: 'Pincer Movement', icon: 'CF', max: 3, v: 0.25, fmt: v => `Weapons sharing a target: +${pc(v)} damage. All three on different targets: +${pc(v)} fire rate`, apply: (P, v) => { P.crossfire += v; } },
  momentum:  { name: 'Hurry Up',         icon: 'MO', max: 4, v: 0.15, fmt: v => `Up to +${pc(v * 1.5)} damage the faster you are moving`, apply: (P, v) => { P.momentum += v; } },
  anchorlink:{ name: 'Egg Bond',         icon: 'EB', max: 3, v: 0.3, fmt: v => `Near the egg: +${pc(v)} fire rate. Away from it: +${pc(v)} crit chance`, apply: (P, v) => { P.anchorLink += v; } },
  future:    { name: 'Spoilers',    icon: 'FU', max: 4, v: 0.1, fmt: v => `${pc(v)} of shots appear already next to their target`, apply: (P, v) => { P.future += v; } },
  echoinherit: { name: 'Inheritance', icon: 'EI', max: 1, v: 1, minRarity: 1, fmt: () => `Paradox Echoes also cast your spells and last twice as long`, apply: (P) => { P.echoInherit = 1; } },
  evasion:   { name: 'Wriggle Room',          icon: 'EV', max: 5, v: 0.04, fmt: v => `+${pc(v)} chance to dodge hits`, apply: (P, v) => { P.dodge = Math.min(0.5, P.dodge + v); } },
};
function pc(v) { return Math.round(v * 100) + '%'; }

// Element reactions (triggered when an element hits an enemy already carrying another status).
const REACTIONS = {
  thermal:   { name: 'THERMAL SHOCK', color: '#ff9e9e', desc: 'Fire on a chilled/frozen enemy: big burst damage' },
  steam:     { name: 'STEAM BURST',   color: '#e0fbfc', desc: 'Frost on a burning enemy: scalding area blast' },
  combust:   { name: 'COMBUSTION',    color: '#ffba08', desc: 'Fire on a poisoned enemy: poison stacks explode' },
  toxicarc:  { name: 'TOXIC ARC',     color: '#d4ff5c', desc: 'Shock on a poisoned enemy: poison spreads to neighbours' },
  supercon:  { name: 'SUPERCONDUCT',  color: '#bde0fe', desc: 'Shock on a chilled enemy: armour shredded' },
  resonance: { name: 'RESONANCE',     color: '#e0aaff', desc: 'Arcane on any status: bonus damage, mark spreads' },
  overload:  { name: 'OVERLOAD',      color: '#fff3b0', desc: 'Fire on a shocked enemy: lightning explosion' },
};

// Elemental synergy set bonuses: owning N weapons/spells of one element.
const SYNERGIES = {
  phys:   { name: 'Gunslinger',  desc: '+15% fire rate for kinetic weapons' },
  fire:   { name: 'Pyromaniac',  desc: 'Burns last longer and deal +50% damage' },
  ice:    { name: 'Permafrost',  desc: 'Freeze threshold halved, frozen take +25%' },
  shock:  { name: 'Conductor',   desc: 'Shocked enemies arc twice as often' },
  poison: { name: 'Plaguebringer', desc: 'Poison ticks twice as fast' },
  arcane: { name: 'Arcanist',    desc: 'Marks amplify damage by +50% instead of +30%' },
};

// Enemies. from = seconds before they can spawn, w = spawn weight.
const ENEMIES = {
  // Rival swimmers (they have tails) and the host's immune system (they have opinions).
  crawler:  { name: 'Rival Swimmer', hp: 14, speed: 64, armour: 0, r: 12, dmg: 8, xp: 1, color: '#f4ecd8', shape: 'sperm', ai: 'chase', from: 0, w: 10 },
  skitter:  { name: 'Sprinter', hp: 6, speed: 125, armour: 0, r: 8, dmg: 5, xp: 1, color: '#ffd6a5', shape: 'sperm', ai: 'chase', from: 15, w: 7 },
  spitter:  { name: 'Antibody', hp: 20, speed: 58, armour: 0, r: 13, dmg: 6, xp: 3, color: '#ffd23f', shape: 'antibody', ai: 'ranged', from: 35, w: 4,
    shoot: { pattern: 'aimed', cd: 2.6, speed: 170, dmg: 6 } },
  brute:    { name: 'Macrophage', hp: 60, speed: 44, armour: 3, r: 20, dmg: 16, xp: 4, color: '#ff8fab', shape: 'cell', ai: 'chase', from: 55, w: 4 },
  bomber:   { name: 'Acid Bubble', hp: 16, speed: 98, armour: 0, r: 12, dmg: 18, xp: 2, color: '#b8f35a', shape: 'spike', ai: 'bomber', from: 100, w: 3 },
  splitter: { name: 'Mitotic Cell', hp: 42, speed: 52, armour: 0, r: 17, dmg: 10, xp: 3, color: '#43e97b', shape: 'cell', ai: 'chase', from: 85, w: 3, split: 'splitling' },
  splitling:{ name: 'Daughter Cell', hp: 12, speed: 92, armour: 0, r: 9, dmg: 5, xp: 1, color: '#7af5a8', shape: 'cell', ai: 'chase', from: 99999, w: 0 },
  // Tiny krill: shoals of flick-swimming crustaceans that dart in bursts. Nobody knows how they got in here.
  krill:    { name: 'Krill', hp: 3, speed: 150, armour: 0, r: 6, dmg: 3, xp: 0.5, color: '#e6ddd0', shape: 'krill', ai: 'krill', from: 45, w: 2, group: 12 },
  wisp:     { name: 'Spermlet Swarm', hp: 4, speed: 145, armour: 0, r: 6, dmg: 4, xp: 0.5, color: '#fee9a0', shape: 'sperm', ai: 'chase', from: 95, w: 2, group: 9 },
  blinker:  { name: 'Quantum Swimmer', hp: 22, speed: 72, armour: 0, r: 12, dmg: 9, xp: 3, color: '#00f5d4', shape: 'sperm', ai: 'blink', from: 105, w: 2 },
  medic:    { name: 'Nurse Cell', hp: 30, speed: 56, armour: 1, r: 13, dmg: 6, xp: 4, color: '#7bed9f', shape: 'cross', ai: 'medic', from: 120, w: 2 },
  charger:  { name: 'Headbutter', hp: 50, speed: 56, armour: 2, r: 16, dmg: 18, xp: 4, color: '#ffb4a2', shape: 'sperm', ai: 'charge', from: 130, w: 3 },
  bulwark:  { name: 'Mucus Wall', hp: 95, speed: 40, armour: 8, r: 20, dmg: 14, xp: 6, color: '#c9d6e3', shape: 'cell', ai: 'aura', from: 150, w: 2 },
  warlock:  { name: 'Cytokine Caster', hp: 45, speed: 46, armour: 1, r: 15, dmg: 8, xp: 6, color: '#9b5de5', shape: 'star', ai: 'ranged', from: 170, w: 2,
    shoot: { pattern: 'ring', count: 8, cd: 3.2, speed: 140, dmg: 9 } },
  phantom:  { name: 'Ghost Swimmer', hp: 35, speed: 82, armour: 0, r: 13, dmg: 10, xp: 5, color: '#caf0f8', shape: 'sperm', ai: 'phase', from: 195, w: 2 },
  summoner: { name: 'Mother Cell', hp: 75, speed: 40, armour: 2, r: 18, dmg: 10, xp: 8, color: '#ff6fa8', shape: 'cell', ai: 'summon', from: 210, w: 1.2 },
  spire:    { name: 'Enzyme Spire', hp: 85, speed: 16, armour: 4, r: 18, dmg: 10, xp: 8, color: '#ff006e', shape: 'hex', ai: 'turret', from: 240, w: 1.5,
    shoot: { pattern: 'spiral', cd: 0.16, speed: 125, dmg: 7 } },
  lancer:   { name: 'Killer T-Cell', hp: 26, speed: 52, armour: 0, r: 13, dmg: 6, xp: 5, color: '#ff99c8', shape: 'antibody', ai: 'ranged', from: 260, w: 1.5,
    shoot: { pattern: 'snipe', cd: 3.6, speed: 430, dmg: 16 } },
  // Spongy engulfers: slow, tough, knockback-proof, and they eat other monsters to grow (up to 'max' radius).
  amoeba:   { name: 'Amoeba', hp: 150, speed: 30, armour: 1, r: 30, dmg: 14, xp: 10, color: '#7fd8b0', shape: 'amoeba', ai: 'engulf', from: 70, w: 0.9, spongy: true, max: 175 },
  plasmod:  { name: 'Plasmodium', hp: 380, speed: 22, armour: 3, r: 42, dmg: 22, xp: 24, color: '#e9c46a', shape: 'amoeba', ai: 'engulf', from: 240, w: 0.7, spongy: true, max: 210, split: 'amoeba' },
  // More of the pond: a wriggling worm, a glass-shelled turret, a near-indestructible water bear, a ciliate
  // that swims in straight lines and backs off when it bumps you, a rotifer that hoovers up your XP, and a
  // Volvox colony that bursts into daughter colonies.
  pinworm:  { name: 'Pinworm', hp: 70, speed: 60, armour: 1, r: 11, dmg: 12, xp: 5, color: '#e8e2d6', shape: 'worm', ai: 'chase', from: 140, w: 1.6 },
  diatom:   { name: 'Diatom', hp: 55, speed: 24, armour: 6, r: 16, dmg: 8, xp: 6, color: '#cfe0d8', shape: 'diatom', ai: 'ranged', from: 180, w: 1.4,
    shoot: { pattern: 'ring', count: 6, cd: 2.8, speed: 150, dmg: 8 } },
  waterbear:{ name: 'Water Bear', hp: 240, speed: 30, armour: 10, r: 22, dmg: 20, xp: 14, color: '#d9cdb8', shape: 'tardigrade', ai: 'chase', from: 270, w: 0.8, heavy: true, tun: true },
  paramecium:{ name: 'Paramecium', hp: 30, speed: 105, armour: 0, r: 13, dmg: 10, xp: 4, color: '#dfe6d2', shape: 'slipper', ai: 'ciliate', from: 75, w: 2 },
  rotifer:  { name: 'Rotifer', hp: 40, speed: 50, armour: 1, r: 14, dmg: 8, xp: 5, color: '#e3dccb', shape: 'rotifer', ai: 'thief', from: 110, w: 1.4 },
  volvox:   { name: 'Volvox', hp: 110, speed: 34, armour: 2, r: 26, dmg: 14, xp: 8, color: '#c8d9b8', shape: 'volvox', ai: 'chase', from: 160, w: 1.1, split: 'volvoxling', splitN: 4 },
  volvoxling:{ name: 'Daughter Colony', hp: 26, speed: 62, armour: 0, r: 12, dmg: 6, xp: 2, color: '#c8d9b8', shape: 'volvox', ai: 'chase', from: 99999, w: 0 },
  juggernaut: { name: 'Alpha Swimmer', hp: 420, speed: 34, armour: 12, r: 28, dmg: 30, xp: 20, color: '#d4c1a4', shape: 'sperm', ai: 'chase', from: 300, w: 0.6 },
};

const BOSSES = [
  { id: 'queen',    name: 'THE MACROPHAGE QUEEN', hp: 2600, speed: 46, armour: 2, r: 44, dmg: 25, xp: 60, color: '#ff4d8d', shape: 'cell', patterns: ['spiral', 'summon', 'ring', 'aimedFan'] },
  { id: 'colossus', name: 'THE ANTIBODY COLOSSUS', hp: 4200, speed: 36, armour: 10, r: 52, dmg: 35, xp: 90, color: '#ffd23f', shape: 'antibody', patterns: ['ring', 'charge', 'aimedFan', 'doubleSpiral'] },
  { id: 'voideye',  name: 'THE IMMUNE EYE',   hp: 3400, speed: 52, armour: 4, r: 46, dmg: 30, xp: 80, color: '#7b2cbf', shape: 'eye', patterns: ['doubleSpiral', 'blink', 'ring', 'flower'] },
];
const BOSS_INTERVAL = 180; // seconds

// Field power-ups.
const POWERUPS = {
  magnet: { name: 'MAGNET',  letter: 'M', color: '#4cc9f0', desc: 'All XP flies to you' },
  nuke:   { name: 'ACID FLUSH',    letter: 'N', color: '#ff595e', desc: 'Obliterates nearby enemies' },
  rage:   { name: 'ADRENALINE', letter: 'O', color: '#ff924c', desc: 'Double fire rate, no reloads' },
  heal:   { name: 'GLUCOSE HIT',  letter: '+', color: '#8ac926', desc: 'Restore 35% HP' },
  shield: { name: 'SHIELD',  letter: 'S', color: '#48cae4', desc: 'Invulnerable for 5s' },
  freeze: { name: 'STASIS',  letter: 'F', color: '#a2d2ff', desc: 'Freeze all enemies' },
  chest:  { name: 'LOOT BOX', letter: '?', color: '#ffca3a', desc: 'Free upgrade' },
};

// ---------------------------------------------------------------- The Egg
// The egg sits at the world origin: the arena's centre. Standing in its glow heals you.
const CORE = { r: 80, sanctuary: 290, arena: 2400 };
// Break into the egg: reach EGG.level and its membrane becomes vulnerable. Destroy it to be born (you win).
const EGG = { level: 60, hpBase: 150000, armour: 8 };
// Extra weapon slots unlock at these levels (3 to start, 6 at most).
const SLOT_LEVELS = [15, 30, 45];

// ---------------------------------------------------------------- Palette
// Colour is rationed. Everything is greyscale except four meanings:
//   you     - GFP green: you, your shots, your echoes and your mind-controlled allies
//   danger  - red: anything that can hurt you (enemy bullets, acid, hits you take, low HP)
//   reward  - gold: loot, big XP, elites (they carry loot), charged mitochondria
//   rivals  - each rival champion's own fluorescent dye (their tag, track and name only)
// Loot boxes are reward-gold everywhere, in the world and in the UI.
// The renderer greys out any other colour it is asked to draw.
// Two more for the interface, taken from patient-monitor conventions (each trace has its own fixed colour):
//   upgrade - monitor cyan: anything that permanently changes your build (weapons, levels, perks, mods, stats)
//   pickup  - monitor magenta: temporary field power-ups lying on the slide
const PAL = { you: '#4dff9a', danger: '#ff3b3b', reward: '#ffd23f', upgrade: '#5fd4e8', pickup: '#d983e8' };

// ---------------------------------------------------------------- Weapon upgrade trees
// Every weapon has a tree: at these levels you pick one of two branch perks (the tree is fixed per weapon,
// so you can plan ahead in the Armoury). tier: which milestone it can appear at. fit(d): which weapons it suits.
const PERK_LEVELS = [3, 5, 8, 10];
const MAX_WLVL = 10; // weapons level to 10; Lv 10 is the mastery branch
const MULTI_KINDS = ['gun', 'lob', 'chain', 'mine', 'orbit', 'ring', 'strike', 'siphon', 'mimic', 'tether', 'prequel'];
const hasArea = d => !!(d.base.area || d.base.explode > 1 || d.base.aura || d.base.radius || d.style === 'flame' || d.kind === 'orbit');
const isProj = d => PROJ_KINDS.includes(d.kind);
const PERKS = {
  // Tier 1 (Lv 3): tune the gun.
  power:    { tier: 1, icon: 'PW', color: '#ff924c', name: 'Hot Load',        desc: '+40% damage.' },
  rapid:    { tier: 1, icon: 'RP', color: '#ffd23f', name: 'Hair Trigger',    desc: '25% faster cooldown and reload.' },
  deepmag:  { tier: 1, icon: 'DM', color: '#9fb3c8', name: 'Nappy Bag',   desc: '+60% magazine size.', fit: d => (d.base.mag || 1) > 1 },
  wide:     { tier: 1, icon: 'WD', color: '#c77dff', name: 'Wide Hips',       desc: '+35% area and +15% range.', fit: hasArea },
  pierce:   { tier: 1, icon: 'PC', color: '#e0fbff', name: 'Pointy Head',      desc: 'Shots pierce 2 more enemies.', fit: d => d.kind === 'gun' || d.kind === 'ring' },
  ricochet: { tier: 1, icon: 'RC', color: '#8dffc0', name: 'Trampoline Rounds',   desc: 'Shots bounce to 2 more targets.', fit: isProj },
  keen:     { tier: 1, icon: 'KN', color: '#fee440', name: 'Sharp Tongue',       desc: '+15% crit chance.' },
  chill:    { tier: 1, icon: 'CH', color: '#6fd8ff', name: 'Cold Shoulder',       desc: 'Hits chill: enemies slow by 35% for 1.5s.' },
  ignite:   { tier: 1, icon: 'IG', color: '#ff7a2f', name: 'Extra Spicy',      desc: 'Hits set enemies on fire for 25% of the hit per second.' },
  // Tier 2 (Lv 5): change how it plays.
  seek:     { tier: 2, icon: 'SK', color: '#d0a3ff', name: 'Homing Instinct',    desc: 'Shots home in on targets.', fit: isProj },
  split:    { tier: 2, icon: 'SL', color: '#ffd166', name: 'Cell Division',     desc: 'Shots burst into 3 shards on first hit.', fit: isProj },
  arc:      { tier: 2, icon: 'AR', color: '#ffe94a', name: 'Carpet Shock',   desc: '30% of hits arc to a nearby enemy for 50% damage.' },
  execute:  { tier: 2, icon: 'EX', color: '#ff4d6d', name: 'Kick Them While Down',        desc: '+60% damage to enemies under 35% health.' },
  venom:    { tier: 2, icon: 'VN', color: '#8dff4a', name: 'Toxic Relationship',    desc: 'Hits add a stacking poison.' },
  freeze:   { tier: 2, icon: 'FZ', color: '#bde0fe', name: 'Ice Queen',       desc: '12% of hits freeze non-boss enemies solid.' },
  blast:    { tier: 2, icon: 'BL', color: '#ff5a36', name: 'Special Delivery',         desc: 'Hits explode for 35% damage around the target.' },
  volley:   { tier: 2, icon: 'VL', color: '#48cae4', name: 'Plus One',    desc: '+1 projectile.', fit: d => MULTI_KINDS.includes(d.kind) },
  vamp:     { tier: 2, icon: 'VP', color: '#ff8fab', name: 'Bloodsucker',    desc: 'Hits heal you a little (within the lifesteal limit).' },
  giant:    { tier: 2, icon: 'GS', color: '#ffb347', name: 'Punching Up',        desc: '+100% damage to elites, bosses and rival champions.' },
  // Tier 3 (Lv 8): capstones.
  overdrive:{ tier: 3, icon: 'OD', color: '#ff3df2', name: 'Sugar Rush',       desc: '+75% damage.' },
  frenzy:   { tier: 3, icon: 'FR', color: '#ffd23f', name: 'Due Date Panic',          desc: '40% faster cooldown and reload.' },
  chainburst:{ tier: 3, icon: 'CB', color: '#ff5a36', name: 'Domino Effect', desc: 'Kills explode for 60% of the killing blow.' },
  slayer:   { tier: 3, icon: 'SY', color: '#ffb347', name: 'Giant Killer',   desc: '+150% damage to elites, bosses and rival champions.' },
  twin:     { tier: 3, icon: 'TW', color: '#48cae4', name: 'Twins!',      desc: '+2 projectiles.', fit: d => MULTI_KINDS.includes(d.kind) },
  storm:    { tier: 3, icon: 'ST', color: '#ffe94a', name: 'Electric Personality',     desc: '50% of hits arc to 2 nearby enemies for 60% damage.' },
  // Tier 4 (Lv 10): mastery.
  apex:     { tier: 4, icon: 'AX', color: '#ffffff', name: 'Final Form',       desc: '+100% damage and +20% crit chance.' },
  overclock:{ tier: 4, icon: 'OC', color: '#ffffff', name: 'Espresso Drip',       desc: '50% faster cooldown and reload, +50% magazine.' },
  legion:   { tier: 4, icon: 'LG', color: '#ffffff', name: 'Octuplets',          desc: '+3 projectiles.', fit: d => MULTI_KINDS.includes(d.kind) },
  lifeline: { tier: 4, icon: 'LF', color: '#ffffff', name: 'Umbilical Cord',        desc: 'Hits heal you (up to four times the usual lifesteal limit).' },
  executioner:{ tier: 4, icon: 'EX', color: '#ffffff', name: 'No Survivors',   desc: 'Non-boss enemies under 20% health die instantly when hit.' },
};

// ---------------------------------------------------------------- Swimming
// Your head turns at most turn rad/s (times traction), faster when you're nearly stopped.
// Sideways drift bleeds off at grip per second (times traction). Growth per level: +1.5% size.
const SWIM = { turn: 3.8, pivot: 1.6, grip: 4, growth: 0.015, hitGrowth: 0.0075 };

// ---------------------------------------------------------------- Terrain
// Things growing in the womb. solid: blocks bodies. shot: what happens to any projectile or bullet that hits it.
const OBSTACLES = {
  ridge:   { name: 'Cartilage Nodule', solid: true,  shot: 'bounce', n: 16, r: [45, 110], color: '#f2d0c9' },
  mito:    { name: 'Mitochondrion',    solid: true,  shot: 'absorb', n: 9,  r: [48, 72],  color: PAL.reward, charge: 45, burstR: 230 },
  acid:    { name: 'Acid Crypt',       solid: true,  shot: 'melt',   n: 9,  r: [40, 80],  color: PAL.danger, dps: 10 },
  cilia:   { name: 'Cilia Bed',        solid: false, shot: 'repel',  n: 8,  r: [95, 150], color: '#b0b0b0', push: 260 },
  current: { name: 'Tubal Current',    solid: false, shot: 'drift',  n: 7,  r: [120, 180], color: '#b0b0b0', push: 150 },
  slick:   { name: 'Lubricant Slick',  solid: false, shot: 'none',   n: 8,  r: [90, 150], color: '#c8b6ff', traction: 0.3 },
};

// ---------------------------------------------------------------- Rival champions
// Other would-be babies grow elsewhere on the map. First to level 60 to break the membrane wins.
// skill: how fast they grow. aggro: how keen they are to come and pick a fight with you.
const RIVALS = [
  { id: 'steve',  name: 'Big Steve',          color: '#ffb347', skill: 1.10, aggro: 0.6, title: 'Has been doing laps since the Tuesday before last' },
  { id: 'chad',   name: 'Chad Flagellum',     color: '#9ef01a', skill: 1.00, aggro: 0.9, title: 'Tail day, every day' },
  { id: 'wiggles',name: 'Professor Wiggles',  color: '#c77dff', skill: 1.15, aggro: 0.2, title: 'Holds a doctorate in swimming, self-awarded' },
  { id: 'zygo',   name: "Lil' Zygo",          color: '#ff5d8f', skill: 0.90, aggro: 0.7, title: 'Small, angry, surprisingly aerodynamic' },
  { id: 'kevin',  name: 'Kevin',              color: '#ffe94a', skill: 0.95, aggro: 0.4, title: 'Just Kevin' },
];
// finish: seconds for a skill-1.0 rival to reach EGG.level if nobody interferes.
const RIVAL = { finish: 840, hpBase: 250, duel: 14, speed: 78, zapR: 240, sight: 950, eggDps: 0.012, spawnR: 1700, pow: 1.1, huntFrom: 150 };

// ---------------------------------------------------------------- Chrono (time travel)
const CHRONO = { window: 4, snapEvery: 0.25, animDur: 1.1, energyPerCharge: 600, startCharges: 1, maxCharges: 2 };

// ---------------------------------------------------------------- Modifiers (slot into one weapon, 3 per weapon)
// Power (p) comes from the card's rarity. Picking a modifier a weapon already has boosts its power.
const MOD_SLOTS = 3;
const MOD_POWER = [1, 1.25, 1.6, 2.2];
const MOD_MAX_POWER = 3;
const MAX_ALLIES = 6;
const PROJ_KINDS = ['gun', 'siphon', 'mimic'];
const MODS = {
  seeking:   { name: 'Seeking',      icon: 'SE', color: '#d0a3ff', kinds: PROJ_KINDS, desc: p => `Shots hunt down targets (turn rate ${(3 + 2 * p).toFixed(1)})` },
  splitting: { name: 'Splitting',    icon: 'SP', color: '#ffd166', kinds: PROJ_KINDS, desc: p => `On first hit, shots split into ${2 + Math.round(p)} shards at 45% damage` },
  orbiting:  { name: 'Orbiting',     icon: 'OR', color: '#8dffc0', kinds: PROJ_KINDS, desc: p => `Shots circle you for ${(1.2 * p).toFixed(1)}s, eating enemy bullets, then launch` },
  growing:   { name: 'Growing',      icon: 'GW', color: '#8ac926', kinds: PROJ_KINDS, desc: p => `Shots swell in flight: triple size and up to +${Math.round(100 * p)}% damage` },
  boomerang: { name: 'Boomerang',    icon: 'BM', color: '#f1f1f1', kinds: PROJ_KINDS, desc: () => 'Shots fly out and come back, hitting everything twice' },
  ricochet:  { name: 'Ricochet',     icon: 'RI', color: '#a0c4ff', kinds: PROJ_KINDS, desc: p => `+${1 + Math.round(p)} bounces between enemies` },
  freezing:  { name: 'Freezing',     icon: 'FZ', color: '#6fd8ff', desc: p => `${Math.round(18 * p)}% chance per hit to freeze the target solid` },
  exploding: { name: 'Exploding',    icon: 'EX', color: '#ff7a2f', desc: p => `Hits explode for ${Math.round(30 * p)}% damage in a small blast` },
  mindctrl:  { name: 'Mind Control', icon: 'MC', color: '#ff8fab', desc: p => `${(5 * p).toFixed(0)}% chance per hit to make a monster fight for you for ${Math.round(6 * p)}s (max ${MAX_ALLIES} allies)` },
  elemental: { name: 'Element Swap', icon: 'EL', color: '#c77dff', desc: () => 'Converts this weapon to a new element' },
  shrapnel:  { name: 'Shrapnel',     icon: 'SH', color: '#e9c46a', desc: () => 'Kills burst into 3 shards at 40% damage' },
  // The Modifier Forge.
  chaining:  { name: 'Chaining',     icon: 'CN', color: '#eee36a', desc: p => `${Math.round(25 * p)}% of hits chain to another enemy for 50% damage` },
  pulsing:   { name: 'Pulsing',      icon: 'PU', color: '#cfe3ff', kinds: PROJ_KINDS, desc: p => `Shots pulse every 0.45s, hitting everything close by for ${Math.round(25 * p)}% damage` },
  magnetic:  { name: 'Magnetic',     icon: 'MG', color: '#b0b0b0', kinds: PROJ_KINDS, desc: p => `Shots drag monsters within ${Math.round(70 * p)} units into their path` },
  delayed:   { name: 'Delayed',      icon: 'DL', color: '#b0b0b0', kinds: PROJ_KINDS, desc: p => `Shots hang for a moment, then launch 60% faster for +${Math.round(30 * p)}% damage` },
  mirror:    { name: 'Mirror',       icon: 'MR', color: '#b0b0b0', kinds: PROJ_KINDS, desc: p => `Every shot has a twin fired the opposite way at ${Math.round(50 * p)}% damage` },
};
// Duo combos: two specific modifiers on the same weapon unlock a named bonus.
const DUOS = [
  { a: 'seeking',   b: 'splitting', name: 'Cluster Hunter', desc: 'Split shards home in too.' },
  { a: 'freezing',  b: 'exploding', name: 'Cryoblast',      desc: 'Explosions freeze whatever they hit.' },
  { a: 'orbiting',  b: 'pulsing',   name: 'Halo',           desc: 'Pulses come twice as often and hit twice as hard.' },
  { a: 'boomerang', b: 'growing',   name: 'Snowball',       desc: 'Shots grow twice as much on the way out and back.' },
  { a: 'ricochet',  b: 'chaining',  name: 'Pinball Wizard', desc: 'Chains jump to 3 targets.' },
  { a: 'mindctrl',  b: 'magnetic',  name: 'Pied Piper',     desc: 'Mind-controlled allies last twice as long.' },
  { a: 'mirror',    b: 'splitting', name: 'Kaleidoscope',   desc: 'Mirrored twins split into twice as many shards.' },
  { a: 'delayed',   b: 'exploding', name: 'Time Bomb',      desc: 'Delayed shots explode as they launch.' },
];

// ---------------------------------------------------------------- Cursed loot cards
const CURSES = [
  { id: 'glass', name: 'Glass Cannon Deluxe', boon: 'x1.8 damage for everything', bane: 'Max HP halved',
    apply: (P, G) => { P.might *= 1.8; P.maxHp = Math.max(30, Math.round(P.maxHp / 2)); G.player.hp = Math.min(G.player.hp, P.maxHp); } },
  { id: 'speed', name: "Speedrunner's Regret", boon: '+50% fire rate', bane: 'Enemy bullets 20% faster', apply: P => { P.haste += 0.5; P.bulletSpeed *= 1.2; } },
  { id: 'hoard', name: "Hoarder's Bargain", boon: 'Double scrap, double viewers', bane: 'Pickup range halved', apply: P => { P.scrap *= 2; P.viewers *= 2; P.magnet *= 0.5; } },
  { id: 'crowd', name: 'Crowd Pleaser', boon: '+50% XP and viewers', bane: '30% more enemies', apply: P => { P.xp += 0.5; P.viewers *= 1.5; P.spawnMult *= 1.3; } },
  { id: 'paradox', name: 'Paradox Addict', boon: '+2 max Rewind charges, all refilled now', bane: 'All healing halved', apply: (P, G) => { G.chrono.max += 2; G.chrono.charges = G.chrono.max; P.healMult *= 0.5; } },
  { id: 'naked', name: 'Clothing Optional', boon: '+25% move speed, +20% dodge', bane: 'Armour is zero. Forever.', apply: P => { P.speed += 0.25; P.dodge = Math.min(0.6, P.dodge + 0.2); P.noArmour = true; } },
];

// ---------------------------------------------------------------- The Show: announcer, achievements, viewers, sponsors
// Original comedy writing for Storm Directive's sardonic game-show host, "the System".
const GACHA_TIERS = [
  { name: 'BRONZE MAG', mult: 0.7, color: '#cd8a4a', w: 55 },
  { name: 'SILVER MAG', mult: 1.1, color: '#c9d6e3', w: 28 },
  { name: 'GOLD MAG', mult: 1.8, color: '#ffd23f', w: 13 },
  { name: 'LEGENDARY MAG', mult: 3, color: '#ff3df2', w: 4 },
];
const BOSS_TITLES = { queen: 'Eater of Hopefuls', colossus: 'Head of Border Control', voideye: 'Unblinking Critic of Your Genome' };
const SPONSORS = [
  "Grundle's Discount Ordnance", "Madame Vex's Totally Legal Potions", 'The Committee for Unnecessary Explosions',
  "Big Barry's Scrap and Salvage", 'Glorp Cola: It Glows For A Reason', 'The Ancient Order of Slightly Sticky Relics',
  "Dr Fizzwick's Regrettable Medicines", 'Hovercrab Insurance: We Probably Cover That',
];
const SYSTEM_LINES = {
  start: [
    'Welcome, Spermy. Four hundred million of you entered. One gets to become a person. No pressure.',
    'Today\'s prize: existence. Today\'s competition: literally everyone you arrived with.',
    'Reminder: you swim yourself. Your job is to make bad decisions in the menus.',
    'Good news: there is an egg. Bad news: so is everyone else\'s plan.',
  ],
  level: [
    'Level up! You are growing. Please stop sprouting weapons from your tail, it upsets the viewers.',
    'Another level. The egg has noticed you. The egg is not impressed yet.',
    'Level up. Please enjoy this complimentary box of violence.',
    'Congratulations on your promotion from "tadpole" to "slightly angrier tadpole".',
  ],
  boss: [
    'It has read your genome and is unimpressed.',
    'It has been told you insulted its mother. You did not. We did. On your behalf.',
    'Please try to die slowly. The viewers paid for the full episode.',
  ],
  lowhp: [
    'Your health is low. Have you tried not getting absorbed?',
    'Vital signs: concerning. Viewer engagement: excellent.',
    'The immune system is winning. The immune system always thinks it is winning.',
  ],
  rewind: [
    'Time has been rewound. Biology has filed a formal complaint.',
    'Rewind successful. Your future self is now an unpaid intern.',
    'You swam backwards through time. Most swimmers can barely swim forwards.',
  ],
  fusion: ['Fusion complete. Two weapons became one. That is, ironically, the theme of the show.', 'Fusion complete. It violates at least four treaties and one textbook.'],
  cursed: ['You took the cursed card. We are not angry. We are just disappointed. And delighted.', 'Bold. Stupid, but bold. Very on-brand for a swimmer.'],
  surge: ['Immune Surge! The host has noticed you. Everything hits harder now. Please remain calm and panic.'],
  idle: [
    'The egg is right there. Just saying.',
    'Fun fact: most swimmers never get past the first minute. Just saying.',
    'A reminder that screaming does not affect gameplay, but we do record it.',
    'Viewer poll: 61% think you will be eaten by a Macrophage. Prove them right.',
    'You are doing great! This message is automated and applies to all four hundred million swimmers equally.',
    'Current odds of becoming a person: low. Current odds of being a snack: excellent.',
  ],
  death: [
    'Swimmer absorbed. Your DNA will be recycled into something more useful, like a toenail.',
    'You have been eaten by the immune system. It was nothing personal. It was entirely personal.',
    'And that is the show! Another swimmer gets to be a person. It was not you.',
    'Cause of death: optimism.',
  ],
  gacha: ['Legendary magazine! The house always wins. Except, apparently, now.'],
  mimic: ['Pattern copied. The original owner has been absorbed and cannot sue.'],
  grudge: ['Grudge settled. Therapy was cheaper, but this was faster.'],
  eggReady: ['The egg has decided you are big enough. Go and break in. Knocking is optional.', 'The egg is ready. Its membrane is not. Shoot it until it agrees.'],
  rivalLevel: ['{n} just hit level {l}. They look insufferable about it.', '{n} is level {l}. The Committee would like to remind you that this is a race.'],
  rivalEgg: ['{n} has reached the egg and is headbutting the membrane. If it breaks for them, you lose. Go and have words.', '{n} is knocking on the egg. Politely, with their face. Stop them.'],
  rivalDead: ['{n} has been eliminated. {k}', 'Farewell, {n}. {k}'],
  rivalWin: ['{n} got there first. Congratulations to {n}. You are now a statistic.'],
  amoebaHuge: ['An amoeba has eaten {n} of its colleagues and is now the size of a small opinion. Kill it before it becomes a large one.', 'Something spongy has had {n} meals and is getting ideas. Deal with it.'],
  born: ['Congratulations! It\'s you! Everyone else can go home. Everyone else is, technically, going nowhere.'],
  slot: ['You grew a new weapon mount. Biology is not supposed to work like this. Please enjoy it anyway.', 'Extra weapon slot unlocked. Evolution took millions of years. You took fifteen levels.'],
};
const NO_REWARD = [
  'Reward: a sense of accomplishment. It is non-refundable.',
  'Reward: nothing. We are not made of money.',
  'Reward: our respect. It has no resale value.',
  'Reward: exposure. You know how it is.',
];
const CARD_QUIPS = [
  'The System recommends this one. The System is often wrong.',
  'Viewers voted this "most likely to end in tears".',
  'A previous contestant picked this. We don\'t talk about them.',
  'Sponsored content. Probably.',
  'This one comes with a free trial of hope.',
  'Our focus group loved it. The focus group has since dissolved.',
];
const ACHIEVEMENTS = {
  firstblood: { name: "Baby's First Homicide", desc: 'Killed a rival. Only 399,999,999 to go.', reward: 'none' },
  born:       { name: "Congratulations, It's You", desc: 'Broke into the egg and got yourself born. Please enjoy the next eighty years.', reward: 'none' },
  amoeba:     { name: 'Portion Control', desc: 'Let an amoeba eat so much it made the news.', reward: 'none' },
  bigamoeba:  { name: 'Diet Plan', desc: 'Killed an amoeba bigger than a boss.', reward: 'box' },
  rivalkill:  { name: 'Survival of the Fittest', desc: 'Eliminated a rival champion personally. Biology is a contact sport.', reward: 'box' },
  allrivals:  { name: 'Only Child', desc: 'Every rival champion is gone. The egg only has one option now.', reward: 'reroll' },
  eggready:   { name: 'Big Enough', desc: 'Grew strong enough for the egg to take you seriously.', reward: 'heal' },
  slot:       { name: 'Extra Limb', desc: 'Grew an extra weapon slot. The textbooks will need updating.', reward: 'none' },
  kills100:   { name: 'Pest Control', desc: '100 kills. The exterminators\' union has filed a complaint.', reward: 'reroll' },
  kills1000:  { name: 'Statistically Significant', desc: '1,000 kills. You are now a demographic.', reward: 'box' },
  kills5000:  { name: 'Extinction Event', desc: '5,000 kills. Several species have asked you to stop.', reward: 'bossbox' },
  firstloot:  { name: 'Unboxing Influencer', desc: 'Opened your first loot box. Please like and subscribe.', reward: 'none' },
  fusion:     { name: 'Frankenweapon', desc: 'Fused two weapons. It is alive. It is also on fire.', reward: 'reroll' },
  rewind:     { name: 'Undo Button Enthusiast', desc: 'Rewound time. Causality has been notified.', reward: 'none' },
  autorewind: { name: 'Not Today, Death', desc: 'Died, then un-died. Our lawyers are looking into it.', reward: 'heal' },
  boss:       { name: 'Middle Management Removed', desc: 'Killed a boss. Someone will be promoted to replace it.', reward: 'none' },
  reactions:  { name: 'Mad Scientist', desc: 'Triggered 50 elemental reactions. Safety goggles were optional.', reward: 'reroll' },
  friendly:   { name: 'Let Them Fight', desc: 'A Bomber killed another monster. Teamwork!', reward: 'none' },
  cursed:     { name: 'Bad Decision Maker', desc: 'Took a cursed card. We knew you would.', reward: 'none' },
  modded:     { name: 'Aftermarket Parts', desc: 'Installed a modifier. The warranty is now fully void.', reward: 'none' },
  fullmods:   { name: 'Pimp My Death Machine', desc: 'Filled all three modifier slots on one weapon. Tasteful.', reward: 'box' },
  mindctrl:   { name: 'Friends Forever', desc: 'Mind-controlled a monster. It was not consulted.', reward: 'none' },
  recycle:    { name: 'Circular Economy', desc: 'Recycled a weapon in the Armoury. Very eco. Very violent.', reward: 'none' },
  grudge:     { name: 'Petty', desc: 'Killed the thing that hurt you with the Family Grudge. Worth it.', reward: 'none' },
  broke:      { name: 'Financially Ruined', desc: 'Ran the Child Benefit Cannon dry. Please consult a debt counsellor.', reward: 'scrap' },
  gachagold:  { name: 'Gambling Problem', desc: 'Rolled a Legendary magazine. Do not tell your mother.', reward: 'none' },
  parasite:   { name: 'Landlord of Flesh', desc: 'A corpse became your turret. Rent is due Tuesday.', reward: 'none' },
  mimic:      { name: 'Identity Theft', desc: 'Stole a monster\'s attack pattern. It will be pressing charges.', reward: 'none' },
  overkill:   { name: 'Excessive Force', desc: 'Dealt 1,000 overkill damage in one hit. The review board is concerned.', reward: 'none' },
  lastword:   { name: 'The Last Word', desc: 'Killed something with the final round of a magazine. Dramatic.', reward: 'none' },
  spoilers:   { name: 'Spoilers', desc: 'Killed something before the shell had even been fired.', reward: 'none' },
  tethered:   { name: 'Forced Proximity', desc: 'Slammed two tethered monsters together. They did not consent.', reward: 'none' },
  siphoned:   { name: 'Return to Sender', desc: 'Absorbed 200 enemy bullets. The postal service is in awe.', reward: 'reroll' },
  echokill:   { name: 'Time Paradox Murder', desc: 'Your future self got a kill. Who gets the XP? You do. Don\'t ask.', reward: 'none' },
  survive5:   { name: 'Still Here?', desc: 'Survived 5 minutes. The producers are surprised.', reward: 'box' },
  survive10:  { name: 'Contractually Obligated', desc: 'Survived 10 minutes. We have to keep filming now.', reward: 'box' },
  surge:      { name: 'Ratings Spike', desc: 'Reached the Storm Surge. The audience is thrilled you will die soon.', reward: 'none' },
  viewers1m:  { name: 'Celebrity', desc: 'One million viewers. Your agent has several questions.', reward: 'box' },
  lowhp:      { name: 'Flesh Wound', desc: 'Survived a hit with under 5% HP. The medic has fainted.', reward: 'heal' },
  sponsor:    { name: 'Sold Out', desc: 'Accepted a sponsor gift. Integrity was never on the table.', reward: 'none' },
};
const VIEWER_MILESTONES = [10e3, 50e3, 100e3, 250e3, 500e3, 1e6, 2.5e6, 5e6, 1e7, 2.5e7, 5e7];

// Everything you fire is yours, so it's all GFP green.
for (const d of Object.values(WEAPONS).concat(Object.values(SPELLS))) d.color = PAL.you;
