'use strict';
// Storm Directive - game data: elements, weapons, spells, merges, passives, enemies, bosses, directives.

const ELEMENTS = {
  phys:   { name: 'Kinetic', color: '#e8eef8' },
  fire:   { name: 'Fire',    color: '#ff7a2f' },
  ice:    { name: 'Frost',   color: '#6fd8ff' },
  shock:  { name: 'Shock',   color: '#ffe94a' },
  poison: { name: 'Toxic',   color: '#8dff4a' },
  arcane: { name: 'Arcane',  color: '#c77dff' },
};

// Targeting directives. Each weapon/spell runs one of these.
const DIRECTIVES = [
  { id: 'nearest',   name: 'NEAREST',        short: 'NEAR' },
  { id: 'strongest', name: 'STRONGEST',      short: 'STRG' },
  { id: 'weakest',   name: 'WEAKEST',        short: 'WEAK' },
  { id: 'lowhp',     name: 'LOWEST HEALTH',  short: 'LOW HP' },
  { id: 'highhp',    name: 'HIGHEST HEALTH', short: 'HI HP' },
  { id: 'armour',    name: 'HIGHEST ARMOUR', short: 'ARMR' },
  { id: 'fastest',   name: 'FASTEST',        short: 'FAST' },
  { id: 'furthest',  name: 'FURTHEST',       short: 'FAR' },
  { id: 'cluster',   name: 'DENSEST CLUSTER', short: 'CLSTR' },
  { id: 'elite',     name: 'ELITES & BOSSES', short: 'ELITE' },
  { id: 'shooters',  name: 'SHOOTERS FIRST', short: 'SHOOT' },
  { id: 'random',    name: 'RANDOM',         short: 'RAND' },
];

// Movement (autorun) directives.
const MOVE_DIRECTIVES = [
  { id: 'kite',    name: 'KITE',    desc: 'Keep distance from threats, dodge bullets' },
  { id: 'collect', name: 'COLLECT', desc: 'Hoover up XP and power-ups' },
  { id: 'orbit',   name: 'ORBIT',   desc: 'Circle around the horde' },
  { id: 'hunt',    name: 'HUNT',    desc: 'Close in on the primary target' },
  { id: 'hold',    name: 'HOLD',    desc: 'Stand ground, only dodge bullets' },
];

// Level bonus keys: count, pierce, chain, bounce (additive); dmg, area, dur (additive %); cd (negative = faster).
const WEAPONS = {
  blaster: { name: 'Blaster', icon: 'BL', elem: 'phys', kind: 'gun', color: '#e8f0ff', dir: 'nearest',
    desc: 'Reliable sidearm. Accurate single shots.',
    base: { dmg: 10, cd: 0.3, mag: 12, reload: 1.1, count: 1, spread: 0.04, speed: 640, pierce: 0, range: 430, size: 4 },
    lv: { 3: { pierce: 1 }, 5: { count: 1 }, 7: { dmg: 0.3 } } },
  smg: { name: 'Storm SMG', icon: 'SM', elem: 'phys', kind: 'gun', color: '#cfd8ff', dir: 'nearest',
    desc: 'Sprays a hail of light rounds. Big magazine, long reload.',
    base: { dmg: 4.5, cd: 0.075, mag: 36, reload: 1.7, count: 1, spread: 0.2, speed: 580, pierce: 0, range: 370, size: 3 },
    lv: { 3: { cd: -0.15 }, 5: { pierce: 1 }, 7: { count: 1 } } },
  shotgun: { name: 'Scattergun', icon: 'SG', elem: 'phys', kind: 'gun', color: '#ffd6a5', dir: 'nearest',
    desc: 'Close-range pellet burst with knockback.',
    base: { dmg: 8, cd: 0.75, mag: 4, reload: 1.6, count: 6, spread: 0.55, speed: 540, pierce: 0, range: 270, size: 3.5, knock: 70 },
    lv: { 3: { count: 2 }, 5: { pierce: 1 }, 7: { count: 3 } } },
  railgun: { name: 'Railgun', icon: 'RG', elem: 'phys', kind: 'gun', color: '#9ef0ff', dir: 'armour', style: 'rail',
    desc: 'Hypersonic slug. Pierces everything and shreds armour.',
    base: { dmg: 42, cd: 1.3, mag: 3, reload: 2.2, count: 1, spread: 0.05, speed: 1700, pierce: 99, range: 720, size: 3, shred: 3 },
    lv: { 3: { shred: 2 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  rocket: { name: 'Rocket Pod', icon: 'RK', elem: 'fire', kind: 'gun', color: '#ffb347', dir: 'cluster', style: 'rocket',
    desc: 'Explosive rockets that ignite the blast zone.',
    base: { dmg: 24, cd: 0.55, mag: 2, reload: 2.4, count: 1, spread: 0.1, speed: 400, pierce: 0, range: 500, size: 5, explode: 62 },
    lv: { 3: { area: 0.25 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  flamer: { name: 'Flamer', icon: 'FL', elem: 'fire', kind: 'gun', color: '#ff7a2f', dir: 'nearest', style: 'flame',
    desc: 'Short-range cone of fire. Every lick burns.',
    base: { dmg: 3.2, cd: 0.05, mag: 50, reload: 2.1, count: 2, spread: 0.45, speed: 310, pierce: 99, range: 200, size: 7 },
    lv: { 3: { area: 0.3 }, 5: { dmg: 0.3 }, 7: { count: 1 } } },
  frost: { name: 'Frost Lance', icon: 'FR', elem: 'ice', kind: 'gun', color: '#6fd8ff', dir: 'fastest', style: 'shard',
    desc: 'Piercing ice shards that chill and freeze.',
    base: { dmg: 15, cd: 0.6, mag: 5, reload: 1.5, count: 1, spread: 0.08, speed: 540, pierce: 3, range: 460, size: 5 },
    lv: { 3: { count: 1 }, 5: { pierce: 3 }, 7: { count: 2 } } },
  tesla: { name: 'Tesla Coil', icon: 'TC', elem: 'shock', kind: 'chain', color: '#ffe94a', dir: 'cluster',
    desc: 'Instant lightning that arcs between enemies.',
    base: { dmg: 13, cd: 0.7, mag: 6, reload: 1.8, count: 1, chain: 3, range: 330, jump: 140 },
    lv: { 3: { chain: 2 }, 5: { count: 1 }, 7: { chain: 3 } } },
  venom: { name: 'Venom Spitter', icon: 'VS', elem: 'poison', kind: 'lob', color: '#8dff4a', dir: 'cluster',
    desc: 'Lobs acid globs that leave toxic puddles.',
    base: { dmg: 9, cd: 0.9, mag: 4, reload: 1.8, count: 1, spread: 40, range: 390, area: 55, dur: 3, flight: 0.6 },
    lv: { 3: { dur: 0.5 }, 5: { count: 1 }, 7: { area: 0.4 } } },
  glaive: { name: 'Glaive', icon: 'GL', elem: 'phys', kind: 'gun', color: '#f1f1f1', dir: 'furthest', style: 'glaive',
    desc: 'Spinning blade that flies out and returns.',
    base: { dmg: 15, cd: 1.0, mag: 2, reload: 1.3, count: 1, spread: 0.3, speed: 430, pierce: 99, range: 330, size: 10, boomerang: 1 },
    lv: { 3: { count: 1 }, 5: { dmg: 0.3 }, 7: { count: 1 } } },
  orbit: { name: 'Orbital Blades', icon: 'OB', elem: 'arcane', kind: 'orbit', color: '#c77dff', dir: 'nearest',
    desc: 'Arcane blades orbit you. Active, then recharge.',
    base: { dmg: 16, count: 3, dur: 4.5, reload: 2.2, radius: 72, spin: 3.6, size: 10, range: 100 },
    lv: { 3: { count: 1 }, 5: { area: 0.3 }, 7: { count: 2 } } },
  prism: { name: 'Prism Beam', icon: 'PB', elem: 'arcane', kind: 'beam', color: '#e0aaff', dir: 'strongest',
    desc: 'Channelled beam that burns through a line of foes.',
    base: { dmg: 32, cd: 1.7, mag: 3, reload: 2.2, count: 1, dur: 1.2, range: 390, size: 6 },
    lv: { 3: { dur: 0.35 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  mines: { name: 'Mine Layer', icon: 'ML', elem: 'fire', kind: 'mine', color: '#ff9f1c', dir: 'nearest',
    desc: 'Drops proximity mines in your wake.',
    base: { dmg: 32, cd: 0.7, mag: 5, reload: 2.4, count: 1, explode: 72, life: 14, range: 600 },
    lv: { 3: { count: 1 }, 5: { area: 0.3 }, 7: { dmg: 0.5 } } },
  seeker: { name: 'Seeker Swarm', icon: 'SS', elem: 'arcane', kind: 'gun', color: '#d0a3ff', dir: 'weakest', style: 'missile',
    desc: 'Homing micro-missiles that never miss.',
    base: { dmg: 9, cd: 0.45, mag: 6, reload: 2.0, count: 2, spread: 1.2, speed: 320, pierce: 0, range: 500, size: 4, homing: 5 },
    lv: { 3: { count: 1 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  gatling: { name: 'Gatling', icon: 'GT', elem: 'phys', kind: 'gun', color: '#ffe8a3', dir: 'nearest', spinup: 1,
    desc: 'Spins up to a terrifying fire rate. Huge belt.',
    base: { dmg: 5.5, cd: 0.14, mag: 120, reload: 3.2, count: 1, spread: 0.13, speed: 720, pierce: 0, range: 450, size: 3 },
    lv: { 3: { pierce: 1 }, 5: { count: 1 }, 7: { dmg: 0.3 } } },
  drone: { name: 'Attack Drone', icon: 'DR', elem: 'shock', kind: 'gun', color: '#fff275', dir: 'lowhp', drones: 1,
    desc: 'Drones hover beside you and fire shock bolts.',
    base: { dmg: 8, cd: 0.45, mag: 10, reload: 1.5, count: 1, spread: 0.05, speed: 620, pierce: 0, range: 420, size: 3.5 },
    lv: { 3: { count: 1 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  ricochet: { name: 'Ricochet Disc', icon: 'RD', elem: 'phys', kind: 'gun', color: '#a0c4ff', dir: 'nearest', style: 'disc',
    desc: 'Discs bounce from enemy to enemy.',
    base: { dmg: 13, cd: 0.8, mag: 3, reload: 1.5, count: 1, spread: 0.1, speed: 500, pierce: 0, range: 420, size: 6, bounce: 3 },
    lv: { 3: { bounce: 2 }, 5: { count: 1 }, 7: { bounce: 3 } } },
  mortar: { name: 'Mortar', icon: 'MR', elem: 'fire', kind: 'lob', color: '#ff6b35', dir: 'cluster',
    desc: 'Slow, heavy shells with a huge blast.',
    base: { dmg: 42, cd: 1.6, mag: 2, reload: 2.5, count: 1, spread: 30, range: 540, area: 82, flight: 1.0, explode: 1 },
    lv: { 3: { area: 0.25 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  arbalest: { name: 'Arbalest', icon: 'AB', elem: 'phys', kind: 'gun', color: '#d4a373', dir: 'strongest', style: 'bolt',
    desc: 'Heavy bolts. Massive knockback, light armour shred.',
    base: { dmg: 24, cd: 0.9, mag: 4, reload: 1.6, count: 1, spread: 0.05, speed: 820, pierce: 2, range: 540, size: 4, knock: 220, shred: 1 },
    lv: { 3: { pierce: 2 }, 5: { count: 1 }, 7: { dmg: 0.4 } } },
  void: { name: 'Void Orb', icon: 'VO', elem: 'arcane', kind: 'gun', color: '#7b2cbf', dir: 'cluster', style: 'void',
    desc: 'Slow orb that drags enemies into its maw.',
    base: { dmg: 7, cd: 1.8, mag: 2, reload: 2.5, count: 1, spread: 0.2, speed: 115, pierce: 99, range: 400, size: 15, aura: 70, pull: 90 },
    lv: { 3: { area: 0.3 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
  needler: { name: 'Needler', icon: 'ND', elem: 'poison', kind: 'gun', color: '#b8f35a', dir: 'highhp', style: 'needle',
    desc: 'Rapid toxic needles. Poison stacks up.',
    base: { dmg: 3.5, cd: 0.1, mag: 30, reload: 1.6, count: 1, spread: 0.1, speed: 680, pierce: 0, range: 410, size: 2.5 },
    lv: { 3: { count: 1 }, 5: { pierce: 1 }, 7: { cd: -0.2 } } },
  hailstorm: { name: 'Hailstorm', icon: 'HS', elem: 'ice', kind: 'lob', color: '#a2d2ff', dir: 'cluster',
    desc: 'Rains ice chunks around the target.',
    base: { dmg: 11, cd: 1.4, mag: 2, reload: 2.0, count: 5, spread: 90, range: 460, area: 36, flight: 0.7, explode: 1 },
    lv: { 3: { count: 2 }, 5: { area: 0.3 }, 7: { count: 3 } } },

  // ---- Merged weapons (not in the random pool; created by fusing two maxed-enough weapons) ----
  steam: { name: 'Steam Cannon', icon: 'ST', elem: 'fire', elem2: 'ice', kind: 'gun', color: '#ffc6ff', dir: 'nearest', style: 'flame', merged: 1,
    desc: 'Scalding fire-and-frost cone. Triggers reactions constantly.',
    base: { dmg: 8, cd: 0.055, mag: 70, reload: 1.9, count: 3, spread: 0.5, speed: 380, pierce: 99, range: 250, size: 9 },
    lv: { 5: { area: 0.3 }, 7: { count: 1 } } },
  thunderbuck: { name: 'Thunder Buckshot', icon: 'TB', elem: 'shock', kind: 'gun', color: '#fff3b0', dir: 'nearest', merged: 1,
    desc: 'Each pellet detonates into chain lightning.',
    base: { dmg: 11, cd: 0.7, mag: 5, reload: 1.4, count: 8, spread: 0.6, speed: 580, pierce: 0, range: 310, size: 4, chainHit: 2, knock: 60 },
    lv: { 5: { count: 2 }, 7: { dmg: 0.3 } } },
  annihilator: { name: 'Annihilator', icon: 'AN', elem: 'arcane', kind: 'beam', color: '#f72585', dir: 'strongest', merged: 1,
    desc: 'Colossal armour-shredding beam across the screen.',
    base: { dmg: 130, cd: 2.4, mag: 2, reload: 2.5, count: 1, dur: 1.5, range: 820, size: 14, shred: 5 },
    lv: { 5: { dur: 0.4 }, 7: { count: 1 } } },
  hydra: { name: 'Hydra Barrage', icon: 'HB', elem: 'fire', kind: 'gun', color: '#ff9e00', dir: 'elite', style: 'rocket', merged: 1,
    desc: 'Volleys of homing explosive rockets.',
    base: { dmg: 22, cd: 0.5, mag: 4, reload: 2.2, count: 4, spread: 1.6, speed: 350, pierce: 0, range: 540, size: 5, homing: 6, explode: 58 },
    lv: { 5: { count: 2 }, 7: { area: 0.3 } } },
  cyclone: { name: 'Cyclone Glaives', icon: 'CG', elem: 'phys', kind: 'orbit', color: '#ffffff', dir: 'nearest', merged: 1,
    desc: 'Six glaives pulse outward and back in a storm.',
    base: { dmg: 30, count: 6, dur: 6, reload: 1.4, radius: 70, spin: 4.2, size: 12, range: 170, pulse: 1 },
    lv: { 5: { count: 2 }, 7: { dmg: 0.4 } } },
  pinball: { name: 'Pinball Magnum', icon: 'PM', elem: 'phys', kind: 'gun', color: '#caffbf', dir: 'nearest', style: 'disc', merged: 1,
    desc: 'Magnum rounds that ricochet 6 times. Crits often.',
    base: { dmg: 22, cd: 0.35, mag: 8, reload: 1.2, count: 1, spread: 0.05, speed: 720, pierce: 0, range: 470, size: 5, bounce: 6, critBonus: 0.2 },
    lv: { 5: { bounce: 3 }, 7: { count: 1 } } },
  plague: { name: 'Plague Mortar', icon: 'PL', elem: 'poison', kind: 'lob', color: '#70e000', dir: 'cluster', merged: 1,
    desc: 'Toxic shells: huge blast plus a lingering plague pool.',
    base: { dmg: 46, cd: 1.4, mag: 3, reload: 2.2, count: 1, spread: 40, range: 540, area: 96, dur: 5, flight: 0.9, explode: 1 },
    lv: { 5: { count: 1 }, 7: { area: 0.3 } } },
  singularity: { name: 'Singularity Mines', icon: 'SI', elem: 'arcane', kind: 'mine', color: '#9d4edd', dir: 'nearest', merged: 1,
    desc: 'Mines open a black hole, then detonate.',
    base: { dmg: 55, cd: 0.8, mag: 4, reload: 2.2, count: 1, explode: 95, life: 16, range: 600, singularity: 1 },
    lv: { 5: { count: 1 }, 7: { dmg: 0.5 } } },
  hive: { name: 'Drone Hive', icon: 'DH', elem: 'shock', kind: 'gun', color: '#ffee32', dir: 'lowhp', drones: 1, merged: 1,
    desc: 'Four drones with SMG fire rates.',
    base: { dmg: 6.5, cd: 0.12, mag: 40, reload: 1.8, count: 4, spread: 0.1, speed: 640, pierce: 0, range: 440, size: 3 },
    lv: { 5: { count: 2 }, 7: { dmg: 0.4 } } },
  siege: { name: 'Siege Repeater', icon: 'SR', elem: 'phys', kind: 'gun', color: '#e9c46a', dir: 'armour', style: 'bolt', spinup: 1, merged: 1,
    desc: 'Automatic heavy bolts. Pierce, shred, knockback.',
    base: { dmg: 17, cd: 0.15, mag: 60, reload: 2.4, count: 1, spread: 0.08, speed: 860, pierce: 4, range: 560, size: 4, knock: 140, shred: 2 },
    lv: { 5: { pierce: 3 }, 7: { count: 1 } } },
  zero: { name: 'Absolute Zero', icon: 'AZ', elem: 'ice', kind: 'lob', color: '#caf0f8', dir: 'cluster', merged: 1,
    desc: 'Ice meteors that flash-freeze everything hit.',
    base: { dmg: 18, cd: 1.3, mag: 3, reload: 1.8, count: 8, spread: 110, range: 500, area: 48, flight: 0.7, explode: 1, freezeHit: 1 },
    lv: { 5: { count: 3 }, 7: { dmg: 0.4 } } },
  neuro: { name: 'Neurotoxin Arc', icon: 'NA', elem: 'poison', elem2: 'shock', kind: 'chain', color: '#d9ed92', dir: 'cluster', merged: 1,
    desc: 'Toxic lightning. Every arc spreads plague.',
    base: { dmg: 9, cd: 0.25, mag: 12, reload: 1.6, count: 1, chain: 6, range: 360, jump: 150 },
    lv: { 5: { chain: 3 }, 7: { count: 1 } } },
};

const MERGES = [
  { a: 'flamer',  b: 'frost',     out: 'steam' },
  { a: 'shotgun', b: 'tesla',     out: 'thunderbuck' },
  { a: 'railgun', b: 'prism',     out: 'annihilator' },
  { a: 'rocket',  b: 'seeker',    out: 'hydra' },
  { a: 'glaive',  b: 'orbit',     out: 'cyclone' },
  { a: 'blaster', b: 'ricochet',  out: 'pinball' },
  { a: 'venom',   b: 'mortar',    out: 'plague' },
  { a: 'mines',   b: 'void',      out: 'singularity' },
  { a: 'drone',   b: 'smg',       out: 'hive' },
  { a: 'arbalest', b: 'gatling',  out: 'siege' },
  { a: 'frost',   b: 'hailstorm', out: 'zero' },
  { a: 'needler', b: 'tesla',     out: 'neuro' },
];
const MERGE_MIN_LEVEL = 4;

// Spells: autocast on cooldown, occupy spell slots.
const SPELLS = {
  meteor: { name: 'Meteor', icon: 'ME', elem: 'fire', kind: 'strike', color: '#ff5400', dir: 'cluster',
    desc: 'Calls a meteor on the target. Leaves burning ground.',
    base: { dmg: 65, cd: 5, count: 1, area: 88, delay: 0.7, range: 520, dur: 2 },
    lv: { 3: { count: 1 }, 5: { area: 0.3 }, 7: { count: 1 } } },
  frostnova: { name: 'Frost Nova', icon: 'FN', elem: 'ice', kind: 'nova', color: '#90e0ef', dir: 'nearest',
    desc: 'Freezing blast around you. Erases enemy bullets.',
    base: { dmg: 22, cd: 7, area: 165, range: 170 },
    lv: { 3: { area: 0.2 }, 5: { dmg: 0.5 }, 7: { cd: -0.25 } } },
  thunder: { name: 'Thunderstorm', icon: 'TS', elem: 'shock', kind: 'thunder', color: '#fdf0d5', dir: 'strongest',
    desc: 'Lightning strikes several targets at once.',
    base: { dmg: 36, cd: 6, count: 5, area: 48, range: 520 },
    lv: { 3: { count: 2 }, 5: { dmg: 0.4 }, 7: { count: 3 } } },
  blackhole: { name: 'Black Hole', icon: 'BH', elem: 'arcane', kind: 'zone', color: '#7209b7', dir: 'cluster',
    desc: 'Tears open a singularity that drags and crushes.',
    base: { dmg: 16, cd: 10, area: 125, dur: 3, pull: 210, range: 460 },
    lv: { 3: { dur: 0.3 }, 5: { area: 0.3 }, 7: { dmg: 0.6 } } },
  heal: { name: 'Rejuvenate', icon: 'RJ', elem: 'poison', kind: 'heal', color: '#80ffdb', dir: 'nearest', noTarget: 1,
    desc: 'Restores a portion of your health.',
    base: { dmg: 0.15, cd: 14, range: 0 },
    lv: { 3: { cd: -0.15 }, 5: { dmg: 0.5 }, 7: { cd: -0.2 } } },
  warp: { name: 'Time Warp', icon: 'TW', elem: 'arcane', kind: 'warp', color: '#b8c0ff', dir: 'nearest', noTarget: 1,
    desc: 'Slows every enemy and bullet to a crawl.',
    base: { dmg: 0, cd: 16, dur: 3, range: 0 },
    lv: { 3: { dur: 0.3 }, 5: { cd: -0.2 }, 7: { dur: 0.4 } } },
  barrier: { name: 'Aegis Barrier', icon: 'AE', elem: 'arcane', kind: 'barrier', color: '#48cae4', dir: 'nearest', noTarget: 1,
    desc: 'Shield that reflects enemy bullets and blocks contact.',
    base: { dmg: 12, cd: 12, dur: 3, area: 80, range: 0 },
    lv: { 3: { dur: 0.35 }, 5: { area: 0.3 }, 7: { cd: -0.25 } } },
  bladestorm: { name: 'Blade Storm', icon: 'BS', elem: 'phys', kind: 'ring', color: '#e9ecef', dir: 'nearest', noTarget: 1,
    desc: 'Explodes a ring of blades outward.',
    base: { dmg: 19, cd: 6, count: 16, speed: 460, pierce: 3, range: 360, size: 6 },
    lv: { 3: { count: 8 }, 5: { pierce: 3 }, 7: { dmg: 0.5 } } },
  cloud: { name: 'Plague Cloud', icon: 'PC', elem: 'poison', kind: 'zone', color: '#9ef01a', dir: 'cluster',
    desc: 'A drifting cloud of stacking poison.',
    base: { dmg: 11, cd: 9, area: 115, dur: 5, pull: 0, range: 460 },
    lv: { 3: { dur: 0.4 }, 5: { area: 0.3 }, 7: { dmg: 0.6 } } },
  sentry: { name: 'Sentry Turret', icon: 'SN', elem: 'shock', kind: 'sentry', color: '#ffd60a', dir: 'nearest', noTarget: 1,
    desc: 'Deploys an auto-turret that uses this directive.',
    base: { dmg: 9, cd: 13, count: 1, dur: 10, rate: 0.25, range: 400 },
    lv: { 3: { dur: 0.3 }, 5: { count: 1 }, 7: { dmg: 0.5 } } },
};

const RARITIES = [
  { id: 'common',    name: 'Common',    color: '#b0bec5', mult: 1,   lvls: 1, w: 60 },
  { id: 'rare',      name: 'Rare',      color: '#4dabf7', mult: 1.5, lvls: 1, w: 27 },
  { id: 'epic',      name: 'Epic',      color: '#b565f6', mult: 2,   lvls: 2, w: 10 },
  { id: 'legendary', name: 'Legendary', color: '#ffb400', mult: 3,   lvls: 3, w: 3 },
];

// Passive power-ups. v = value per stack at common rarity; rarity multiplies it.
const PASSIVES = {
  might:     { name: 'Might',            icon: 'MT', max: 8, v: 0.12, fmt: v => `+${pc(v)} damage`, apply: (P, v) => { P.might += v; } },
  haste:     { name: 'Trigger Discipline', icon: 'TD', max: 8, v: 0.10, fmt: v => `+${pc(v)} fire rate`, apply: (P, v) => { P.haste += v; } },
  reload:    { name: 'Quick Hands',      icon: 'QH', max: 6, v: 0.15, fmt: v => `+${pc(v)} reload speed`, apply: (P, v) => { P.reloadSpd += v; } },
  mag:       { name: 'Extended Mags',    icon: 'EM', max: 6, v: 0.20, fmt: v => `+${pc(v)} magazine size`, apply: (P, v) => { P.magMult += v; } },
  multishot: { name: 'Multishot',        icon: 'MS', max: 3, v: 1, minRarity: 2, fmt: v => `+${Math.round(v)} projectile for all weapons`, apply: (P, v) => { P.multishot += Math.round(v); } },
  velocity:  { name: 'Velocity',         icon: 'VE', max: 5, v: 0.12, fmt: v => `+${pc(v)} projectile speed and range`, apply: (P, v) => { P.projSpeed += v; P.range += v * 0.6; } },
  area:      { name: 'Blast Radius',     icon: 'BR', max: 6, v: 0.12, fmt: v => `+${pc(v)} area of effect`, apply: (P, v) => { P.area += v; } },
  duration:  { name: 'Longevity',        icon: 'LG', max: 5, v: 0.15, fmt: v => `+${pc(v)} effect duration`, apply: (P, v) => { P.dur += v; } },
  pierce:    { name: 'Penetrator',       icon: 'PN', max: 4, v: 1, fmt: v => `+${Math.round(v)} pierce`, apply: (P, v) => { P.pierce += Math.round(v); } },
  crit:      { name: 'Deadeye',          icon: 'DE', max: 6, v: 0.05, fmt: v => `+${pc(v)} crit chance`, apply: (P, v) => { P.crit += v; } },
  critdmg:   { name: 'Executioner',      icon: 'EX', max: 6, v: 0.25, fmt: v => `+${pc(v)} crit damage`, apply: (P, v) => { P.critDmg += v; } },
  vital:     { name: 'Vital Core',       icon: 'VC', max: 8, v: 15, fmt: v => `+${Math.round(v)} max HP (and heal it)`, apply: (P, v, G) => { P.maxHp += Math.round(v); G.player.hp += Math.round(v); } },
  regen:     { name: 'Nanites',          icon: 'NA', max: 5, v: 0.3, fmt: v => `+${v.toFixed(1)} HP/sec regen`, apply: (P, v) => { P.regen += v; } },
  speed:     { name: 'Sprint Servos',    icon: 'SP', max: 5, v: 0.08, fmt: v => `+${pc(v)} move speed`, apply: (P, v) => { P.speed += v; } },
  magnet:    { name: 'Tractor Field',    icon: 'TF', max: 5, v: 0.3, fmt: v => `+${pc(v)} pickup range`, apply: (P, v) => { P.magnet += v; } },
  armour:    { name: 'Plating',          icon: 'PT', max: 6, v: 1, fmt: v => `+${Math.round(v)} armour (flat damage reduction)`, apply: (P, v) => { P.armour += Math.round(v); } },
  luck:      { name: 'Fortune',          icon: 'FO', max: 5, v: 0.15, fmt: v => `+${pc(v)} luck (rarer loot, more drops)`, apply: (P, v) => { P.luck += v; } },
  vamp:      { name: 'Vampiric Rounds',  icon: 'VR', max: 5, v: 0.08, fmt: v => `Heal ${v.toFixed(2)} HP per kill`, apply: (P, v) => { P.lifesteal += v; } },
  pyro:      { name: 'Pyromancy',        icon: 'PY', max: 5, v: 0.25, fmt: v => `+${pc(v)} fire damage and burn`, apply: (P, v) => { P.elem.fire += v; } },
  cryo:      { name: 'Cryomancy',        icon: 'CY', max: 5, v: 0.25, fmt: v => `+${pc(v)} frost damage and chill`, apply: (P, v) => { P.elem.ice += v; } },
  storm:     { name: 'Stormcaller',      icon: 'SC', max: 5, v: 0.25, fmt: v => `+${pc(v)} shock damage, +1 chain`, apply: (P, v) => { P.elem.shock += v; P.chain += 1; } },
  toxin:     { name: 'Toxicology',       icon: 'TX', max: 5, v: 0.25, fmt: v => `+${pc(v)} poison damage, +3 max stacks`, apply: (P, v) => { P.elem.poison += v; P.poisonCap += 3; } },
  arcanum:   { name: 'Arcanum',          icon: 'AR', max: 5, v: 0.25, fmt: v => `+${pc(v)} arcane damage`, apply: (P, v) => { P.elem.arcane += v; } },
  kinetic:   { name: 'Ballistics',       icon: 'BA', max: 5, v: 0.25, fmt: v => `+${pc(v)} kinetic damage`, apply: (P, v) => { P.elem.phys += v; } },
  catalyst:  { name: 'Catalyst',         icon: 'CT', max: 5, v: 0.35, fmt: v => `+${pc(v)} elemental reaction damage`, apply: (P, v) => { P.react += v; } },
  echo:      { name: 'Spell Echo',       icon: 'SE', max: 5, v: 0.10, fmt: v => `-${pc(v)} spell cooldowns`, apply: (P, v) => { P.cdr = Math.max(0.4, P.cdr - v); } },
  scholar:   { name: 'Scholar',          icon: 'SH', max: 5, v: 0.12, fmt: v => `+${pc(v)} experience gained`, apply: (P, v) => { P.xp += v; } },
  evasion:   { name: 'Evasion',          icon: 'EV', max: 5, v: 0.04, fmt: v => `+${pc(v)} chance to dodge hits`, apply: (P, v) => { P.dodge = Math.min(0.5, P.dodge + v); } },
};
function pc(v) { return Math.round(v * 100) + '%'; }

// Element reactions (triggered when an element hits an enemy already carrying another status).
const REACTIONS = {
  thermal:   { name: 'THERMAL SHOCK', color: '#ff9e9e', desc: 'Fire on a chilled/frozen enemy: big burst damage' },
  steam:     { name: 'STEAM BURST',   color: '#e0fbfc', desc: 'Frost on a burning enemy: scalding area blast' },
  combust:   { name: 'COMBUSTION',    color: '#ffba08', desc: 'Fire on a poisoned enemy: poison stacks explode' },
  toxicarc:  { name: 'TOXIC ARC',     color: '#d4ff5c', desc: 'Shock on a poisoned enemy: poison spreads to neighbours' },
  supercon:  { name: 'SUPERCONDUCT',  color: '#bde0fe', desc: 'Shock on a chilled enemy: armour shredded' },
  resonance: { name: 'RESONANCE',     color: '#e0aaff', desc: 'Arcane on any status: bonus damage, mark spreads' },
  overload:  { name: 'OVERLOAD',      color: '#fff3b0', desc: 'Fire on a shocked enemy: lightning explosion' },
};

// Elemental synergy set bonuses: owning N weapons/spells of one element.
const SYNERGIES = {
  phys:   { name: 'Gunslinger',  desc: '+15% fire rate for kinetic weapons' },
  fire:   { name: 'Pyromaniac',  desc: 'Burns last longer and deal +50% damage' },
  ice:    { name: 'Permafrost',  desc: 'Freeze threshold halved, frozen take +25%' },
  shock:  { name: 'Conductor',   desc: 'Shocked enemies arc twice as often' },
  poison: { name: 'Plaguebringer', desc: 'Poison ticks twice as fast' },
  arcane: { name: 'Arcanist',    desc: 'Marks amplify damage by +50% instead of +30%' },
};

// Enemies. from = seconds before they can spawn, w = spawn weight.
const ENEMIES = {
  crawler:  { name: 'Crawler', hp: 14, speed: 64, armour: 0, r: 12, dmg: 8, xp: 1, color: '#ff4d6d', shape: 'circle', ai: 'chase', from: 0, w: 10 },
  skitter:  { name: 'Skitter', hp: 6, speed: 125, armour: 0, r: 8, dmg: 5, xp: 1, color: '#ffa94d', shape: 'tri', ai: 'chase', from: 15, w: 7 },
  spitter:  { name: 'Spitter', hp: 20, speed: 58, armour: 0, r: 13, dmg: 6, xp: 3, color: '#e056fd', shape: 'diamond', ai: 'ranged', from: 35, w: 4,
    shoot: { pattern: 'aimed', cd: 2.6, speed: 170, dmg: 6 } },
  brute:    { name: 'Brute', hp: 60, speed: 44, armour: 3, r: 20, dmg: 16, xp: 4, color: '#c77d4a', shape: 'square', ai: 'chase', from: 55, w: 4 },
  bomber:   { name: 'Bomber', hp: 16, speed: 98, armour: 0, r: 12, dmg: 18, xp: 2, color: '#ff2e2e', shape: 'spike', ai: 'bomber', from: 100, w: 3 },
  splitter: { name: 'Splitter', hp: 42, speed: 52, armour: 0, r: 17, dmg: 10, xp: 3, color: '#43e97b', shape: 'hex', ai: 'chase', from: 85, w: 3, split: 'splitling' },
  splitling:{ name: 'Splitling', hp: 12, speed: 92, armour: 0, r: 9, dmg: 5, xp: 1, color: '#7af5a8', shape: 'hex', ai: 'chase', from: 99999, w: 0 },
  wisp:     { name: 'Wisp', hp: 4, speed: 145, armour: 0, r: 6, dmg: 4, xp: 0.5, color: '#fee440', shape: 'circle', ai: 'chase', from: 95, w: 2, group: 9 },
  blinker:  { name: 'Blinker', hp: 22, speed: 72, armour: 0, r: 12, dmg: 9, xp: 3, color: '#00f5d4', shape: 'diamond', ai: 'blink', from: 105, w: 2 },
  medic:    { name: 'Mender', hp: 30, speed: 56, armour: 1, r: 13, dmg: 6, xp: 4, color: '#7bed9f', shape: 'cross', ai: 'medic', from: 120, w: 2 },
  charger:  { name: 'Ram', hp: 50, speed: 56, armour: 2, r: 16, dmg: 18, xp: 4, color: '#f15bb5', shape: 'tri', ai: 'charge', from: 130, w: 3 },
  bulwark:  { name: 'Bulwark', hp: 95, speed: 40, armour: 8, r: 20, dmg: 14, xp: 6, color: '#8da9c4', shape: 'square', ai: 'aura', from: 150, w: 2 },
  warlock:  { name: 'Warlock', hp: 45, speed: 46, armour: 1, r: 15, dmg: 8, xp: 6, color: '#9b5de5', shape: 'star', ai: 'ranged', from: 170, w: 2,
    shoot: { pattern: 'ring', count: 8, cd: 3.2, speed: 140, dmg: 9 } },
  phantom:  { name: 'Phantom', hp: 35, speed: 82, armour: 0, r: 13, dmg: 10, xp: 5, color: '#caf0f8', shape: 'circle', ai: 'phase', from: 195, w: 2 },
  summoner: { name: 'Broodmother', hp: 75, speed: 40, armour: 2, r: 18, dmg: 10, xp: 8, color: '#ff8fab', shape: 'oct', ai: 'summon', from: 210, w: 1.2 },
  spire:    { name: 'Spire', hp: 85, speed: 16, armour: 4, r: 18, dmg: 10, xp: 8, color: '#ff006e', shape: 'hex', ai: 'turret', from: 240, w: 1.5,
    shoot: { pattern: 'spiral', cd: 0.16, speed: 125, dmg: 7 } },
  lancer:   { name: 'Lancer', hp: 26, speed: 52, armour: 0, r: 13, dmg: 6, xp: 5, color: '#ff99c8', shape: 'tri', ai: 'ranged', from: 260, w: 1.5,
    shoot: { pattern: 'snipe', cd: 3.6, speed: 430, dmg: 16 } },
  juggernaut: { name: 'Juggernaut', hp: 420, speed: 34, armour: 12, r: 28, dmg: 30, xp: 20, color: '#8d99ae', shape: 'oct', ai: 'chase', from: 300, w: 0.6 },
};

const BOSSES = [
  { id: 'queen',    name: 'THE HIVE QUEEN', hp: 2600, speed: 46, armour: 2, r: 44, dmg: 25, xp: 60, color: '#ff4d6d', shape: 'star', patterns: ['spiral', 'summon', 'ring', 'aimedFan'] },
  { id: 'colossus', name: 'IRON COLOSSUS',  hp: 4200, speed: 36, armour: 10, r: 52, dmg: 35, xp: 90, color: '#adb5bd', shape: 'oct', patterns: ['ring', 'charge', 'aimedFan', 'doubleSpiral'] },
  { id: 'voideye',  name: 'THE VOID EYE',   hp: 3400, speed: 52, armour: 4, r: 46, dmg: 30, xp: 80, color: '#7b2cbf', shape: 'eye', patterns: ['doubleSpiral', 'blink', 'ring', 'flower'] },
];
const BOSS_INTERVAL = 180; // seconds

// Field power-ups.
const POWERUPS = {
  magnet: { name: 'MAGNET',  letter: 'M', color: '#4cc9f0', desc: 'All XP flies to you' },
  nuke:   { name: 'NUKE',    letter: 'N', color: '#ff595e', desc: 'Obliterates nearby enemies' },
  rage:   { name: 'OVERDRIVE', letter: 'O', color: '#ff924c', desc: 'Double fire rate, no reloads' },
  heal:   { name: 'MEDKIT',  letter: '+', color: '#8ac926', desc: 'Restore 35% HP' },
  shield: { name: 'SHIELD',  letter: 'S', color: '#48cae4', desc: 'Invulnerable for 5s' },
  freeze: { name: 'STASIS',  letter: 'F', color: '#a2d2ff', desc: 'Freeze all enemies' },
  chest:  { name: 'LOOT BOX', letter: '?', color: '#ffca3a', desc: 'Free upgrade' },
};
